// Title: F5 BIG-IP iControl Rest API Command Execution - Proxy
// Author: Nasreddine Bencherchali (Nextron Systems), Thurein Oo
// Date: 2023-11-08
// Level: medium
// Description: Detects POST requests to the F5 BIG-IP iControl Rest API "bash" endpoint, which allows the execution of commands on the BIG-IPThis table contains proxy logs, which can be queried to retrieve relevant information related to proxy activity. Make sure to have the necessary connectors or data sources configured in Sentinel to collect and ingest proxy logs into this table.
// Tags: attack.initial-access, attack.t1190
// ================================================================== 

ProxyLog
| where 'c-uri' endswith "/mgmt/tm/util/bash" and 'cs-method' =~ "POST"