// Title: Ingress/Egress Security Group Modification
// Author: jamesc-grafana
// Date: 2024-07-11
// Level: medium
// Description: Detects when an account makes changes to the ingress or egress rules of a security group.
// This can indicate that an attacker is attempting to open up new attack vectors in the account, that they are trying to exfiltrate data over the network, or that they are trying to allow machines in that VPC/Subnet to contact a C&C server.
// The equivalent table in Microsoft Sentinel for AWS CloudTrail logs. Ensure that the AWS CloudTrail connector is set up in Sentinel to collect and ingest these logs.
// Tags: attack.initial-access, attack.t1190
// ================================================================== 

CloudTrail
| where (eventName in~ ("AuthorizeSecurityGroupEgress", "AuthorizeSecurityGroupIngress", "RevokeSecurityGroupEgress", "RevokeSecurityGroupIngress")) and eventSource =~ "ec2.amazonaws.com"