// Title: LoadBalancer Security Group Modification
// Author: jamesc-grafana
// Date: 2024-07-11
// Level: medium
// Description: Detects changes to the security groups associated with an Elastic Load Balancer (ELB) or Application Load Balancer (ALB).
// This can indicate that a misconfiguration allowing more traffic into the system than required, or could indicate that an attacker is attempting to enable new connections into a VPC or subnet controlled by the account.
// The equivalent table in Microsoft Sentinel for AWS CloudTrail logs. Make sure to have the AWS CloudTrail connector set up in Sentinel to collect and ingest these logs.
// Tags: attack.initial-access, attack.t1190
// ================================================================== 

CloudTrail
| where (eventName in~ ("ApplySecurityGroupsToLoadBalancer", "SetSecurityGroups")) and eventSource =~ "elasticloadbalancing.amazonaws.com"