// Title: OpenCanary - HTTP POST Login Attempt
// Author: Security Onion Solutions
// Date: 2024-03-08
// Level: high
// Description: Detects instances where an HTTP service on an OpenCanary node has had login attempt via Form POST.
// This table contains logs related to the Opencanary application. To have this table present in Microsoft Sentinel, you need to ensure that Opencanary logs are being collected and sent to Sentinel for analysis.
// Tags: attack.initial-access, attack.t1190
// ================================================================== 

OpencanaryLogs
| where logtype == 3001