// Title: Potential Server Side Template Injection In Velocity
// Author: Moti Harmats
// Date: 2023-02-11
// Level: high
// Description: Detects exceptions in velocity template renderer, this most likely happens due to dynamic rendering of user input and may lead to RCE.This table contains information about application requests, including error logs. To specifically query for logs with LOG_LEVEL=ERROR and above, you can filter on the severityLevel field in this table.
// Tags: attack.initial-access, attack.t1190
// ================================================================== 

AppRequests
| where "ParseErrorException" or "VelocityException" or "TemplateInitException"