// Title: Potential SpEL Injection In Spring Framework
// Author: Moti Harmats
// Date: 2023-02-11
// Level: high
// Description: Detects potential SpEL Injection exploitation, which may lead to RCE.This table contains application request logs, including error logs with LOG_LEVEL=ERROR and above. Additional components or logsources related to Spring applications may need to be installed in Sentinel to have this table present.
// Tags: attack.initial-access, attack.t1190
// ================================================================== 

AppRequests
| where "org.springframework.expression.ExpressionException"