// Title: Suspicious VSFTPD Error Messages
// Author: Florian Roth (Nextron Systems)
// Date: 2017-07-05
// Level: medium
// Description: Detects suspicious VSFTPD error messages that indicate a fatal or suspicious error that could be caused by exploiting attemptsThe LinuxAuditLogs table in Microsoft Sentinel contains audit logs from Linux machines. To have this table present, ensure that the Linux machines are onboarded to Sentinel and the necessary data connectors are configured to collect audit logs.
// Tags: attack.initial-access, attack.t1190
// ================================================================== 

LinuxAuditLogs
| where "Connection refused: too many sessions for this address." or "Connection refused: tcp_wrappers denial." or "Bad HTTP verb." or "port and pasv both active" or "pasv and port both active" or "Transfer done (but failed to open directory)." or "Could not set file modification time." or "bug: pid active in ptrace_sandbox_free" or "PTRACE_SETOPTIONS failure" or "weird status:" or "couldn't handle sandbox event" or "syscall * out of bounds" or "syscall not permitted:" or "syscall validate failed:" or "Input line too long." or "poor buffer accounting in str_netfd_alloc" or "vsf_sysutil_read_loop"