// Title: Suspicious SQL Error Messages
// Author: Bjoern Kimminich
// Date: 2017-11-27
// Level: high
// Description: Detects SQL error messages that indicate probing for an injection attackThis table contains application error logs with LOG_LEVEL ERROR and above. Ensure that the necessary connectors are set up to collect application error logs in Microsoft Sentinel.
// Tags: attack.initial-access, attack.t1190
// ================================================================== 

AppEvents
| where "quoted string not properly terminated" or "You have an error in your SQL syntax" or "Unclosed quotation mark" or "near \"*\": syntax error" or "SELECTs to the left and right of UNION do not have the same number of result columns"