// Title: Kerberos Manipulation
// Author: Florian Roth (Nextron Systems)
// Date: 2017-02-10
// Level: high
// Description: Detects failed Kerberos TGT issue operation. This can be a sign of manipulations of TGT messages by an attacker.The SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. To have this table present, ensure that you have the necessary data connectors set up in Sentinel to collect security events from Windows machines.
// Tags: attack.credential-access, attack.t1212
// ================================================================== 

SecurityEvent
| where Status in~ ("0x9", "0xA", "0xB", "0xF", "0x10", "0x11", "0x13", "0x14", "0x1A", "0x1F", "0x21", "0x22", "0x23", "0x24", "0x26", "0x27", "0x28", "0x29", "0x2C", "0x2D", "0x2E", "0x2F", "0x31", "0x32", "0x3E", "0x3F", "0x40", "0x41", "0x43", "0x44")