// Title: User Has Been Deleted Via Userdel
// Author: Tuan Le (NCSGroup)
// Date: 2022-12-26
// Level: medium
// Description: Detects execution of the "userdel" binary. Which is used to delete a user account and related files. This is sometimes abused by threat actors in order to cover their tracks
// Tags: attack.impact, attack.t1531
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "/userdel"