// Title: Print History File Contents
// Author: Florian Roth (Nextron Systems)
// Date: 2022-06-20
// Level: medium
// Description: Detects events in which someone prints the contents of history files to the commandline or redirects it to a file for reconnaissance
// Tags: attack.reconnaissance, attack.t1592.004
// ================================================================== 

DeviceProcessEvents
| where (FolderPath endswith "/cat" or FolderPath endswith "/head" or FolderPath endswith "/tail" or FolderPath endswith "/more") and ((ProcessCommandLine contains "/.bash_history" or ProcessCommandLine contains "/.zsh_history") or (ProcessCommandLine endswith "_history" or ProcessCommandLine endswith ".history" or ProcessCommandLine endswith "zhistory"))