// Description: Identify emails that were send from an address external to your company and where email was send to more then 50 distinct corporate users.
// Update corporatedomain.com to your corporate domain to have it excluded.
// Update 50 if you want to adjust the distinct user count.
// Required Connectors: MicrosoftThreatProtection (Types: EmailEvents)

EmailEvents 
| where SenderFromDomain != "corporatedomain.com" 
| summarize dcount(RecipientEmailAddress) by SenderFromAddress, NetworkMessageId, AttachmentCount, SendTime = Timestamp 
| where dcount_RecipientEmailAddress > 50