// Title: Suspicious Curl File Upload - Linux
// Author: Nasreddine Bencherchali (Nextron Systems), Cedric MAURUGEON (Update)
// Date: 2022-09-15
// Level: medium
// Description: Detects a suspicious curl process start the adds a file to a web request
// Tags: attack.exfiltration, attack.t1567, attack.t1105
// ================================================================== 

DeviceProcessEvents
| where (((ProcessCommandLine contains " --form" or ProcessCommandLine contains " --upload-file " or ProcessCommandLine contains " --data " or ProcessCommandLine contains " --data-") or ProcessCommandLine matches regex "\\s-[FTd]\\s") and FolderPath endswith "/curl") and (not((ProcessCommandLine contains "://localhost" or ProcessCommandLine contains "://127.0.0.1")))