// Title: UAC Bypass Using ChangePK and SLUI
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-23
// Level: high
// Description: Detects an UAC bypass that uses changepk.exe and slui.exe (UACMe 61)
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "\\changepk.exe" and (ProcessIntegrityLevel in~ ("High", "System", "S-1-16-16384", "S-1-16-12288")) and InitiatingProcessFolderPath endswith "\\slui.exe"