// Title: UAC Bypass Using Windows Media Player - File
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-23
// Level: high
// Description: Detects the pattern of UAC Bypass using Windows Media Player osksupport.dll (UACMe 32)
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// ================================================================== 

DeviceFileEvents
| where (FolderPath endswith "\\AppData\\Local\\Temp\\OskSupport.dll" and FolderPath startswith "C:\\Users\\") or (InitiatingProcessFolderPath =~ "C:\\Windows\\system32\\DllHost.exe" and FolderPath =~ "C:\\Program Files\\Windows Media Player\\osk.exe")