// Title: File Deletion
// Author: Ömer Günal, oscd.community
// Date: 2020-10-07
// Level: informational
// Description: Detects file deletion using "rm", "shred" or "unlink" commands which are used often by adversaries to delete files left behind by the actions of their intrusion activity
// Tags: attack.defense-evasion, attack.t1070.004
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "/rm" or FolderPath endswith "/shred" or FolderPath endswith "/unlink"