// Title: BITS Transfer Job With Uncommon Or Suspicious Remote TLD
// Author: Florian Roth (Nextron Systems)
// Date: 2022-06-10
// Level: medium
// Description: Detects a suspicious download using the BITS client from a FQDN that is unusual. Adversaries may abuse BITS jobs to persistently execute or clean up after malicious payloads.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which may include logs related to the BITS client service. Ensure that Windows security event logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.defense-evasion, attack.persistence, attack.t1197
// ================================================================== 

SecurityEvent
| where not((RemoteName contains ".azureedge.net/" or RemoteName contains ".com/" or RemoteName contains ".sfx.ms/" or RemoteName contains "download.mozilla.org/" or RemoteName contains "cdn.onenote.net/" or RemoteName contains "cdn.office.net/"))