// Title: Credentials In Files
// Author: Igor Fits, Mikhail Larin, oscd.community
// Date: 2020-10-19
// Level: high
// Description: Detecting attempts to extract passwords with grep and laZagne
// Tags: attack.credential-access, attack.t1552.001
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "password" and FolderPath endswith "/grep") or ProcessCommandLine contains "laZagne"