// Title: WSF/JSE/JS/VBA/VBE File Execution Via Cscript/Wscript
// Author: Michael Haag
// Date: 2019-01-16
// Level: medium
// Description: Detects script file execution (.js, .jse, .vba, .vbe, .vbs, .wsf) by Wscript/Cscript
// Tags: attack.execution, attack.t1059.005, attack.t1059.007, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains ".js" or ProcessCommandLine contains ".jse" or ProcessCommandLine contains ".vba" or ProcessCommandLine contains ".vbe" or ProcessCommandLine contains ".vbs" or ProcessCommandLine contains ".wsf") and ((ProcessVersionInfoOriginalFileName in~ ("wscript.exe", "cscript.exe")) or (FolderPath endswith "\\wscript.exe" or FolderPath endswith "\\cscript.exe"))