// Title: Malicious ShellIntel PowerShell Commandlets
// Author: Max Altgelt (Nextron Systems), Tobias Michalski (Nextron Systems)
// Date: 2021-08-09
// Level: high
// Description: Detects Commandlet names from ShellIntel exploitation scripts.This table contains Windows security event logs, including script block logging events. Enable the appropriate data connectors in Microsoft Sentinel to collect Windows security event logs.
// Tags: attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Invoke-SMBAutoBrute" or ScriptBlockText contains "Invoke-GPOLinks" or ScriptBlockText contains "Invoke-Potato"