// Title: Powershell MsXml COM Object
// Author: frack113, MatilJ
// Date: 2022-01-19
// Level: medium
// Description: Adversaries may abuse PowerShell commands and scripts for execution.
// PowerShell is a powerful interactive command-line interface and scripting environment included in the Windows operating system. (Citation: TechNet PowerShell)
// Adversaries can use PowerShell to perform a number of actions, including discovery of information and execution of code
// This table contains Windows security event logs, including script block logging events. Make sure to enable the appropriate data connectors in Microsoft Sentinel to collect Windows security event logs.
// Tags: attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "New-Object" and ScriptBlockText contains "-ComObject" and ScriptBlockText contains "MsXml2." and ScriptBlockText contains "XmlHttp"