// Title: Powershell XML Execute Command
// Author: frack113
// Date: 2022-01-19
// Level: medium
// Description: Adversaries may abuse PowerShell commands and scripts for execution.
// PowerShell is a powerful interactive command-line interface and scripting environment included in the Windows operating system. (Citation: TechNet PowerShell)
// Adversaries can use PowerShell to perform a number of actions, including discovery of information and execution of code
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script block logging. Ensure that the Windows security events are being collected and ingested into Sentinel for this table to be available.
// Tags: attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "IEX " or ScriptBlockText contains "Invoke-Expression " or ScriptBlockText contains "Invoke-Command " or ScriptBlockText contains "ICM -") and (ScriptBlockText contains "New-Object" and ScriptBlockText contains "System.Xml.XmlDocument" and ScriptBlockText contains ".Load")