// Title: PowerShell Create Local User
// Author: @ROxPinTeddy
// Date: 2020-04-11
// Level: medium
// Description: Detects creation of a local user via PowerShellThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.execution, attack.t1059.001, attack.persistence, attack.t1136.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "New-LocalUser"