// Title: PSAsyncShell - Asynchronous TCP Reverse Shell
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-04
// Level: high
// Description: Detects the use of PSAsyncShell an Asynchronous TCP Reverse Shell written in powershellThis table contains Windows security event logs, including script block logging events. Ensure that the required data connectors are set up in Sentinel to collect Windows security event logs.
// Tags: attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "PSAsyncShell"