// Title: Remote PowerShell Sessions Network Connections (WinRM)
// Author: Roberto Rodriguez @Cyb3rWard0g
// Date: 2019-09-12
// Level: high
// Description: Detects basic PowerShell Remoting (WinRM) by monitoring for network inbound connections to ports 5985 OR 5986The SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. To have this table present, ensure that you have the necessary data connectors set up to collect security events from Windows machines.
// Tags: attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (DestPort in~ ("5985", "5986")) and LayerRTID == 44