// Title: Suspicious PowerShell Download - PoshModule
// Author: Florian Roth (Nextron Systems)
// Date: 2017-03-05
// Level: medium
// Description: Detects suspicious PowerShell download commandThis table contains security-related events from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to collect data from this table.
// Tags: attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ContextInfo contains ".DownloadFile(" or ContextInfo contains ".DownloadString(") and ContextInfo contains "System.Net.WebClient"