// Title: Suspicious PowerShell Download
// Author: Florian Roth (Nextron Systems)
// Date: 2017-03-05
// Level: medium
// Description: Detects suspicious PowerShell download commandThe SecurityEvent table in Microsoft Sentinel contains Windows security events. Make sure to have the Windows Security Events connector enabled in Sentinel to collect this data.
// Tags: attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (Data contains ".DownloadFile(" or Data contains ".DownloadString(") and Data contains "Net.WebClient"