// Title: Capsh Shell Invocation - Linux
// Author: Li Ling, Andy Parkidomo, Robert Rakowski, Blake Hartstein (Bloomberg L.P.)
// Date: 2024-09-02
// Level: high
// Description: Detects the use of the "capsh" utility to invoke a shell.
// 
// Tags: attack.execution, attack.t1059
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine endswith " --" and FolderPath endswith "/capsh"