// Title: Potential Xterm Reverse Shell
// Author: @d4ns4n_
// Date: 2023-04-24
// Level: medium
// Description: Detects usage of "xterm" as a potential reverse shell tunnel
// Tags: attack.execution, attack.t1059
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "-display" and ProcessCommandLine endswith ":1" and FolderPath contains "xterm"