// Title: AWS SecurityHub Findings Evasion
// Author: Sittikorn S
// Date: 2021-06-28
// Level: high
// Description: Detects the modification of the findings on SecurityHub.The CloudTrail table in Microsoft Sentinel contains logs related to AWS CloudTrail service. To have this table present in Sentinel, you need to ensure that the AWS connector is properly configured and collecting CloudTrail logs.
// Tags: attack.defense-evasion, attack.t1562
// ================================================================== 

CloudTrail
| where (eventName in~ ("BatchUpdateFindings", "DeleteInsight", "UpdateFindings", "UpdateInsight")) and eventSource =~ "securityhub.amazonaws.com"