// Title: Azure Kubernetes Events Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-07-24
// Level: medium
// Description: Detects when Events are deleted in Azure Kubernetes. An adversary may delete events in Azure Kubernetes in an attempt to evade detection.This table contains Azure activity logs data. Ensure that Azure Activity Logs connector is enabled in Microsoft Sentinel to collect this data.
// Tags: attack.defense-evasion, attack.t1562, attack.t1562.001
// ================================================================== 

AzureActivityLogs
| where operationName =~ "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/EVENTS.K8S.IO/EVENTS/DELETE"