// Title: Google Cloud Firewall Modified or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-08-13
// Level: medium
// Description: Detects  when a firewall rule is modified or deleted in Google Cloud Platform (GCP).This table contains GCP audit logs. To have this table present in Microsoft Sentinel, you need to ensure that GCP audit logs are being ingested into Sentinel and mapped to the appropriate schema.
// Tags: attack.defense-evasion, attack.t1562
// ================================================================== 

GCPAuditLogs
| where ('gcp.audit.method_name' contains "v" and 'gcp.audit.method_name' contains ".Compute.Firewalls.Delete") or ('gcp.audit.method_name' contains "v" and 'gcp.audit.method_name' contains ".Compute.Firewalls.Patch") or ('gcp.audit.method_name' contains "v" and 'gcp.audit.method_name' contains ".Compute.Firewalls.Update") or ('gcp.audit.method_name' contains "v" and 'gcp.audit.method_name' contains ".Compute.Firewalls.Insert")