// Title: Removal Of Index Value to Hide Schedule Task - Registry
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-26
// Level: medium
// Description: Detects when the "index" value of a scheduled task is removed or deleted from the registry. Which effectively hides it from any tooling such as "schtasks /query"
// Tags: attack.defense-evasion, attack.t1562
// ================================================================== 

DeviceRegistryEvents
| where (ActionType in~ ("RegistryKeyDeleted", "RegistryValueDeleted")) and (RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tree*" and RegistryKey contains "Index")