// Title: Sysmon Application Crashed
// Author: Tim Shelton
// Date: 2022-04-26
// Level: high
// Description: Detects application popup reporting a failure of the Sysmon serviceThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events are being collected and ingested into Sentinel for this table to be available.
// Tags: attack.defense-evasion, attack.t1562
// ================================================================== 

SecurityEvent
| where (Caption in~ ("sysmon64.exe - Application Error", "sysmon.exe - Application Error")) and Provider_Name =~ "Application Popup"