// Title: Potential Data Exfiltration Via Curl.EXE
// Author: Florian Roth (Nextron Systems), Cedric MAURUGEON (Update)
// Date: 2020-07-03
// Level: medium
// Description: Detects the execution of the "curl" process with "upload" flags. Which might indicate potential data exfiltration
// Tags: attack.exfiltration, attack.t1567, attack.t1105, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where (((ProcessCommandLine contains " --form" or ProcessCommandLine contains " --upload-file " or ProcessCommandLine contains " --data " or ProcessCommandLine contains " --data-") or ProcessCommandLine matches regex "\\s-[FTd]\\s") and (FolderPath endswith "\\curl.exe" or ProcessVersionInfoProductName =~ "The curl executable")) and (not((ProcessCommandLine contains "://localhost" or ProcessCommandLine contains "://127.0.0.1")))