// Title: File Time Attribute Change
// Author: Igor Fits, Mikhail Larin, oscd.community
// Date: 2020-10-19
// Level: medium
// Description: Detect file time attribute change to hide new or changes to existing files
// Tags: attack.defense-evasion, attack.t1070.006
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "-t" or ProcessCommandLine contains "-acmr" or ProcessCommandLine contains "-d" or ProcessCommandLine contains "-r") and FolderPath endswith "/touch"