// Title: Unauthorized System Time Modification
// Author: @neu5ron
// Date: 2019-02-05
// Level: low
// Description: Detect scenarios where a potentially unauthorized application or user is modifying the system time.The SecurityEvent table in Microsoft Sentinel contains security-related events, including audit policy changes and security state changes. To query this table, ensure that the Windows Security Events data connector is enabled in Sentinel.
// Tags: attack.defense-evasion, attack.t1070.006
// ================================================================== 

SecurityEvent
| where not(((InitiatingProcessFolderPath in~ ("C:\\Program Files\\VMware\\VMware Tools\\vmtoolsd.exe", "C:\\Windows\\System32\\VBoxService.exe", "C:\\Windows\\System32\\oobe\\msoobe.exe")) or (InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\svchost.exe" and SubjectUserSid =~ "S-1-5-19")))