// Title: Default Credentials Usage
// Author: Alexandr Yampolskyi, SOC Prime
// Date: 2019-03-26
// Level: medium
// Description: Before deploying any new asset, change all default passwords to have values consistent with administrative level accounts.
// Sigma detects default credentials usage. Sigma for Qualys vulnerability scanner. Scan type - Vulnerability Management.
// This table contains vulnerability assessment data from Qualys. Ensure that the Qualys connector is set up in Microsoft Sentinel to collect data from the Qualys API and populate this table.
// Tags: attack.initial-access
// ================================================================== 

QualysVulnerabilities
| where 'host.scan.vuln' in~ ("10693", "11507", "11633", "11804", "11821", "11847", "11867", "11931", "11935", "11950", "12541", "12558", "12559", "12560", "12562", "12563", "12565", "12587", "12590", "12599", "12702", "12705", "12706", "12907", "12928", "12929", "13053", "13178", "13200", "13218", "13241", "13253", "13274", "13296", "13301", "13327", "13373", "13374", "13409", "13530", "13532", "20065", "20073", "20081", "27202", "27358", "38702", "38719", "42045", "42417", "43029", "43220", "43221", "43222", "43223", "43225", "43246", "43431", "43484", "86857", "87098", "87106")