// Title: System Network Connections Discovery - MacOs
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2020-10-19
// Level: informational
// Description: Detects usage of system utilities to discover system network connections
// Tags: attack.discovery, attack.t1049
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "/who" or FolderPath endswith "/w" or FolderPath endswith "/last" or FolderPath endswith "/lsof" or FolderPath endswith "/netstat"