// Title: Potential COM Object Hijacking Via TreatAs Subkey - Registry
// Author: Kutepov Anton, oscd.community
// Date: 2019-10-23
// Level: medium
// Description: Detects COM object hijacking via TreatAs subkey
// Tags: attack.persistence, attack.t1546.015
// ================================================================== 

DeviceRegistryEvents
| where (ActionType =~ "RegistryKeyCreated" and (RegistryKey endswith "HKU*" and RegistryKey endswith "Classes\\CLSID*" and RegistryKey contains "\\TreatAs")) and (not(InitiatingProcessFolderPath =~ "C:\\WINDOWS\\system32\\svchost.exe"))