// Title: Suspicious Start-Process PassThru
// Author: frack113
// Date: 2022-01-15
// Level: medium
// Description: Powershell use PassThru option to start in backgroundThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1036.003
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Start-Process" and ScriptBlockText contains "-PassThru " and ScriptBlockText contains "-FilePath "