// Title: Old TLS1.0/TLS1.1 Protocol Version Enabled
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-05
// Level: medium
// Description: Detects applications or users re-enabling old TLS versions by setting the "Enabled" value to "1" for the "Protocols" registry key.
// Tags: attack.defense-evasion
// ================================================================== 

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and (RegistryKey endswith "\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0*" or RegistryKey endswith "\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1*") and RegistryKey endswith "\\Enabled"