// Title: Renamed Microsoft Teams Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-07-12
// Level: medium
// Description: Detects the execution of a renamed Microsoft Teams binary.
// Tags: attack.defense-evasion
// ================================================================== 

DeviceProcessEvents
| where (ProcessVersionInfoOriginalFileName in~ ("msteams.exe", "teams.exe")) and (not((FolderPath endswith "\\msteams.exe" or FolderPath endswith "\\teams.exe")))