// Title: Windows Kernel Debugger Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-15
// Level: medium
// Description: Detects execution of the Windows Kernel Debugger "kd.exe".
// Tags: attack.defense-evasion, attack.privilege-escalation
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "\\kd.exe" or ProcessVersionInfoOriginalFileName =~ "kd.exe"