// Title: Potential In-Memory Download And Compile Of Payloads
// Author: Sohan G (D4rkCiph3r), Red Canary (idea)
// Date: 2023-08-22
// Level: medium
// Description: Detects potential in-memory downloading and compiling of applets using curl and osacompile as seen used by XCSSET malware
// Tags: attack.command-and-control, attack.execution, attack.t1059.007, attack.t1105
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "osacompile" and ProcessCommandLine contains "curl"