// Title: Request A Single Ticket via PowerShell
// Author: frack113
// Date: 2021-12-28
// Level: high
// Description: utilize native PowerShell Identity modules to query the domain to extract the Service Principal Names for a single computer.
// This behavior is typically used during a kerberos or silver ticket attack.
// A successful execution will output the SPNs for the endpoint in question.
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows Security events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.credential-access, attack.t1558.003
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "System.IdentityModel.Tokens.KerberosRequestorSecurityToken"