// Title: UAC Bypass Using IEInstal - Process
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-30
// Level: high
// Description: Detects the pattern of UAC Bypass using IEInstal.exe (UACMe 64)
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// ================================================================== 

DeviceProcessEvents
| where FolderPath contains "\\AppData\\Local\\Temp\\" and FolderPath endswith "consent.exe" and (ProcessIntegrityLevel in~ ("High", "System", "S-1-16-16384", "S-1-16-12288")) and InitiatingProcessFolderPath endswith "\\ieinstal.exe"