// Title: UAC Bypass Using PkgMgr and DISM
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-23
// Level: high
// Description: Detects the pattern of UAC Bypass using pkgmgr.exe and dism.exe (UACMe 23)
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "\\dism.exe" and (ProcessIntegrityLevel in~ ("High", "System", "S-1-16-16384", "S-1-16-12288")) and InitiatingProcessFolderPath endswith "\\pkgmgr.exe"