// Title: AWS EC2 Disable EBS Encryption
// Author: Sittikorn S
// Date: 2021-06-29
// Level: medium
// Description: Identifies disabling of default Amazon Elastic Block Store (EBS) encryption in the current region.
// Disabling default encryption does not change the encryption status of your existing volumes.
// The equivalent table in Microsoft Sentinel for AWS CloudTrail logs. Ensure that the AWS CloudTrail connector is set up in Sentinel to collect and ingest these logs.
// Tags: attack.impact, attack.t1486, attack.t1565
// ================================================================== 

CloudTrail
| where eventName =~ "DisableEbsEncryptionByDefault" and eventSource =~ "ec2.amazonaws.com"