// Title: Security Software Discovery - Linux
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2020-10-19
// Level: low
// Description: Detects usage of system utilities (only grep and egrep for now) to discover security software discovery
// Tags: attack.discovery, attack.t1518.001
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "nessusd" or ProcessCommandLine contains "td-agent" or ProcessCommandLine contains "packetbeat" or ProcessCommandLine contains "filebeat" or ProcessCommandLine contains "auditbeat" or ProcessCommandLine contains "osqueryd" or ProcessCommandLine contains "cbagentd" or ProcessCommandLine contains "falcond") and (FolderPath endswith "/grep" or FolderPath endswith "/egrep")