// Title: Clearing Windows Console History
// Author: Austin Songer @austinsonger
// Date: 2021-11-25
// Level: high
// Description: Identifies when a user attempts to clear console history. An adversary may clear the command history of a compromised account to conceal the actions undertaken during an intrusion.This table contains security event logs from Windows machines. Ensure that the Windows Security Events data connector is enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1070, attack.t1070.003
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Clear-History" or ((ScriptBlockText contains "Remove-Item" or ScriptBlockText contains "rm") and (ScriptBlockText contains "ConsoleHost_history.txt" or ScriptBlockText contains "(Get-PSReadlineOption).HistorySavePath"))