// Title: Disable of ETW Trace - Powershell
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-28
// Level: high
// Description: Detects usage of powershell cmdlets to disable or remove ETW trace sessionsThis table contains security-related events, including PowerShell script execution events. Ensure that the necessary data connectors are set up to collect Windows security event logs in Sentinel.
// Tags: attack.defense-evasion, attack.t1070, attack.t1562.006, car.2016-04-002
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Remove-EtwTraceProvider " or (ScriptBlockText contains "Set-EtwTraceProvider " and ScriptBlockText contains "0x11")