// Title: Remove Exported Mailbox from Exchange Webserver
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-27
// Level: high
// Description: Detects removal of an exported Exchange mailbox which could be to cover tracks from ProxyShell exploitThe OfficeActivity table in Microsoft Sentinel contains logs related to Microsoft Exchange management activities on Windows servers. To have this table present in Sentinel, ensure that you have the necessary connectors or data sources configured to collect logs from the msexchange-management service on Windows servers.
// Tags: attack.defense-evasion, attack.t1070
// ================================================================== 

OfficeActivity
| where "Remove-MailboxExportRequest" and " -Identity " and " -Confirm \"False\""