// Title: SES Identity Has Been Deleted
// Author: Janantha Marasinghe
// Date: 2022-12-13
// Level: medium
// Description: Detects an instance of an SES identity being deleted via the "DeleteIdentity" event. This may be an indicator of an adversary removing the account that carried out suspicious or malicious activitiesThe CloudTrail table in Microsoft Sentinel contains logs related to AWS CloudTrail service. To have this table present in Sentinel, ensure that the AWS CloudTrail connector is configured and sending logs to Sentinel.
// Tags: attack.defense-evasion, attack.t1070
// ================================================================== 

CloudTrail
| where eventName =~ "DeleteIdentity" and eventSource =~ "ses.amazonaws.com"