// Title: Terminal Server Client Connection History Cleared - Registry
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-10-19
// Level: high
// Description: Detects the deletion of registry keys containing the MSTSC connection history
// Tags: attack.defense-evasion, attack.t1070, attack.t1112
// ================================================================== 

DeviceRegistryEvents
| where (ActionType =~ "DeleteValue" and RegistryKey contains "\\Microsoft\\Terminal Server Client\\Default\\MRU") or ((ActionType in~ ("RegistryKeyDeleted", "RegistryValueDeleted")) and RegistryKey endswith "\\Microsoft\\Terminal Server Client\\Servers*")