// Title: Execute Invoke-command on Remote Host
// Author: frack113
// Date: 2022-01-07
// Level: medium
// Description: Adversaries may use Valid Accounts to interact with remote systems using Windows Remote Management (WinRM). The adversary may then perform actions as the logged-on user.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows Security Events data connector is enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.lateral-movement, attack.t1021.006
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "invoke-command " and ScriptBlockText contains " -ComputerName "