// Title: Kubernetes Secrets Enumeration
// Author: Leo Tsaousis (@laripping)
// Date: 2024-03-26
// Level: low
// Description: Detects enumeration of Kubernetes secrets.The KubeEvents table in Microsoft Sentinel contains Kubernetes audit logs. To have this table present, ensure that you have the necessary connectors or data sources set up to collect Kubernetes audit logs in Sentinel.
// Tags: attack.t1552.007
// ================================================================== 

KubeEvents
| where 'objectRef.resource' =~ "secrets" and verb =~ "list"