// Title: Windows Screen Capture with CopyFromScreen
// Author: frack113
// Date: 2021-12-28
// Level: medium
// Description: Adversaries may attempt to take screen captures of the desktop to gather information over the course of an operation.
// Screen capturing functionality may be included as a feature of a remote access tool used in post-compromise operations
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include events related to PowerShell script execution. Ensure that the Windows Security events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.collection, attack.t1113
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains ".CopyFromScreen"