// Title: HackTool - SILENTTRINITY Stager DLL Load
// Author: Aleksey Potapov, oscd.community
// Date: 2019-10-22
// Level: high
// Description: Detects SILENTTRINITY stager dll loading activity
// Tags: attack.command-and-control, attack.t1071
// ================================================================== 

DeviceImageLoadEvents
| where InitiatingProcessVersionInfoFileDescription contains "st2stager"