// Title: PetitPotam Suspicious Kerberos TGT Request
// Author: Mauricio Velazco, Michael Haag
// Date: 2021-09-02
// Level: high
// Description: Detect suspicious Kerberos TGT requests.
// Once an attacer obtains a computer certificate by abusing Active Directory Certificate Services in combination with PetitPotam, the next step would be to leverage the certificate for malicious purposes.
// One way of doing this is to request a Kerberos Ticket Granting Ticket using a tool like Rubeus.
// This request will generate a 4768 event with some unusual fields depending on the environment.
// This analytic will require tuning, we recommend filtering Account_Name to the Domain Controller computer accounts.
// The SecurityEvent table in Microsoft Sentinel contains security-related events, including account logon events and Kerberos authentication events. Ensure that the necessary data connectors are set up in Sentinel to collect Windows security logs.
// Tags: attack.credential-access, attack.t1187
// ================================================================== 

SecurityEvent
| where (CertThumbprint startswith "" and TargetUserName endswith "$") and (not((IpAddress =~ "::1" or CertThumbprint =~ "")))