// Title: Remote Thread Creation Via PowerShell In Uncommon Target
// Author: Florian Roth (Nextron Systems)
// Date: 2018-06-25
// Level: medium
// Description: Detects the creation of a remote thread from a Powershell process in an uncommon target processThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. To query for events related to creating remote threads, you can filter on the EventID field and look for events with EventID 8.
// Tags: attack.defense-evasion, attack.execution, attack.t1218.011, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") and (TargetImage endswith "\\rundll32.exe" or TargetImage endswith "\\regsvr32.exe")