// Title: Remote Schedule Task Lateral Movement via ITaskSchedulerService
// Author: Sagie Dulce, Dekel Paz
// Date: 2022-01-01
// Level: high
// Description: Detects remote RPC calls to create or execute a scheduled taskThis table contains logs related to the RPC Firewall product. Make sure to onboard RPC Firewall logs to Microsoft Sentinel to have this table available for querying.
// Tags: attack.lateral-movement, attack.t1053, attack.t1053.002
// ================================================================== 

rpc_firewall_logs
| where EventLog =~ "RPCFW" and InterfaceUuid =~ "86d35949-83c9-4044-b424-db363231fd0c" and (OpNum in~ ("1", "3", "4", "10", "11", "12", "13", "14", "15"))