// Title: Remote Schedule Task Lateral Movement via SASec
// Author: Sagie Dulce, Dekel Paz
// Date: 2022-01-01
// Level: high
// Description: Detects remote RPC calls to create or execute a scheduled task via SASecThis table contains logs related to RPC Firewall activity. To have this table present in Microsoft Sentinel, ensure that RPC Firewall logs are being collected and sent to Sentinel for analysis.
// Tags: attack.lateral-movement, attack.t1053, attack.t1053.002
// ================================================================== 

rpc_firewall_logs
| where EventLog =~ "RPCFW" and InterfaceUuid =~ "378e52b0-c0a9-11cf-822d-00aa0051e40f" and (OpNum in~ ("0", "1"))