// Title: Restricted Software Access By SRP
// Author: frack113
// Date: 2023-01-12
// Level: high
// Description: Detects restricted access to applications by the Software Restriction Policies (SRP) policyThe WindowsEvent table in Microsoft Sentinel contains logs related to Windows events. To have this table present, ensure that you have the necessary data connectors set up to collect Windows event logs from your environment.
// Tags: attack.defense-evasion, attack.t1072
// ================================================================== 

WindowsEvent
| where Provider_Name =~ "Microsoft-Windows-SoftwareRestrictionPolicies"