// Title: Disable PUA Protection on Windows Defender
// Author: Austin Songer @austinsonger
// Date: 2021-08-04
// Level: high
// Description: Detects disabling Windows Defender PUA protection
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey contains "\\Policies\\Microsoft\\Windows Defender\\PUAProtection"