// Title: Sysmon Driver Altitude Change
// Author: B.Talebi
// Date: 2022-07-28
// Level: high
// Description: Detects changes in Sysmon driver altitude value.
// If the Sysmon driver is configured to load at an altitude of another registered service, it will fail to load at boot.
// 
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

DeviceRegistryEvents
| where RegistryKey endswith "\\Services*" and RegistryKey endswith "\\Instances\\Sysmon Instance\\Altitude"