// Title: AWS EFS Fileshare Mount Modified or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-08-15
// Level: medium
// Description: Detects when a EFS Fileshare Mount is modified or deleted. An adversary breaking any file system using the mount target that is being deleted, which might disrupt instances or applications using those mounts.The equivalent table in Microsoft Sentinel for AWS CloudTrail logs. Ensure that the AWS CloudTrail connector is set up in Sentinel to collect these logs.
// Tags: attack.impact, attack.t1485
// ================================================================== 

CloudTrail
| where eventName =~ "DeleteMountTarget" and eventSource =~ "elasticfilesystem.amazonaws.com"