// Title: Azure Device or Configuration Modified or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-09-03
// Level: medium
// Description: Identifies when a device or device configuration in azure is modified or deleted.This table contains Azure Activity Logs data. Ensure that the Azure Activity Logs connector is enabled in Microsoft Sentinel to have this table available for querying.
// Tags: attack.impact, attack.t1485, attack.t1565.001
// ================================================================== 

AzureActivityLogs
| where 'properties.message' in~ ("Delete device", "Delete device configuration", "Update device", "Update device configuration")