// Title: Activity from Suspicious IP Addresses
// Author: Austin Songer @austinsonger
// Date: 2021-08-23
// Level: medium
// Description: Detects when a Microsoft Cloud App Security reported users were active from an IP address identified as risky by Microsoft Threat Intelligence.
// These IP addresses are involved in malicious activities, such as Botnet C&C, and may indicate compromised account.
// The OfficeActivity table in Microsoft Sentinel contains logs related to Microsoft 365 activity. Ensure that the Microsoft 365 data connector is set up and collecting logs from the threat_detection service.
// Tags: attack.command-and-control, attack.t1573
// ================================================================== 

OfficeActivity
| where eventName =~ "Activity from suspicious IP addresses" and eventSource =~ "SecurityComplianceCenter" and status =~ "success"