// Title: Activity from Infrequent Country
// Author: Austin Songer @austinsonger
// Date: 2021-08-23
// Level: medium
// Description: Detects when a Microsoft Cloud App Security reported when an activity occurs from a location that wasn't recently or never visited by any user in the organization.This table contains threat intelligence indicators, including indicators from Microsoft 365. Ensure that Threat Intelligence data connector is enabled in Microsoft Sentinel to have this table available for querying.
// Tags: attack.command-and-control, attack.t1573
// ================================================================== 

ThreatIntelligenceIndicator
| where eventName =~ "Activity from infrequent country" and eventSource =~ "SecurityComplianceCenter" and status =~ "success"