// Title: Remote CHM File Download/Execution Via HH.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-29
// Level: high
// Description: Detects the usage of "hh.exe" to execute/download remotely hosted ".chm" files.
// Tags: attack.defense-evasion, attack.t1218.001
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://" or ProcessCommandLine contains "\\\\") and (ProcessVersionInfoOriginalFileName =~ "HH.exe" or FolderPath endswith "\\hh.exe")