// Title: Activity From Anonymous IP Address
// Author: Mark Morowczynski '@markmorow', Gloria Lee, '@gleeiamglo'
// Date: 2023-09-03
// Level: high
// Description: Identifies that users were active from an IP address that has been identified as an anonymous proxy IP address.The AzureActivity table in Microsoft Sentinel contains logs related to Azure services, including risk detection events. To ensure this table is populated, make sure to have the Azure Monitor logs solution installed in Sentinel and properly configured to collect logs from the Azure service 'riskdetection'.
// Tags: attack.t1078, attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.initial-access
// ================================================================== 

AzureActivity
| where riskEventType =~ "riskyIPAddress"