// Title: Azure Kubernetes Admission Controller
// Author: Austin Songer @austinsonger
// Date: 2021-11-25
// Level: medium
// Description: Identifies when an admission controller is executed in Azure Kubernetes.
// A Kubernetes Admission controller intercepts, and possibly modifies, requests to the Kubernetes API server.
// The behavior of this admission controller is determined by an admission webhook (MutatingAdmissionWebhook or ValidatingAdmissionWebhook) that the user deploys in the cluster.
// An adversary can use such webhooks as the MutatingAdmissionWebhook for obtaining persistence in the cluster.
// For example, attackers can intercept and modify the pod creation operations in the cluster and add their malicious container to every created pod.
// An adversary can use the webhook ValidatingAdmissionWebhook, which could be used to obtain access credentials.
// An adversary could use the webhook to intercept the requests to the API server, record secrets, and other sensitive information.
// This table contains Azure activity logs. Ensure that Azure Activity Logs connector is enabled in Microsoft Sentinel to have this table available for querying.
// Tags: attack.persistence, attack.t1078, attack.credential-access, attack.t1552, attack.t1552.007
// ================================================================== 

AzureActivityLogs
| where (operationName endswith "/MUTATINGWEBHOOKCONFIGURATIONS/WRITE" or operationName endswith "/VALIDATINGWEBHOOKCONFIGURATIONS/WRITE") and (operationName startswith "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/ADMISSIONREGISTRATION.K8S.IO" or operationName startswith "MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS/ADMISSIONREGISTRATION.K8S.IO")