// Title: Google Cloud Kubernetes Admission Controller
// Author: Austin Songer @austinsonger
// Date: 2021-11-25
// Level: medium
// Description: Identifies when an admission controller is executed in GCP Kubernetes.
// A Kubernetes Admission controller intercepts, and possibly modifies, requests to the Kubernetes API server.
// The behavior of this admission controller is determined by an admission webhook (MutatingAdmissionWebhook or ValidatingAdmissionWebhook) that the user deploys in the cluster.
// An adversary can use such webhooks as the MutatingAdmissionWebhook for obtaining persistence in the cluster.
// For example, attackers can intercept and modify the pod creation operations in the cluster and add their malicious container to every created pod. An adversary can use the webhook ValidatingAdmissionWebhook, which could be used to obtain access credentials.
// An adversary could use the webhook to intercept the requests to the API server, record secrets, and other sensitive information.
// This table contains GCP audit logs. To have this table present in Microsoft Sentinel, ensure that the GCP connector is set up and configured to ingest audit logs from the 'gcp.audit' service within the GCP product.
// Tags: attack.persistence, attack.t1078, attack.credential-access, attack.t1552, attack.t1552.007
// ================================================================== 

GCPAuditLogs
| where (''gcp.audit.method_name'' contains ".mutatingwebhookconfigurations." or ''gcp.audit.method_name'' contains ".validatingwebhookconfigurations.") and (''gcp.audit.method_name'' endswith "create" or ''gcp.audit.method_name'' endswith "patch" or ''gcp.audit.method_name'' endswith "replace") and 'gcp.audit.method_name' startswith "admissionregistration.k8s.io.v"