// Title: Impossible Travel
// Author: Mark Morowczynski '@markmorow', Gloria Lee, '@gleeiamglo'
// Date: 2023-09-03
// Level: high
// Description: Identifies user activities originating from geographically distant locations within a time period shorter than the time it takes to travel from the first location to the second.The AzureActivity table in Microsoft Sentinel contains logs related to Azure services, including risk detection events. Ensure that Azure Activity logs are being collected and ingested into Sentinel to query this table.
// Tags: attack.t1078, attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.initial-access
// ================================================================== 

AzureActivity
| where riskEventType =~ "impossibleTravel"