// Title: PIM Alert Setting Changes To Disabled
// Author: Mark Morowczynski '@markmorow', Yochana Henderson, '@Yochana-H'
// Date: 2022-08-09
// Level: high
// Description: Detects when PIM alerts are set to disabled.This table contains Azure activity logs, which includes audit logs. Ensure that Azure Diagnostics logs are enabled for the Azure service in question to populate this table.
// Tags: attack.persistence, attack.privilege-escalation, attack.t1078
// ================================================================== 

AzureActivity
| where 'properties.message' =~ "Disable PIM Alert"