// Title: Roles Assigned Outside PIM
// Author: Mark Morowczynski '@markmorow', Gloria Lee, '@gleeiamglo'
// Date: 2023-09-14
// Level: high
// Description: Identifies when a privilege role assignment has taken place outside of PIM and may indicate an attack.The AzureActivity table in Microsoft Sentinel contains logs related to Azure activity, including Azure PIM (Privileged Identity Management) logs. Ensure that Azure Activity logs are being collected and ingested into Sentinel to query this table.
// Tags: attack.t1078, attack.persistence, attack.privilege-escalation
// ================================================================== 

AzureActivity
| where riskEventType =~ "rolesAssignedOutsidePrivilegedIdentityManagementAlertConfiguration"