// Title: Unfamiliar Sign-In Properties
// Author: Mark Morowczynski '@markmorow', Gloria Lee, '@gleeiamglo'
// Date: 2023-09-03
// Level: high
// Description: Detects sign-in with properties that are unfamiliar to the user. The detection considers past sign-in history to look for anomalous sign-ins.The AzureActivity table in Microsoft Sentinel contains logs related to Azure services, including risk detection events. Ensure that Azure Activity logs are being collected and ingested into Sentinel to query this table.
// Tags: attack.t1078, attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.initial-access
// ================================================================== 

AzureActivity
| where riskEventType =~ "unfamiliarFeatures"