// Title: Credential Dumping Attempt Via Svchost
// Author: Florent Labouyrie
// Date: 2021-04-30
// Level: high
// Description: Detects when a process tries to access the memory of svchost to potentially dump credentials.The SecurityEvent table in Microsoft Sentinel contains process access logs for Windows systems. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.t1548
// ================================================================== 

SecurityEvent
| where (GrantedAccess =~ "0x143a" and TargetImage endswith "\\svchost.exe") and (not((InitiatingProcessFolderPath endswith "\\services.exe" or InitiatingProcessFolderPath endswith "\\msiexec.exe")))