// Title: Suspicious Curl Change User Agents - Linux
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-15
// Level: medium
// Description: Detects a suspicious curl process start on linux with set useragent options
// Tags: attack.command-and-control, attack.t1071.001
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains " -A " or ProcessCommandLine contains " --user-agent ") and FolderPath endswith "/curl"