// Title: Apache Spark Shell Command Injection - ProcessCreation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-20
// Level: high
// Description: Detects attempts to exploit an apache spark server via CVE-2014-6287 from a commandline perspective
// Tags: attack.initial-access, attack.t1190, cve.2022-33891
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "id -Gn `" or ProcessCommandLine contains "id -Gn '") and InitiatingProcessFolderPath endswith "\\bash"