// Title: Monero Crypto Coin Mining Pool Lookup
// Author: Florian Roth (Nextron Systems)
// Date: 2021-10-24
// Level: high
// Description: Detects suspicious DNS queries to Monero mining poolsThis table contains DNS events and can be queried in KQL for Microsoft Sentinel. Make sure to have the necessary connectors or data sources configured in Sentinel to collect DNS logs.
// Tags: attack.impact, attack.t1496, attack.exfiltration, attack.t1567
// ================================================================== 

DnsEvents
| where query contains "pool.minexmr.com" or query contains "fr.minexmr.com" or query contains "de.minexmr.com" or query contains "sg.minexmr.com" or query contains "ca.minexmr.com" or query contains "us-west.minexmr.com" or query contains "pool.supportxmr.com" or query contains "mine.c3pool.com" or query contains "xmr-eu1.nanopool.org" or query contains "xmr-eu2.nanopool.org" or query contains "xmr-us-east1.nanopool.org" or query contains "xmr-us-west1.nanopool.org" or query contains "xmr-asia1.nanopool.org" or query contains "xmr-jp1.nanopool.org" or query contains "xmr-au1.nanopool.org" or query contains "xmr.2miners.com" or query contains "xmr.hashcity.org" or query contains "xmr.f2pool.com" or query contains "xmrpool.eu" or query contains "pool.hashvault.pro"