// Title: Persistence Via Sudoers Files
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-05
// Level: medium
// Description: Detects creation of sudoers file or files in "sudoers.d" directory which can be used a potential method to persiste privileges for a specific user.
// Tags: attack.persistence, attack.t1053.003
// ================================================================== 

DeviceFileEvents
| where FolderPath startswith "/etc/sudoers.d/"