// Title: Process Discovery
// Author: Ömer Günal, oscd.community, CheraaghiMilad
// Date: 2020-10-06
// Level: low
// Description: Detects process discovery commands. Adversaries may attempt to get information about running processes on a system.
// Information obtained could be used to gain an understanding of common software/applications running on systems within the network
// 
// Tags: attack.discovery, attack.t1057, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "/atop" or FolderPath endswith "/htop" or FolderPath endswith "/pgrep" or FolderPath endswith "/ps" or FolderPath endswith "/pstree" or FolderPath endswith "/top"