// Title: Dfsvc.EXE Network Connection To Non-Local IPs
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-12
// Level: medium
// Description: Detects network connections from "dfsvc.exe" used to handled ClickOnce applications to non-local IPs
// Tags: attack.execution, attack.t1203, detection.threat-hunting
// ================================================================== 

DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\dfsvc.exe" and (not((ipv4_is_in_range(RemoteIP, "127.0.0.0/8") or ipv4_is_in_range(RemoteIP, "10.0.0.0/8") or ipv4_is_in_range(RemoteIP, "169.254.0.0/16") or ipv4_is_in_range(RemoteIP, "172.16.0.0/12") or ipv4_is_in_range(RemoteIP, "192.168.0.0/16") or ipv4_is_in_range(RemoteIP, "::1/128") or ipv4_is_in_range(RemoteIP, "fe80::/10") or ipv4_is_in_range(RemoteIP, "fc00::/7"))))