// Title: ClickOnce Deployment Execution - Dfsvc.EXE Child Process
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-12
// Level: medium
// Description: Detects child processes of "dfsvc" which indicates a ClickOnce deployment execution.
// Tags: attack.execution, attack.defense-evasion, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "\\AppData\\Local\\Apps\\2.0\\" and InitiatingProcessFolderPath endswith "\\dfsvc.exe"