// Title: Import New Module Via PowerShell CommandLine
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-09
// Level: low
// Description: Detects usage of the "Import-Module" cmdlet in order to add new Cmdlets to the current PowerShell session
// Tags: attack.execution, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where ((ProcessCommandLine contains "Import-Module " or ProcessCommandLine contains "ipmo ") and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")))) and (not(((ProcessCommandLine contains ":\\Program Files\\Microsoft Visual Studio\\" and ProcessCommandLine contains "Tools\\Microsoft.VisualStudio.DevShell.dll") and (InitiatingProcessFolderPath contains ":\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_" or InitiatingProcessFolderPath contains ":\\Windows\\System32\\cmd.exe"))))