// Title: Container Residence Discovery Via Proc Virtual FS
// Author: Seth Hanford
// Date: 2023-08-23
// Level: low
// Description: Detects potential container discovery via listing of certain kernel features in the "/proc" virtual filesystem
// Tags: attack.discovery, attack.t1082
// ================================================================== 

DeviceProcessEvents
| where (FolderPath endswith "awk" or FolderPath endswith "/cat" or FolderPath endswith "grep" or FolderPath endswith "/head" or FolderPath endswith "/less" or FolderPath endswith "/more" or FolderPath endswith "/nl" or FolderPath endswith "/tail") and (ProcessCommandLine contains "/proc/2/" or (ProcessCommandLine contains "/proc/" and (ProcessCommandLine endswith "/cgroup" or ProcessCommandLine endswith "/sched")))