// Title: Recon Information for Export with PowerShell
// Author: frack113
// Date: 2021-07-30
// Level: medium
// Description: Once established within a system or network, an adversary may use automated techniques for collecting internal dataThis table contains security-related events, including PowerShell script execution events. Make sure to enable the necessary connectors and data sources in Sentinel to collect Windows security events.
// Tags: attack.collection, attack.t1119
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "Get-Service " or ScriptBlockText contains "Get-ChildItem " or ScriptBlockText contains "Get-Process ") and ScriptBlockText contains "> $env:TEMP\\"