// Title: File Download via CertOC.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-05-16
// Level: medium
// Description: Detects when a user downloads a file by using CertOC.exe
// Tags: attack.command-and-control, attack.t1105
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "-GetCACAPS" and ProcessCommandLine contains "http") and (FolderPath endswith "\\certoc.exe" or ProcessVersionInfoOriginalFileName =~ "CertOC.exe")