// Title: Potential COM Objects Download Cradles Usage - PS Script
// Author: frack113
// Date: 2022-12-25
// Level: medium
// Description: Detects usage of COM objects that can be abused to download files in PowerShell by CLSIDThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.command-and-control, attack.t1105
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "[Type]::GetTypeFromCLSID(" and (ScriptBlockText contains "0002DF01-0000-0000-C000-000000000046" or ScriptBlockText contains "F6D90F16-9C73-11D3-B32E-00C04F990BB4" or ScriptBlockText contains "F5078F35-C551-11D3-89B9-0000F81FE221" or ScriptBlockText contains "88d96a0a-f192-11d4-a65f-0040963251e5" or ScriptBlockText contains "AFBA6B42-5692-48EA-8141-DC517DCF0EF1" or ScriptBlockText contains "AFB40FFD-B609-40A3-9828-F88BBE11E4E3" or ScriptBlockText contains "88d96a0b-f192-11d4-a65f-0040963251e5" or ScriptBlockText contains "2087c2f4-2cef-4953-a8ab-66779b670495" or ScriptBlockText contains "000209FF-0000-0000-C000-000000000046" or ScriptBlockText contains "00024500-0000-0000-C000-000000000046")