// Title: Remote File Copy
// Author: Ömer Günal
// Date: 2020-06-18
// Level: low
// Description: Detects the use of tools that copy files from or to remote systemsThis table contains Linux audit logs in Microsoft Sentinel. To have this table present, ensure that the Linux machines are onboarded to Sentinel and the necessary data connectors are configured to collect Linux audit logs.
// Tags: attack.command-and-control, attack.lateral-movement, attack.t1105
// ================================================================== 

LinuxAuditLogs
| where ("scp " or "rsync " or "sftp ") and ("@" or ":")