// Title: Suspicious Diantz Download and Compress Into a CAB File
// Author: frack113
// Date: 2021-11-26
// Level: medium
// Description: Download and compress a remote file and store it in a cab file on local machine.
// Tags: attack.command-and-control, attack.t1105
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "diantz.exe" and ProcessCommandLine contains " \\\\" and ProcessCommandLine contains ".cab"