// Title: Azure Active Directory Hybrid Health AD FS Service Delete
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research), MSTIC
// Date: 2021-08-26
// Level: medium
// Description: This detection uses azureactivity logs (Administrative category) to identify the deletion of an Azure AD Hybrid health AD FS service instance in a tenant.
// A threat actor can create a new AD Health ADFS service and create a fake server to spoof AD FS signing logs.
// The health AD FS service can then be deleted after it is not longer needed via HTTP requests to Azure.
// This table contains Azure Activity Logs data. Ensure that Azure Activity Logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.defense-evasion, attack.t1578.003
// ================================================================== 

AzureActivityLogs
| where CategoryValue =~ "Administrative" and OperationNameValue =~ "Microsoft.ADHybridHealthService/services/delete" and ResourceId contains "AdFederationService" and ResourceProviderValue =~ "Microsoft.ADHybridHealthService"