// Title: Network Connection Initiated By PowerShell Process
// Author: Florian Roth (Nextron Systems)
// Date: 2017-03-13
// Level: low
// Description: Detects a network connection that was initiated from a PowerShell process.
// Often times malicious powershell scripts download additional payloads or communicate back to command and control channels via uncommon ports or IPs.
// Use this rule as a basis for hunting for anomalies.
// 
// Tags: attack.execution, attack.t1059.001, detection.threat-hunting
// ================================================================== 

DeviceNetworkEvents
| where (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") and (not((((ipv4_is_in_range(RemoteIP, "127.0.0.0/8") or ipv4_is_in_range(RemoteIP, "10.0.0.0/8") or ipv4_is_in_range(RemoteIP, "169.254.0.0/16") or ipv4_is_in_range(RemoteIP, "172.16.0.0/12") or ipv4_is_in_range(RemoteIP, "192.168.0.0/16") or ipv4_is_in_range(RemoteIP, "::1/128") or ipv4_is_in_range(RemoteIP, "fe80::/10") or ipv4_is_in_range(RemoteIP, "fc00::/7")) and (InitiatingProcessAccountName contains "AUTHORI" or InitiatingProcessAccountName contains "AUTORI")) or (ipv4_is_in_range(RemoteIP, "20.184.0.0/13") or ipv4_is_in_range(RemoteIP, "51.103.210.0/23")))))