// Title: Unusually Long PowerShell CommandLine
// Author: oscd.community, Natalia Shornikova
// Date: 2020-10-06
// Level: low
// Description: Detects unusually long PowerShell command lines with a length of 1000 characters or more
// Tags: attack.execution, attack.t1059.001, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine matches regex ".{1000,}" and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")) or ProcessVersionInfoFileDescription =~ "Windows Powershell" or ProcessVersionInfoProductName =~ "PowerShell Core 6")