// Title: OpenCanary - TFTP Request
// Author: Security Onion Solutions
// Date: 2024-03-08
// Level: high
// Description: Detects instances where a TFTP service on an OpenCanary node has had a request.The OpencanaryLogs table in Microsoft Sentinel contains logs related to the Opencanary application. To have this table present in Sentinel, you need to ensure that the Opencanary logs are being collected and sent to Sentinel for analysis.
// Tags: attack.exfiltration, attack.t1041
// ================================================================== 

OpencanaryLogs
| where logtype == 10001