// Title: UAC Bypass Using WOW64 Logger DLL Hijack
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-23
// Level: high
// Description: Detects the pattern of UAC Bypass using a WoW64 logger DLL hijack (UACMe 30)This table contains information about process creation events in Windows. To query this table in Microsoft Sentinel, ensure that the Windows Security Events data connector is enabled and collecting process creation events.
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// ================================================================== 

ProcessCreationEvents
| where CallTrace startswith "UNKNOWN(0000000000000000)|UNKNOWN(0000000000000000)|" and GrantedAccess =~ "0x1fffff" and InitiatingProcessFolderPath contains ":\\Windows\\SysWOW64\\"