// Title: Linux Base64 Encoded Shebang In CLI
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-15
// Level: medium
// Description: Detects the presence of a base64 version of the shebang in the commandline, which could indicate a malicious payload about to be decoded
// Tags: attack.defense-evasion, attack.t1140
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "IyEvYmluL2Jhc2" or ProcessCommandLine contains "IyEvYmluL2Rhc2" or ProcessCommandLine contains "IyEvYmluL3pza" or ProcessCommandLine contains "IyEvYmluL2Zpc2" or ProcessCommandLine contains "IyEvYmluL3No"