// Title: Hidden Flag Set On File/Directory Via Chflags - MacOS
// Author: Omar Khaled (@beacon_exe)
// Date: 2024-08-21
// Level: medium
// Description: Detects the execution of the "chflags" utility with the "hidden" flag, in order to hide files on MacOS.
// When a file or directory has this hidden flag set, it becomes invisible to the default file listing commands and in graphical file browsers.
// 
// Tags: attack.defense-evasion, attack.t1218, attack.t1564.004, attack.t1552.001, attack.t1105
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "hidden " and FolderPath endswith "/chflags"