// Title: Potential RemoteFXvGPUDisablement.EXE Abuse
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-07-13
// Level: high
// Description: Detects PowerShell module creation where the module Contents are set to "function Get-VMRemoteFXPhysicalVideoAdapter". This could be a sign of potential abuse of  the "RemoteFXvGPUDisablement.exe" binary which is known to be vulnerable to module load-order hijacking.The SecurityEvent table in Microsoft Sentinel contains logs from Windows security events, which may include PowerShell activity. Make sure to have the necessary data connectors set up in Sentinel to collect Windows security event logs.
// Tags: attack.defense-evasion, attack.t1218
// ================================================================== 

SecurityEvent
| where Data contains "ModuleContents=function Get-VMRemoteFXPhysicalVideoAdapter {"