// Title: Potential Provisioning Registry Key Abuse For Binary Proxy Execution
// Author: Nasreddine Bencherchali (Nextron Systems), Swachchhanda Shrawan Poudel
// Date: 2023-08-08
// Level: high
// Description: Detects potential abuse of the provisioning registry key for indirect command execution through "Provlaunch.exe".
// Tags: attack.defense-evasion, attack.t1218
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "SOFTWARE\\Microsoft\\Provisioning\\Commands\\"