// Title: SyncAppvPublishingServer Execution to Bypass Powershell Restriction
// Author: Ensar Şamil, @sblmsrsn, OSCD Community
// Date: 2020-10-05
// Level: medium
// Description: Detects SyncAppvPublishingServer process execution which usually utilized by adversaries to bypass PowerShell execution restrictions.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Make sure to have the necessary data connectors set up in Sentinel to collect Windows security event logs.
// Tags: attack.defense-evasion, attack.t1218
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "SyncAppvPublishingServer.exe"