// Title: AWS Route 53 Domain Transferred to Another Account
// Author: Elastic, Austin Songer @austinsonger
// Date: 2021-07-22
// Level: low
// Description: Detects when a request has been made to transfer a Route 53 domain to another AWS account.The CloudTrail table in Microsoft Sentinel contains logs related to AWS CloudTrail service. To query this table, ensure that the AWS CloudTrail connector is set up in Sentinel and ingesting logs from the specified AWS account.
// Tags: attack.persistence, attack.credential-access, attack.t1098
// ================================================================== 

CloudTrail
| where eventName =~ "TransferDomainToAnotherAwsAccount" and eventSource =~ "route53.amazonaws.com"