// Title: AWS IAM Backdoor Users Keys
// Author: faloker
// Date: 2020-02-12
// Level: medium
// Description: Detects AWS API key creation for a user by another user.
// Backdoored users can be used to obtain persistence in the AWS environment.
// Also with this alert, you can detect a flow of AWS keys in your org.
// The equivalent table in Microsoft Sentinel for AWS CloudTrail logs. Ensure that the AWS CloudTrail connector is set up in Sentinel to collect and ingest these logs.
// Tags: attack.persistence, attack.t1098
// ================================================================== 

CloudTrail
| where (eventName =~ "CreateAccessKey" and eventSource =~ "iam.amazonaws.com") and (not('userIdentity.arn' contains "responseElements.accessKey.userName"))