// Title: AWS Route 53 Domain Transfer Lock Disabled
// Author: Elastic, Austin Songer @austinsonger
// Date: 2021-07-22
// Level: low
// Description: Detects when a transfer lock was removed from a Route 53 domain. It is recommended to refrain from performing this action unless intending to transfer the domain to a different registrar.The equivalent table in Microsoft Sentinel for AWS CloudTrail logs. Ensure that the AWS CloudTrail connector is set up in Sentinel to collect these logs.
// Tags: attack.persistence, attack.credential-access, attack.t1098
// ================================================================== 

CloudTrail
| where eventName =~ "DisableDomainTransferLock" and eventSource =~ "route53.amazonaws.com"