// Title: Number Of Resource Creation Or Deployment Activities
// Author: sawwinnnaung
// Date: 2020-05-07
// Level: medium
// Description: Number of VM creations or deployment activities occur in Azure via the azureactivity log.This table contains Azure activity logs, which can be queried in KQL for Microsoft Sentinel. Ensure that the Azure Activity Logs connector is enabled in Sentinel to have this table available.
// Tags: attack.persistence, attack.t1098
// ================================================================== 

AzureActivityLogs
| where "Microsoft.Compute/virtualMachines/write" or "Microsoft.Resources/deployments/write"