// Title: Powershell LocalAccount Manipulation
// Author: frack113
// Date: 2021-12-28
// Level: medium
// Description: Adversaries may manipulate accounts to maintain access to victim systems.
// Account manipulation may consist of any action that preserves adversary access to a compromised account, such as modifying credentials or permission groups
// The SecurityEvent table in Microsoft Sentinel contains logs related to security events on Windows machines. To ensure that Script Block Logging events are present in this table, make sure to enable Script Block Logging on the Windows machines and configure the necessary data connectors in Sentinel to collect these logs.
// Tags: attack.persistence, attack.t1098
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Disable-LocalUser" or ScriptBlockText contains "Enable-LocalUser" or ScriptBlockText contains "Get-LocalUser" or ScriptBlockText contains "Set-LocalUser" or ScriptBlockText contains "New-LocalUser" or ScriptBlockText contains "Rename-LocalUser" or ScriptBlockText contains "Remove-LocalUser"