// Title: New Github Organization Member Added
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2023-01-29
// Level: informational
// Description: Detects when a new member is added or invited to a github organization.This table contains audit logs for the Github service. To query this table in Microsoft Sentinel, make sure to have the Github connector installed and properly configured to ingest audit logs.
// Tags: attack.persistence, attack.t1136.003
// ================================================================== 

GithubAuditLogs
| where action in~ ("org.add_member", "org.invite_member")