// Title: PsExec Default Named Pipe
// Author: Thomas Patzke
// Date: 2017-06-12
// Level: low
// Description: Detects PsExec service default pipe creationThis table contains Sysmon events, including Named Pipe Events (Event ID 17 and Event ID 18). To have this table present in Sentinel, you need to have Sysmon installed on your Windows endpoints and configured to log Named Pipe Events.
// Tags: attack.execution, attack.t1569.002, attack.s0029, detection.threat-hunting
// ================================================================== 

SysmonEvent
| where PipeName =~ "\\PSEXESVC"