// Title: HTTP Request With Empty User Agent
// Author: Florian Roth (Nextron Systems)
// Date: 2017-07-08
// Level: medium
// Description: Detects a potentially suspicious empty user agent strings in proxy log.
// Could potentially indicate an uncommon request method.
// This table contains proxy logs, which can be queried in Microsoft Sentinel. Make sure to have the necessary connectors or data sources configured in Sentinel to collect and ingest proxy logs into this table.
// Tags: attack.defense-evasion, attack.command-and-control, attack.t1071.001
// ================================================================== 

ProxyLog
| where 'c-useragent' =~ ""