// Title: Suspicious Splwow64 Without Params
// Author: Florian Roth (Nextron Systems)
// Date: 2021-08-23
// Level: high
// Description: Detects suspicious Splwow64.exe process without any command line parameters
// Tags: attack.defense-evasion, attack.t1202
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine endswith "splwow64.exe" and FolderPath endswith "\\splwow64.exe"