// Title: HackTool - RemoteKrbRelay SMB Relay Secrets Dump Module Indicators
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-06-27
// Level: high
// Description: Detects the creation of file with specific names used by RemoteKrbRelay SMB Relay attack module.
// Tags: attack.command-and-control, attack.t1219
// ================================================================== 

DeviceFileEvents
| where FolderPath endswith ":\\windows\\temp\\sam.tmp" or FolderPath endswith ":\\windows\\temp\\sec.tmp" or FolderPath endswith ":\\windows\\temp\\sys.tmp"