// Title: Mesh Agent Service Installation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-11-28
// Level: medium
// Description: Detects a Mesh Agent service installation. Mesh Agent is used to remotely manage computersThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events are being collected and ingested into Sentinel to query this table.
// Tags: attack.command-and-control, attack.t1219
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager" and (ImagePath contains "MeshAgent.exe" or ServiceName contains "Mesh Agent")