// Title: Remote Access Tool - ScreenConnect Potential Suspicious Remote Command Execution
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems), @Kostastsale
// Date: 2022-02-25
// Level: medium
// Description: Detects potentially suspicious child processes launched via the ScreenConnect client service.
// 
// Tags: attack.command-and-control, attack.t1219
// ================================================================== 

DeviceProcessEvents
| where (FolderPath endswith "\\bitsadmin.exe" or FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\curl.exe" or FolderPath endswith "\\dllhost.exe" or FolderPath endswith "\\net.exe" or FolderPath endswith "\\nltest.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\wevtutil.exe") and (InitiatingProcessCommandLine contains ":\\Windows\\TEMP\\ScreenConnect\\" and InitiatingProcessCommandLine contains "run.cmd")