// Title: TacticalRMM Service Installation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-11-28
// Level: medium
// Description: Detects a TacticalRMM service installation. Tactical RMM is a remote monitoring & management tool.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.command-and-control, attack.t1219
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager" and (ImagePath contains "tacticalrmm.exe" or ServiceName contains "TacticalRMM Agent Service")