// Title: DCERPC SMB Spoolss Named Pipe
// Author: OTR (Open Threat Research)
// Date: 2018-11-28
// Level: medium
// Description: Detects the use of the spoolss named pipe over SMB. This can be used to trigger the authentication via NTLM of any machine that has the spoolservice enabled.The SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. To have this table present, ensure that you have the necessary data connectors set up in Sentinel to collect security events from Windows machines.
// Tags: attack.lateral-movement, attack.t1021.002
// ================================================================== 

SecurityEvent
| where RelativeTargetName =~ "spoolss" and ShareName =~ "\\\\*\\IPC$"