// Title: First Time Seen Remote Named Pipe
// Author: Samir Bousseaden
// Date: 2019-04-03
// Level: high
// Description: This detection excludes known namped pipes accessible remotely and notify on newly observed ones, may help to detect lateral movement and remote exec using named pipesThe SecurityEvent table in Microsoft Sentinel contains security-related events and logs, including detailed file share access events. Make sure to have the necessary connectors and data sources configured in Sentinel to collect Windows security logs.
// Tags: attack.lateral-movement, attack.t1021.002
// ================================================================== 

SecurityEvent
| where ShareName =~ "\\\\*\\IPC$" and (not((RelativeTargetName in~ ("atsvc", "samr", "lsarpc", "lsass", "winreg", "netlogon", "srvsvc", "protected_storage", "wkssvc", "browser", "netdfs", "svcctl", "spoolss", "ntsvcs", "LSM_API_service", "HydraLsPipe", "TermSrv_API_service", "MsFteWds", "sql\\query", "eventlog"))))