// Title: PUA - RemCom Default Named Pipe
// Author: Nikita Nazarov, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-07
// Level: medium
// Description: Detects default RemCom pipe creationThis table contains Sysmon events, including Named Pipe Events (Event ID 17 and Event ID 18). To have this table present in Sentinel, you need to have Sysmon installed on your Windows endpoints and have the Sysmon connector configured to send data to Sentinel.
// Tags: attack.lateral-movement, attack.t1021.002, attack.execution, attack.t1569.002
// ================================================================== 

SysmonEvent
| where PipeName contains "\\RemCom"