// Title: PUA - CSExec Default Named Pipe
// Author: Nikita Nazarov, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-07
// Level: medium
// Description: Detects default CSExec pipe creationThis table contains Sysmon event logs, including Named Pipe Events (Event ID 17 and Event ID 18). Make sure to have Sysmon installed on the Windows machines and configured to log Named Pipe Events.
// Tags: attack.lateral-movement, attack.t1021.002, attack.execution, attack.t1569.002
// ================================================================== 

SysmonEvent
| where PipeName contains "\\csexecsvc"