// Title: SMB Spoolss Name Piped Usage
// Author: OTR (Open Threat Research), @neu5ron
// Date: 2018-11-28
// Level: medium
// Description: Detects the use of the spoolss named pipe over SMB. This can be used to trigger the authentication via NTLM of any machine that has the spoolservice enabled.Table containing SMB file access logs.
// Tags: attack.lateral-movement, attack.t1021.002
// ================================================================== 

SmbFiles
| where name =~ "spoolss" and path endswith "IPC$"