// Title: SMB Create Remote File Admin Share
// Author: Jose Rodriguez (@Cyb3rPandaH), OTR (Open Threat Research)
// Date: 2020-08-06
// Level: high
// Description: Look for non-system accounts SMB accessing a file with write (0x2) access mask via administrative share (i.e C$).The SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. Make sure to have the Windows Security Events connector enabled in Sentinel to populate this table.
// Tags: attack.lateral-movement, attack.t1021.002
// ================================================================== 

SecurityEvent
| where (AccessMask =~ "0x2" and ShareName endswith "C$") and (not(SubjectUserName endswith "$"))