// Title: smbexec.py Service Installation
// Author: Omer Faruk Celik
// Date: 2018-03-20
// Level: high
// Description: Detects the use of smbexec.py tool by detecting a specific service installationThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events connector is installed and configured in Sentinel to have this table available for querying.
// Tags: attack.lateral-movement, attack.execution, attack.t1021.002, attack.t1569.002
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager" and ((ImagePath contains ".bat & del " or ImagePath contains "__output 2^>^&1 >") or ServiceName =~ "BTOBTO")