// Title: Suspicious PsExec Execution - Zeek
// Author: Samir Bousseaden, @neu5ron, Tim Shelton
// Date: 2020-04-02
// Level: high
// Description: detects execution of psexec or paexec with renamed service name, this rule helps to filter out the noise if psexec is used for legit purposes or if attacker uses a different psexec client other than sysinternal oneThis table contains information about SMB file activity. To have this table present in Microsoft Sentinel, ensure that the Zeek connector is set up and sending data to Sentinel.
// Tags: attack.lateral-movement, attack.t1021.002
// ================================================================== 

SmbFiles
| where ((name endswith "-stdin" or name endswith "-stdout" or name endswith "-stderr") and (path contains "\\" and path contains "\\IPC$")) and (not(name startswith "PSEXESVC"))