// Title: HackTool - CobaltStrike BOF Injection Pattern
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-04
// Level: high
// Description: Detects a typical pattern of a CobaltStrike BOF which inject into other processesThis table contains information about process creation events in Windows. To query this table in Microsoft Sentinel, ensure that the Windows Security Events data connector is enabled and collecting process creation events.
// Tags: attack.execution, attack.t1106, attack.defense-evasion, attack.t1562.001
// ================================================================== 

ProcessCreationEvents
| where CallTrace matches regex "^C:\\\\Windows\\\\SYSTEM32\\\\ntdll\\.dll\\+[a-z0-9]{4,6}\\|C:\\\\Windows\\\\System32\\\\KERNELBASE\\.dll\\+[a-z0-9]{4,6}\\|UNKNOWN\\([A-Z0-9]{16}\\)$" and (GrantedAccess in~ ("0x1028", "0x1fffff"))