// Title: Adwind RAT / JRAT File Artifact
// Author: Florian Roth (Nextron Systems), Tom Ueltschi, Jonhnathan Ribeiro, oscd.community
// Date: 2017-11-10
// Level: high
// Description: Detects javaw.exe in AppData folder as used by Adwind / JRAT
// Tags: attack.execution, attack.t1059.005, attack.t1059.007
// ================================================================== 

DeviceFileEvents
| where (FolderPath contains "\\AppData\\Roaming\\Oracle\\bin\\java" and FolderPath contains ".exe") or (FolderPath contains "\\Retrive" and FolderPath contains ".vbs")