// Title: Execution From Webserver Root Folder
// Author: Florian Roth (Nextron Systems)
// Date: 2019-01-16
// Level: medium
// Description: Detects a program executing from a web server root folder. Use this rule to hunt for potential interesting activity such as webshell or backdoors
// 
// Tags: attack.persistence, attack.t1505.003, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where (FolderPath contains "\\wwwroot\\" or FolderPath contains "\\wmpub\\" or FolderPath contains "\\htdocs\\") and (not(((FolderPath contains "bin\\" or FolderPath contains "\\Tools\\" or FolderPath contains "\\SMSComponent\\") and InitiatingProcessFolderPath endswith "\\services.exe")))