// Title: Osacompile Execution By Potentially Suspicious Applet/Osascript
// Author: Sohan G (D4rkCiph3r), Red Canary (Idea)
// Date: 2023-04-03
// Level: medium
// Description: Detects potential suspicious applet or osascript executing "osacompile".
// Tags: attack.execution, attack.t1059.002
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "osacompile" and (InitiatingProcessFolderPath endswith "/applet" or InitiatingProcessFolderPath endswith "/osascript")