// Title: ETW Logging Disabled In .NET Processes - Registry
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-06-05
// Level: high
// Description: Potential adversaries stopping ETW providers recording loaded .NET assemblies.The SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. To have this table present, ensure that you have the Microsoft Monitoring Agent (MMA) installed on your Windows machines and properly configured to send security events to Sentinel.
// Tags: attack.defense-evasion, attack.t1112, attack.t1562
// ================================================================== 

SecurityEvent
| where (NewValue == 0 and RegistryKey contains "\\Environment" and (ObjectValueName in~ ("COMPlus_ETWEnabled", "COMPlus_ETWFlags"))) or (NewValue == 0 and RegistryKey endswith "\\SOFTWARE\\Microsoft\\.NETFramework" and ObjectValueName =~ "ETWEnabled")