// Title: Malicious IP Address Sign-In Failure Rate
// Author: Mark Morowczynski '@markmorow', Gloria Lee, '@gleeiamglo'
// Date: 2023-09-07
// Level: high
// Description: Indicates sign-in from a malicious IP address based on high failure rates.The AzureActivity table in Microsoft Sentinel contains logs related to Azure activity, including risk detection events. To ensure this table is populated, make sure to have Azure Monitor logs enabled for the Azure service 'riskdetection'.
// Tags: attack.t1090, attack.command-and-control
// ================================================================== 

AzureActivity
| where riskEventType =~ "maliciousIPAddress"