// Title: Suspicious TCP Tunnel Via PowerShell Script
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-08
// Level: medium
// Description: Detects powershell scripts that creates sockets/listeners which could be indicative of tunneling activityThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.command-and-control, attack.t1090
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "[System.Net.HttpWebRequest]" and ScriptBlockText contains "System.Net.Sockets.TcpListener" and ScriptBlockText contains "AcceptTcpClient"