// Title: File and Directory Discovery - MacOS
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2020-10-19
// Level: informational
// Description: Detects usage of system utilities to discover files and directories
// Tags: attack.discovery, attack.t1083
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine matches regex "(.){200,}" and FolderPath =~ "/usr/bin/file") or FolderPath =~ "/usr/bin/find" or FolderPath =~ "/usr/bin/mdfind" or (ProcessCommandLine contains "-R" and FolderPath =~ "/bin/ls") or FolderPath =~ "/tree"