// Title: Arbitrary File Download Via MSOHTMED.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-19
// Level: medium
// Description: Detects usage of "MSOHTMED" to download arbitrary files
// Tags: attack.defense-evasion, attack.execution, attack.t1218
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "ftp://" or ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://") and (FolderPath endswith "\\MSOHTMED.exe" or ProcessVersionInfoOriginalFileName =~ "MsoHtmEd.exe")