// Title: Execution via WorkFolders.exe
// Author: Maxime Thiebaut (@0xThiebaut)
// Date: 2021-10-21
// Level: high
// Description: Detects using WorkFolders.exe to execute an arbitrary control.exe
// Tags: attack.defense-evasion, attack.t1218
// ================================================================== 

DeviceProcessEvents
| where (FolderPath endswith "\\control.exe" and InitiatingProcessFolderPath endswith "\\WorkFolders.exe") and (not(FolderPath =~ "C:\\Windows\\System32\\control.exe"))