// Title: OpenWith.exe Executes Specified Binary
// Author: Beyu Denis, oscd.community (rule), @harr0ey (idea)
// Date: 2019-10-12
// Level: high
// Description: The OpenWith.exe executes other binary
// Tags: attack.defense-evasion, attack.t1218
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "/c" and FolderPath endswith "\\OpenWith.exe"