// Title: Decode Base64 Encoded Text -MacOs
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2020-10-19
// Level: low
// Description: Detects usage of base64 utility to decode arbitrary base64-encoded text
// Tags: attack.defense-evasion, attack.t1027
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "-d" and FolderPath =~ "/usr/bin/base64"