// Title: Cross Site Scripting Strings
// Author: Saw Win Naung, Nasreddine Bencherchali
// Date: 2021-08-15
// Level: high
// Description: Detects XSS attempts injected via GET requests in access logsThis table contains web server logs. Ensure that the appropriate connectors are set up in Sentinel to collect web server logs and populate this table.
// Tags: attack.initial-access, attack.t1189
// ================================================================== 

WebBrowserStats
| where 'cs-method' =~ "GET" and ("=<script>" or "=%3Cscript%3E" or "=%253Cscript%253E" or "<iframe " or "%3Ciframe " or "<svg " or "%3Csvg " or "document.cookie" or "document.domain" or " onerror=" or " onresize=" or " onload=\"" or "onmouseover=" or "${alert" or "javascript:alert" or "javascript%3Aalert") and (not('sc-status' == 404))