// Title: Use Get-NetTCPConnection - PowerShell Module
// Author: frack113
// Date: 2021-12-10
// Level: low
// Description: Adversaries may attempt to get a listing of network connections to or from the compromised system they are currently accessing or from remote systems by querying for information over the network.This table contains security-related events from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to collect this data.
// Tags: attack.discovery, attack.t1049
// ================================================================== 

SecurityEvent
| where ContextInfo contains "Get-NetTCPConnection"