// Title: Cisco Clear Logs
// Author: Austin Clark
// Date: 2019-08-12
// Level: high
// Description: Clear command history in network OS which is used for defense evasionThis table contains authentication logs related to Cisco AAA service. Ensure that the necessary connectors or data connectors are set up in Sentinel to collect and ingest logs from Cisco devices with AAA service enabled.
// Tags: attack.defense-evasion, attack.t1070.003
// ================================================================== 

Cisco_AAA_AuthenticationLogs
| where "clear logging" or "clear archive"