// Title: Clear PowerShell History - PowerShell
// Author: Ilyas Ochkov, Jonhnathan Ribeiro, Daniil Yugoslavskiy, oscd.community
// Date: 2022-01-25
// Level: medium
// Description: Detects keywords that could indicate clearing PowerShell historyThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows Security Events data connector is enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1070.003
// ================================================================== 

SecurityEvent
| where ((ScriptBlockText contains "Set-PSReadlineOption" and ScriptBlockText contains "–HistorySaveStyle" and ScriptBlockText contains "SaveNothing") or (ScriptBlockText contains "Set-PSReadlineOption" and ScriptBlockText contains "-HistorySaveStyle" and ScriptBlockText contains "SaveNothing")) or ((ScriptBlockText contains "del" or ScriptBlockText contains "Remove-Item" or ScriptBlockText contains "rm") and ScriptBlockText contains "(Get-PSReadlineOption).HistorySavePath")