// Title: Disable Powershell Command History
// Author: Ali Alwashali
// Date: 2022-08-21
// Level: high
// Description: Detects scripts or commands that disabled the Powershell command history by removing psreadline moduleThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows Security events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1070.003
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Remove-Module" and ScriptBlockText contains "psreadline"