// Title: Suspicious IO.FileStream
// Author: frack113
// Date: 2022-01-09
// Level: medium
// Description: Open a handle on the drive volume via the \\.\ DOS device path specifier and perform direct access read of the first few bytes of the volume.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. To ensure this table is populated with the necessary logs, ensure that the Windows Security Events connector is enabled and properly configured in Microsoft Sentinel.
// Tags: attack.defense-evasion, attack.t1070.003
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "New-Object" and ScriptBlockText contains "IO.FileStream" and ScriptBlockText contains "\\\\.\\"