// Title: AWS IAM S3Browser User or AccessKey Creation
// Author: daniel.bohannon@permiso.io (@danielhbohannon)
// Date: 2023-05-17
// Level: high
// Description: Detects S3 Browser utility creating IAM User or AccessKey.The equivalent table in Microsoft Sentinel for AWS CloudTrail logs. Ensure that the AWS CloudTrail connector is set up in Sentinel to collect these logs.
// Tags: attack.execution, attack.persistence, attack.t1059.009, attack.t1078.004
// ================================================================== 

CloudTrail
| where (eventName in~ ("CreateUser", "CreateAccessKey")) and eventSource =~ "iam.amazonaws.com" and userAgent contains "S3 Browser"