// Title: AWS IAM S3Browser LoginProfile Creation
// Author: daniel.bohannon@permiso.io (@danielhbohannon)
// Date: 2023-05-17
// Level: high
// Description: Detects S3 Browser utility performing reconnaissance looking for existing IAM Users without a LoginProfile defined then (when found) creating a LoginProfile.The CloudTrail table in Microsoft Sentinel corresponds to AWS CloudTrail logs. To have this table present in Sentinel, you need to ensure that you have configured AWS CloudTrail to send logs to an Azure Storage Account or Event Hub, and then set up a data connector in Sentinel to ingest these logs.
// Tags: attack.execution, attack.persistence, attack.t1059.009, attack.t1078.004
// ================================================================== 

CloudTrail
| where (eventName in~ ("GetLoginProfile", "CreateLoginProfile")) and eventSource =~ "iam.amazonaws.com" and userAgent contains "S3 Browser"