// Title: AWS IAM S3Browser Templated S3 Bucket Policy Creation
// Author: daniel.bohannon@permiso.io (@danielhbohannon)
// Date: 2023-05-17
// Level: high
// Description: Detects S3 browser utility creating Inline IAM policy containing default S3 bucket name placeholder value of "<YOUR-BUCKET-NAME>".The CloudTrail table in Microsoft Sentinel corresponds to AWS CloudTrail logs. To have this table present in Sentinel, make sure to have the AWS CloudTrail connector configured and collecting logs from your AWS environment.
// Tags: attack.execution, attack.t1059.009, attack.persistence, attack.t1078.004
// ================================================================== 

CloudTrail
| where eventName =~ "PutUserPolicy" and eventSource =~ "iam.amazonaws.com" and ((requestParameters contains "\"arn:aws:s3:::<YOUR-BUCKET-NAME>/" and requestParameters contains "\"") and requestParameters contains "\"s3:GetObject\"" and requestParameters contains "\"Allow\"") and userAgent contains "S3 Browser"