// Title: Azure New CloudShell Created
// Author: Austin Songer
// Date: 2021-09-21
// Level: medium
// Description: Identifies when a new cloudshell is created inside of Azure portal.This table contains Azure activity logs. Ensure that Azure Monitor logs are enabled and the necessary connectors are set up in Microsoft Sentinel to collect Azure activity logs.
// Tags: attack.execution, attack.t1059
// ================================================================== 

AzureActivityLogs
| where operationName =~ "MICROSOFT.PORTAL/CONSOLES/WRITE"