// Title: Azure Application Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-09-03
// Level: medium
// Description: Identifies when a application is deleted in Azure.This table contains Azure activity logs. Ensure that Azure Activity Logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.defense-evasion, attack.impact, attack.t1489
// ================================================================== 

AzureActivityLogs
| where 'properties.message' in~ ("Delete application", "Hard Delete application")