// Title: Suspicious Activity in Shell Commands
// Author: Florian Roth (Nextron Systems)
// Date: 2017-08-21
// Level: high
// Description: Detects suspicious shell commands used in various exploit codes (see references)This table contains Linux audit logs, which can be queried in Microsoft Sentinel. To have this table present, ensure that the Linux machines are onboarded to Sentinel and the appropriate data connectors are set up to collect and ingest Linux audit logs.
// Tags: attack.execution, attack.t1059.004
// ================================================================== 

LinuxAuditLogs
| where "wget * - http* | perl" or "wget * - http* | sh" or "wget * - http* | bash" or "python -m SimpleHTTPServer" or "-m http.server" or "import pty; pty.spawn*" or "socat exec:*" or "socat -O /tmp/*" or "socat tcp-connect*" or "*echo binary >>*" or "*wget *; chmod +x*" or "*wget *; chmod 777 *" or "*cd /tmp || cd /var/run || cd /mnt*" or "*stop;service iptables stop;*" or "*stop;SuSEfirewall2 stop;*" or "chmod 777 2020*" or "*>>/etc/rc.local" or "*base64 -d /tmp/*" or "* | base64 -d *" or "*/chmod u+s *" or "*chmod +s /tmp/*" or "*chmod u+s /tmp/*" or "* /tmp/haxhax*" or "* /tmp/ns_sploit*" or "nc -l -p *" or "cp /bin/ksh *" or "cp /bin/sh *" or "* /tmp/*.b64 *" or "*/tmp/ysocereal.jar*" or "*/tmp/x *" or "*; chmod +x /tmp/*" or "*;chmod +x /tmp/*"