// Title: Windows LAPS Credential Dump From Entra ID
// Author: andrewdanis
// Date: 2024-06-26
// Level: high
// Description: Detects when an account dumps the LAPS password from Entra ID.This table contains Azure activity logs, which include audit logs. Ensure that Azure Monitor logs are enabled and the necessary connectors are set up in Microsoft Sentinel to collect Azure activity logs.
// Tags: attack.t1098.005
// ================================================================== 

AzureActivity
| where activityType contains "Recover device local administrator password" and 'additionalDetails.additionalInfo' contains "Successfully recovered local credential by device id" and category =~ "Device"