// Title: Renamed VsCode Code Tunnel Execution - File Indicator
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-25
// Level: high
// Description: Detects the creation of a file with the name "code_tunnel.json" which indicate execution and usage of VsCode tunneling utility by an "Image" or "Process" other than VsCode.
// 
// Tags: attack.command-and-control
// ================================================================== 

DeviceFileEvents
| where FolderPath endswith "\\code_tunnel.json" and (not((InitiatingProcessFolderPath endswith "\\code-tunnel.exe" or InitiatingProcessFolderPath endswith "\\code.exe")))