// Title: Application AppID Uri Configuration Changes
// Author: Mark Morowczynski '@markmorow', Bailey Bercik '@baileybercik'
// Date: 2022-06-02
// Level: high
// Description: Detects when a configuration change is made to an applications AppID URI.This table contains Azure activity logs, which includes audit logs. Ensure that Azure Diagnostics logs are enabled for the Azure service in question to populate this table.
// Tags: attack.persistence, attack.credential-access, attack.privilege-escalation, attack.t1552, attack.t1078.004
// ================================================================== 

AzureActivity
| where 'properties.message' in~ ("Update Application", "Update Service principal")