// Title: History File Deletion
// Author: Florian Roth (Nextron Systems)
// Date: 2022-06-20
// Level: high
// Description: Detects events in which a history file gets deleted, e.g. the ~/bash_history to remove traces of malicious activity
// Tags: attack.impact, attack.t1565.001
// ================================================================== 

DeviceProcessEvents
| where (FolderPath endswith "/rm" or FolderPath endswith "/unlink" or FolderPath endswith "/shred") and ((ProcessCommandLine contains "/.bash_history" or ProcessCommandLine contains "/.zsh_history") or (ProcessCommandLine endswith "_history" or ProcessCommandLine endswith ".history" or ProcessCommandLine endswith "zhistory"))