// Title: Curl.EXE Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-07-05
// Level: low
// Description: Detects a curl process start on Windows, which could indicates a file download from a remote location or a simple web request to a remote server
// Tags: attack.command-and-control, attack.t1105, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "\\curl.exe" or ProcessVersionInfoProductName =~ "The curl executable"