// Title: Potential Okta Password in AlternateID Field
// Author: kelnage
// Date: 2023-04-03
// Level: high
// Description: Detects when a user has potentially entered their password into the
// username field, which will cause the password to be retained in log files.
// This table contains Okta sign-in logs. To have this table present in Microsoft Sentinel, you need to ensure that the Okta connector is set up and configured to send sign-in logs to Sentinel.
// Tags: attack.credential-access, attack.t1552
// ================================================================== 

OktaSignInLogs
| where legacyeventtype =~ "core.user_auth.login_failed" and (not('actor.alternateid' matches regex "(^0oa.*|[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,10})"))