// Title: bXOR Operator Usage In PowerShell Command Line - PowerShell Classic
// Author: Teymur Kheirkhabarov, Harish Segar
// Date: 2020-06-29
// Level: low
// Description: Detects powershell execution with that make use of to the bxor (Bitwise XOR).
// Attackers might use as an alternative obfuscation method to Base64 encoded commands.
// Investigate the CommandLine and process tree to determine if the activity is malicious.
// This table contains Windows security event logs. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to collect these logs.
// Tags: attack.execution, attack.t1059.001, detection.threat-hunting
// ================================================================== 

SecurityEvent
| where Data contains "HostName=ConsoleHost" and Data contains " -bxor "