// Title: Application URI Configuration Changes
// Author: Mark Morowczynski '@markmorow', Bailey Bercik '@baileybercik'
// Date: 2022-06-02
// Level: high
// Description: Detects when a configuration change is made to an applications URI.
// URIs for domain names that no longer exist (dangling URIs), not using HTTPS, wildcards at the end of the domain, URIs that are no unique to that app, or URIs that point to domains you do not control should be investigated.
// This table contains Azure audit logs. Ensure that Azure Monitor logs are enabled and the necessary connectors are set up to collect Azure audit logs in Microsoft Sentinel.
// Tags: attack.t1528, attack.t1078.004, attack.persistence, attack.credential-access, attack.privilege-escalation
// ================================================================== 

AzureActivity
| where 'properties.message' =~ "Update Application Sucess- Property Name AppAddress"