// Title: KrbRelayUp Service Installation
// Author: Sittikorn S, Tim Shelton
// Date: 2022-05-11
// Level: high
// Description: Detects service creation from KrbRelayUp tool used for privilege escalation in Windows domain environments where LDAP signing is not enforced (the default settings)The SecurityEvent table in Microsoft Sentinel contains Windows security event logs. To ensure this table is populated, make sure you have the necessary data connectors set up in Sentinel to collect Windows security event logs.
// Tags: attack.privilege-escalation, attack.t1543
// ================================================================== 

SecurityEvent
| where ServiceName =~ "KrbSCM"