// Title: Copy Passwd Or Shadow From TMP Path
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-01-31
// Level: high
// Description: Detects when the file "passwd" or "shadow" is copied from tmp path
// Tags: attack.credential-access, attack.t1552.001
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "passwd" or ProcessCommandLine contains "shadow") and FolderPath endswith "/cp" and ProcessCommandLine contains "/tmp/"