// Title: Extracting Information with PowerShell
// Author: frack113
// Date: 2021-12-19
// Level: medium
// Description: Adversaries may search local file systems and remote file shares for files containing insecurely stored credentials.
// These can be files created by users to store their own credentials, shared credential stores for a group of individuals,
// configuration files containing passwords for a system or service, or source code/binary files containing embedded passwords.
// This table contains Windows security event logs, including script block logging events. Ensure that the Windows Security Events connector is enabled in Microsoft Sentinel to collect these logs.
// Tags: attack.credential-access, attack.t1552.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "ls" and ScriptBlockText contains " -R" and ScriptBlockText contains "select-string " and ScriptBlockText contains "-Pattern "