// Title: NTLMv1 Logon Between Client and Server
// Author: Tim Shelton, Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-04-26
// Level: medium
// Description: Detects the reporting of NTLMv1 being used between a client and server. NTLMv1 is insecure as the underlying encryption algorithms can be brute-forced by modern hardware.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs. To query this table, ensure that you have the necessary connectors set up in Sentinel to collect Windows security event logs.
// Tags: attack.defense-evasion, attack.lateral-movement, attack.t1550.002
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "LsaSrv"