// Title: Suspicious Windows ANONYMOUS LOGON Local Account Created
// Author: James Pemberton / @4A616D6573
// Date: 2019-10-31
// Level: high
// Description: Detects the creation of suspicious accounts similar to ANONYMOUS LOGON, such as using additional spaces. Created as an covering detection for exclusion of Logon Type 3 from ANONYMOUS LOGON accounts.The SecurityEvent table in Microsoft Sentinel contains security-related logs from Windows machines. To have this table present, ensure that you have the necessary data connectors set up in Sentinel to collect security logs from Windows machines.
// Tags: attack.persistence, attack.t1136.001, attack.t1136.002
// ================================================================== 

SecurityEvent
| where SamAccountName contains "ANONYMOUS" and SamAccountName contains "LOGON"