// Title: Backup Catalog Deleted
// Author: Florian Roth (Nextron Systems), Tom U. @c_APT_ure (collection)
// Date: 2017-05-12
// Level: medium
// Description: Detects backup catalog deletionsThe WindowsEvent table in Microsoft Sentinel contains logs related to Windows events, which would include application logs. Ensure that the necessary data connectors are set up in Sentinel to collect Windows event logs.
// Tags: attack.defense-evasion, attack.t1070.004
// ================================================================== 

WindowsEvent
| where Provider_Name =~ "Microsoft-Windows-Backup"