// Title: MsiExec Web Install
// Author: Florian Roth (Nextron Systems)
// Date: 2018-02-09
// Level: medium
// Description: Detects suspicious msiexec process starts with web addresses as parameter
// Tags: attack.defense-evasion, attack.t1218.007, attack.command-and-control, attack.t1105
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains " msiexec" and ProcessCommandLine contains "://"