// Title: OMIGOD SCX RunAsProvider ExecuteScript
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research), MSTIC
// Date: 2021-10-15
// Level: high
// Description: Rule to detect the use of the SCX RunAsProvider ExecuteScript to execute any UNIX/Linux script using the /bin/sh shell.
// Script being executed gets created as a temp file in /tmp folder with a scx* prefix.
// Then it is invoked from the following directory /etc/opt/microsoft/scx/conf/tmpdir/.
// The file in that directory has the same prefix scx*. SCXcore, started as the Microsoft Operations Manager UNIX/Linux Agent, is now used in a host of products including
// Microsoft Operations Manager, Microsoft Azure, and Microsoft Operations Management Suite.
// This table contains information about process creation events on Linux systems. To have this table present in Microsoft Sentinel, ensure that you have the necessary data connectors or agents installed on your Linux systems to collect process creation logs.
// Tags: attack.privilege-escalation, attack.initial-access, attack.execution, attack.t1068, attack.t1190, attack.t1203
// ================================================================== 

LinuxProcessCreation
| where ProcessCommandLine contains "/etc/opt/microsoft/scx/conf/tmpdir/scx" and CurrentDirectory =~ "/var/opt/microsoft/scx/tmp" and LogonId == 0 and AccountName =~ "root"