// Title: OMIGOD HTTP No Authentication RCE
// Author: Nate Guagenti (neu5ron)
// Date: 2021-09-20
// Level: high
// Description: Detects the exploitation of OMIGOD (CVE-2021-38647) which allows remote execute (RCE) commands as root with just a single unauthenticated HTTP request.
// Verify, successful, exploitation by viewing the HTTP client (request) body to see what was passed to the server (using PCAP).
// Within the client body is where the code execution would occur. Additionally, check the endpoint logs to see if suspicious commands or activity occurred within the timeframe of this HTTP request.
// This table may not exist by default in Microsoft Sentinel. To have this table present, you need to ensure that you have Zeek logs ingested into Sentinel and properly parsed. You may need to create custom parsers or mappings to map the fields from the Zeek logs to the columns in this table.
// Tags: attack.privilege-escalation, attack.initial-access, attack.execution, attack.lateral-movement, attack.t1068, attack.t1190, attack.t1203, attack.t1021.006, attack.t1210
// ================================================================== 

Zeek_HTTP_Header_Names
| where (method =~ "POST" and status_code == 200 and uri =~ "/wsman") and (not(client_header_names contains "AUTHORIZATION")) and (not(request_body_len == 0))