// Title: Potential GobRAT File Discovery Via Grep
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-06-02
// Level: high
// Description: Detects the use of grep to discover specific files created by the GobRAT malware
// Tags: attack.discovery, attack.t1082
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "apached" or ProcessCommandLine contains "frpc" or ProcessCommandLine contains "sshd.sh" or ProcessCommandLine contains "zone.arm") and FolderPath endswith "/grep"