// Title: System Information Discovery Using sw_vers
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-12-20
// Level: medium
// Description: Detects the use of "sw_vers" for system information discovery
// Tags: attack.discovery, attack.t1082
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "/sw_vers" and (ProcessCommandLine contains "-buildVersion" or ProcessCommandLine contains "-productName" or ProcessCommandLine contains "-productVersion")