// Title: Potential Persistence Via GlobalFlags
// Author: Karneades, Jonhnathan Ribeiro, Florian Roth
// Date: 2018-04-11
// Level: high
// Description: Detects registry persistence technique using the GlobalFlags and SilentProcessExit keys
// Tags: attack.privilege-escalation, attack.persistence, attack.defense-evasion, attack.t1546.012, car.2013-01-002
// ================================================================== 

DeviceRegistryEvents
| where (RegistryKey endswith "\\Microsoft\\Windows NT\\CurrentVersion*" and RegistryKey endswith "\\Image File Execution Options*" and RegistryKey contains "\\GlobalFlag") or ((RegistryKey contains "\\ReportingMode" or RegistryKey contains "\\MonitorProcess") and (RegistryKey endswith "\\Microsoft\\Windows NT\\CurrentVersion*" and RegistryKey endswith "\\SilentProcessExit*"))