// Title: Systemd Service Creation
// Author: Pawel Mazur
// Date: 2022-02-03
// Level: medium
// Description: Detects a creation of systemd services which could be used by adversaries to execute malicious code.The equivalent table in Microsoft Sentinel for Linux audit logs. Ensure that the Linux machines are onboarded to Sentinel and the Linux agent is configured to send audit logs to Sentinel.
// Tags: attack.persistence, attack.t1543.002
// ================================================================== 

LinuxAuditLogs
| where (nametype =~ "CREATE" and type =~ "PATH") and ((name startswith "/usr/lib/systemd/system/" or name startswith "/etc/systemd/system/") or name contains "/.config/systemd/user/")