// Title: DNS HybridConnectionManager Service Bus
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2021-04-12
// Level: high
// Description: Detects Azure Hybrid Connection Manager services querying the Azure service bus serviceThe DnsEvents table in Microsoft Sentinel contains DNS query logs. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.persistence, attack.t1554
// ================================================================== 

DnsEvents
| where InitiatingProcessFolderPath contains "HybridConnectionManager" and QueryName contains "servicebus.windows.net"