// Title: HackTool - Koh Default Named Pipe
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-08
// Level: critical
// Description: Detects creation of default named pipes used by the Koh toolThis table contains Sysmon events, including Named Pipe Events (Event ID 17 and Event ID 18). To have this table present in Microsoft Sentinel, you need to have Sysmon installed on your Windows endpoints and configured to log Named Pipe Events.
// Tags: attack.privilege-escalation, attack.credential-access, attack.t1528, attack.t1134.001
// ================================================================== 

SysmonEvent
| where PipeName contains "\\imposecost" or PipeName contains "\\imposingcost"