// Title: OpenCanary - Telnet Login Attempt
// Author: Security Onion Solutions
// Date: 2024-03-08
// Level: high
// Description: Detects instances where a Telnet service on an OpenCanary node has had a login attempt.The OpencanaryLogs table in Microsoft Sentinel contains logs related to the Opencanary application. To have this table present in Sentinel, you need to ensure that Opencanary logs are being collected and sent to Sentinel for ingestion.
// Tags: attack.initial-access, attack.command-and-control, attack.t1133, attack.t1078
// ================================================================== 

OpencanaryLogs
| where logtype == 6001