// Title: WebDAV Temporary Local File Creation
// Author: Micah Babinski
// Date: 2023-08-21
// Level: medium
// Description: Detects the creation of WebDAV temporary files with potentially suspicious extensions
// Tags: attack.initial-access, attack.t1584, attack.t1566, detection.threat-hunting
// ================================================================== 

DeviceFileEvents
| where FolderPath contains "\\AppData\\Local\\Temp\\TfsStore\\Tfs_DAV\\" and (FolderPath endswith ".7z" or FolderPath endswith ".bat" or FolderPath endswith ".dat" or FolderPath endswith ".ico" or FolderPath endswith ".js" or FolderPath endswith ".lnk" or FolderPath endswith ".ps1" or FolderPath endswith ".rar" or FolderPath endswith ".vbe" or FolderPath endswith ".vbs" or FolderPath endswith ".zip")