// Title: Microsoft Word Add-In Loaded
// Author: Steffen Rogge (dr0pd34d)
// Date: 2024-07-10
// Level: low
// Description: Detects Microsoft Word loading an Add-In (.wll) file which can be used by threat actors for initial access or persistence.
// 
// Tags: attack.execution, attack.t1204.002, detection.threat-hunting
// ================================================================== 

DeviceImageLoadEvents
| where FolderPath endswith ".wll" and InitiatingProcessFolderPath endswith "\\winword.exe"