// Title: Certificate Request Export to Exchange Webserver
// Author: Max Altgelt (Nextron Systems)
// Date: 2021-08-23
// Level: critical
// Description: Detects a write of an Exchange CSR to an untypical directory or with aspx name suffix which can be used to place a webshellThe OfficeActivity table in Microsoft Sentinel contains logs related to Microsoft Exchange management activities on Windows servers. To have this table present, ensure that the Microsoft 365 Defender connector is enabled and configured to collect logs from the Microsoft Exchange service.
// Tags: attack.persistence, attack.t1505.003
// ================================================================== 

OfficeActivity
| where ("New-ExchangeCertificate" and " -GenerateRequest" and " -BinaryEncoded" and " -RequestFile") and ("\\\\localhost\\C$" or "\\\\127.0.0.1\\C$" or "C:\\inetpub" or ".aspx")