// Title: Exchange Set OabVirtualDirectory ExternalUrl Property
// Author: Jose Rodriguez @Cyb3rPandaH
// Date: 2021-03-15
// Level: high
// Description: Rule to detect an adversary setting OabVirtualDirectory External URL property to a script in Exchange Management logThis table contains logs related to Microsoft Exchange management activities. To have this table present in Microsoft Sentinel, ensure that you have the Microsoft 365 Defender data connector enabled and configured to collect logs from the Exchange Online service.
// Tags: attack.persistence, attack.t1505.003
// ================================================================== 

ExchangeAdmin
| where "Set-OabVirtualDirectory" and "ExternalUrl" and "Page_Load" and "script"