// Title: Mailbox Export to Exchange Webserver
// Author: Florian Roth (Nextron Systems), Rich Warren, Christian Burkard (Nextron Systems)
// Date: 2021-08-09
// Level: critical
// Description: Detects a successful export of an Exchange mailbox to untypical directory or with aspx name suffix which can be used to place a webshell or the needed role assignment for itThe OfficeActivity table in Microsoft Sentinel contains logs related to Microsoft Exchange management activities on Windows servers. To ensure this table is populated, make sure to have the necessary connectors or data sources configured in Sentinel to collect logs from Microsoft Exchange servers and Windows servers.
// Tags: attack.persistence, attack.t1505.003
// ================================================================== 

OfficeActivity
| where (("New-MailboxExportRequest" and " -Mailbox ") and ("-FilePath \"\\\\" or ".aspx")) or ("New-ManagementRoleAssignment" and " -Role \"Mailbox Import Export\"" and " -User ")