// Title: Suspicious Windows Strings In URI
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-06
// Level: high
// Description: Detects suspicious Windows strings in URI which could indicate possible exfiltration or webshell communicationThe WebBrowserStats table in Microsoft Sentinel contains web server logs. To have this table present, ensure that you have the necessary connectors or data sources configured to collect web server logs in Sentinel.
// Tags: attack.persistence, attack.exfiltration, attack.t1505.003
// ================================================================== 

WebBrowserStats
| where ''cs-uri-query'' contains "=C:/Users" or ''cs-uri-query'' contains "=C:/Program%20Files" or ''cs-uri-query'' contains "=C:/Windows" or ''cs-uri-query'' contains "=C%3A%5CUsers" or ''cs-uri-query'' contains "=C%3A%5CProgram%20Files" or ''cs-uri-query'' contains "=C%3A%5CWindows"