// Title: Azure Device No Longer Managed or Compliant
// Author: Austin Songer @austinsonger
// Date: 2021-09-03
// Level: medium
// Description: Identifies when a device in azure is no longer managed or compliantThis table contains Azure activity logs. Ensure that Azure Activity Logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.impact
// ================================================================== 

AzureActivityLogs
| where 'properties.message' in~ ("Device no longer compliant", "Device no longer managed")