// Title: Azure Kubernetes Secret or Config Object Access
// Author: Austin Songer @austinsonger
// Date: 2021-08-07
// Level: medium
// Description: Identifies when a Kubernetes account access a sensitive objects such as configmaps or secrets.This table contains Azure Activity Logs data. Ensure that Azure Activity Logs are being collected and sent to Microsoft Sentinel for this table to be available.
// Tags: attack.impact
// ================================================================== 

AzureActivityLogs
| where operationName in~ ("MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/CONFIGMAPS/WRITE", "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/CONFIGMAPS/DELETE", "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/SECRETS/WRITE", "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/SECRETS/DELETE")