// Title: Azure Kubernetes Network Policy Change
// Author: Austin Songer @austinsonger
// Date: 2021-08-07
// Level: medium
// Description: Identifies when a Azure Kubernetes network policy is modified or deleted.This table contains Azure activity logs. Ensure that the Azure Activity Logs connector is enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.impact, attack.credential-access
// ================================================================== 

AzureActivityLogs
| where operationName in~ ("MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/NETWORKING.K8S.IO/NETWORKPOLICIES/WRITE", "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/NETWORKING.K8S.IO/NETWORKPOLICIES/DELETE", "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/EXTENSIONS/NETWORKPOLICIES/WRITE", "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/EXTENSIONS/NETWORKPOLICIES/DELETE")