// Title: Azure Container Registry Created or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-08-07
// Level: low
// Description: Detects when a Container Registry is created or deleted.This table contains Azure Activity Logs data. Ensure that Azure Activity Logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.impact
// ================================================================== 

AzureActivityLogs
| where operationName in~ ("MICROSOFT.CONTAINERREGISTRY/REGISTRIES/WRITE", "MICROSOFT.CONTAINERREGISTRY/REGISTRIES/DELETE")