// Title: Azure Kubernetes Cluster Created or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-08-07
// Level: low
// Description: Detects when a Azure Kubernetes Cluster is created or deleted.This table contains Azure Activity Logs data. To have this table present in Microsoft Sentinel, ensure that Azure Activity Logs are being collected and sent to Azure Monitor Logs (Log Analytics Workspace) for ingestion.
// Tags: attack.impact
// ================================================================== 

AzureActivityLogs
| where operationName in~ ("MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/WRITE", "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/DELETE")