// Title: Azure Kubernetes RoleBinding/ClusterRoleBinding Modified and Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-08-07
// Level: medium
// Description: Detects the creation or patching of potential malicious RoleBinding/ClusterRoleBinding.This table contains Azure Activity Logs data. Ensure that Azure Activity Logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.impact, attack.credential-access
// ================================================================== 

AzureActivityLogs
| where operationName in~ ("MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/RBAC.AUTHORIZATION.K8S.IO/CLUSTERROLEBINDINGS/WRITE", "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/RBAC.AUTHORIZATION.K8S.IO/CLUSTERROLEBINDINGS/DELETE", "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/RBAC.AUTHORIZATION.K8S.IO/ROLEBINDINGS/WRITE", "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/RBAC.AUTHORIZATION.K8S.IO/ROLEBINDINGS/DELETE")