// Title: Azure Application Credential Modified
// Author: Austin Songer @austinsonger
// Date: 2021-09-02
// Level: medium
// Description: Identifies when a application credential is modified.This table contains Azure activity logs data. Make sure to have the Azure Activity Logs connector enabled in Microsoft Sentinel to access this table.
// Tags: attack.impact
// ================================================================== 

AzureActivityLogs
| where 'properties.message' =~ "Update application - Certificates and secrets management"