// Title: Google Cloud DNS Zone Modified or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-08-15
// Level: medium
// Description: Identifies when a DNS Zone is modified or deleted in Google Cloud.This table contains GCP audit logs. Ensure that the GCP connector is set up in Microsoft Sentinel to collect logs from the 'gcp.audit' service within the 'gcp' product.
// Tags: attack.impact
// ================================================================== 

GCPAuditLogs
| where 'gcp.audit.method_name' in~ ("Dns.ManagedZones.Delete", "Dns.ManagedZones.Update", "Dns.ManagedZones.Patch")