// Title: Google Cloud Service Account Modified
// Author: Austin Songer @austinsonger
// Date: 2021-08-14
// Level: medium
// Description: Identifies when a service account is modified in Google Cloud.This table contains GCP audit logs. Ensure that the GCP connector is installed in Microsoft Sentinel to collect logs from GCP service with 'gcp.audit' category.
// Tags: attack.impact
// ================================================================== 

GCPAuditLogs
| where ''gcp.audit.method_name'' endswith ".serviceAccounts.patch" or ''gcp.audit.method_name'' endswith ".serviceAccounts.create" or ''gcp.audit.method_name'' endswith ".serviceAccounts.update" or ''gcp.audit.method_name'' endswith ".serviceAccounts.enable" or ''gcp.audit.method_name'' endswith ".serviceAccounts.undelete"