// Title: Okta Unauthorized Access to App
// Author: Austin Songer @austinsonger
// Date: 2021-09-12
// Level: medium
// Description: Detects when unauthorized access to app occurs.This table contains Okta sign-in logs. To have this table present in Microsoft Sentinel, you need to ensure that Okta logs are being forwarded to Sentinel and that the Okta connector is properly configured.
// Tags: attack.impact
// ================================================================== 

OktaSignInLogs
| where displaymessage =~ "User attempted unauthorized access to app"