// Title: Okta Network Zone Deactivated or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-09-12
// Level: medium
// Description: Detects when an Network Zone is Deactivated or Deleted.This table contains Okta sign-in logs. Ensure that the Okta connector is installed in Microsoft Sentinel to have access to this table.
// Tags: attack.impact
// ================================================================== 

OktaSignInLogs
| where eventtype in~ ("zone.deactivate", "zone.delete")