// Title: Okta Policy Modified or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-09-12
// Level: low
// Description: Detects when an Okta policy is modified or deleted.This table contains Okta sign-in logs. To have this table present in Microsoft Sentinel, you need to ensure that Okta logs are being forwarded to Sentinel and that the Okta connector is properly configured.
// Tags: attack.impact
// ================================================================== 

OktaSignInLogs
| where eventtype in~ ("policy.lifecycle.update", "policy.lifecycle.delete")