// Title: Okta Application Sign-On Policy Modified or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-09-12
// Level: medium
// Description: Detects when an application Sign-on Policy is modified or deleted.This table contains Okta sign-in logs. To have this table present in Microsoft Sentinel, you need to ensure that Okta logs are being ingested into Sentinel and the Okta connector is properly configured.
// Tags: attack.impact
// ================================================================== 

OktaSignInLogs
| where eventtype in~ ("application.policy.sign_on.update", "application.policy.sign_on.rule.delete")