// Title: OneLogin User Account Locked
// Author: Austin Songer @austinsonger
// Date: 2021-10-12
// Level: low
// Description: Detects when an user account is locked or suspended.This table contains events from the Onelogin service. Make sure to have the Onelogin connector installed in Microsoft Sentinel to have access to this table.
// Tags: attack.impact
// ================================================================== 

OneloginEvents
| where event_type_id in~ ("532", "553", "551")