// Title: Suspicious MacOS Firmware Activity
// Author: Austin Songer @austinsonger
// Date: 2021-09-30
// Level: medium
// Description: Detects when a user manipulates with Firmward Password on MacOS. NOTE - this command has been disabled on silicon-based apple computers.
// Tags: attack.impact
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "setpasswd" or ProcessCommandLine contains "full" or ProcessCommandLine contains "delete" or ProcessCommandLine contains "check") and FolderPath =~ "/usr/sbin/firmwarepasswd"