// Title: Suspicious OAuth App File Download Activities
// Author: Austin Songer @austinsonger
// Date: 2021-08-23
// Level: medium
// Description: Detects when a Microsoft Cloud App Security reported when an app downloads multiple files from Microsoft SharePoint or Microsoft OneDrive in a manner that is unusual for the user.The ThreatIntelligenceIndicator table in Microsoft Sentinel contains threat intelligence indicators that can be used for threat management. Ensure that the Microsoft 365 Defender connector is enabled in Sentinel to have this table available.
// Tags: attack.exfiltration
// ================================================================== 

ThreatIntelligenceIndicator
| where eventName =~ "Suspicious OAuth app file download activities" and eventSource =~ "SecurityComplianceCenter" and status =~ "success"