// Title: Github SSH Certificate Configuration Changed
// Author: Romain Gaillard (@romain-gaillard)
// Date: 2024-07-29
// Level: medium
// Description: Detects when changes are made to the SSH certificate configuration of the organization.This table contains audit logs for the Github service in Microsoft Sentinel. To have this table present, ensure that the Github connector is installed in Sentinel and properly configured to ingest audit logs.
// Tags: attack.persistence, attack.privilege-escalation, attack.t1078.004
// ================================================================== 

GithubAuditLogs
| where action in~ ("ssh_certificate_authority.create", "ssh_certificate_requirement.disable")