// Title: Guest User Invited By Non Approved Inviters
// Author: Mark Morowczynski '@markmorow', Yochana Henderson, '@Yochana-H'
// Date: 2022-08-10
// Level: medium
// Description: Detects when a user that doesn't have permissions to invite a guest user attempts to invite one.The AzureActivity table in Microsoft Sentinel contains Azure audit logs. Make sure to have the Azure Monitor solution installed in Sentinel to access this table.
// Tags: attack.persistence, attack.defense-evasion, attack.t1078.004
// ================================================================== 

AzureActivity
| where Status =~ "failure" and 'properties.message' =~ "Invite external user"