// Title: Password Reset By User Account
// Author: YochanaHenderson, '@Yochana-H'
// Date: 2022-08-03
// Level: medium
// Description: Detect when a user has reset their password in Azure ADThis table contains Azure activity logs, including audit logs. Ensure that Azure Diagnostics logs are enabled and streaming to Log Analytics workspace in Sentinel.
// Tags: attack.persistence, attack.credential-access, attack.t1078.004
// ================================================================== 

AzureActivity
| where (Category =~ "UserManagement" and Initiatedby =~ "UPN" and Status =~ "Success") and (ActivityType contains "Password reset" and Target contains "UPN")