// Title: VsCode Code Tunnel Execution File Indicator
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-25
// Level: medium
// Description: Detects the creation of a file with the name "code_tunnel.json" which indicate execution and usage of VsCode tunneling utility. Attackers can abuse this functionality to establish a C2 channel
// 
// Tags: attack.command-and-control, detection.threat-hunting
// ================================================================== 

DeviceFileEvents
| where FolderPath endswith "\\code_tunnel.json"