// Title: CA Policy Updated by Non Approved Actor
// Author: Corissa Koopmans, '@corissalea'
// Date: 2022-07-19
// Level: medium
// Description: Monitor and alert on conditional access changes. Is Initiated by (actor) approved to make changes? Review Modified Properties and compare "old" vs "new" value.This table contains Azure activity logs, including audit logs. Make sure to have the Azure Monitor solution enabled in Microsoft Sentinel to access this table.
// Tags: attack.defense-evasion, attack.persistence, attack.t1548, attack.t1556
// ================================================================== 

AzureActivity
| where 'properties.message' =~ "Update conditional access policy"