// Description: This query was originally published in the threat analytics report, Sysrv botnet evolution.
// Sysrv is a Go-based botnet that targets both Windows and Linux servers, and steals resources to mine cryptocurrency.
// The following query finds instances of the Java process being used to execute cmd.exe, and download and execute a PowerShell script.
// Required Connectors: MicrosoftThreatProtection (Types: DeviceProcessEvents)

DeviceProcessEvents                         
| where InitiatingProcessFileName == 'java.exe' and FileName == 'cmd.exe' 
and ProcessCommandLine has_all('powershell iex','DownloadString')