// Description: This query was originally published in the threat analytics report, Sysrv botnet evolution.
// Sysrv is a Go-based botnet that targets both Windows and Linux servers, and steals resources to mine cryptocurrency.
// The following query finds instances where the attacker commanded the Kinsing miner file to be downloaded on Linux devices.
// Required Connectors: MicrosoftThreatProtection (Types: DeviceProcessEvents)

DeviceProcessEvents
| where ProcessCommandLine has_all('curl', '-o /etc/kinsing')