// Title: Triple Cross eBPF Rootkit Install Commands
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-05
// Level: high
// Description: Detects default install commands of the Triple Cross eBPF rootkit based on the "deployer.sh" script
// Tags: attack.defense-evasion, attack.t1014
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains " qdisc " or ProcessCommandLine contains " filter ") and (ProcessCommandLine contains " tc " and ProcessCommandLine contains " enp0s3 ") and FolderPath endswith "/sudo"