// Title: Group Policy Abuse for Privilege Addition
// Author: Elastic, Josh Nickels, Marius Rothenbücher
// Date: 2024-09-04
// Level: medium
// Description: Detects the first occurrence of a modification to Group Policy Object Attributes to add privileges to user accounts or use them to add users as local admins.
// The SecurityEvent table in Microsoft Sentinel contains security-related events, including directory service changes. Make sure to enable the necessary connectors and data sources in Sentinel to collect Windows security events.
// Tags: attack.privilege-escalation, attack.t1484.001
// ================================================================== 

SecurityEvent
| where AttributeLDAPDisplayName =~ "gPCMachineExtensionNames" and (AttributeValue contains "827D319E-6EAC-11D2-A4EA-00C04F79F83A" or AttributeValue contains "803E14A0-B4FB-11D0-A0D0-00A0C90F574B")