// Title: Startup/Logon Script Added to Group Policy Object
// Author: Elastic, Josh Nickels, Marius Rothenbücher
// Date: 2024-09-06
// Level: medium
// Description: Detects the modification of Group Policy Objects (GPO) to add a startup/logon script to users or computer objects.
// The SecurityEvent table in Microsoft Sentinel contains security-related events and logs, including detailed file share access events. Make sure to have the necessary data connectors and log sources configured in Sentinel to populate this table with relevant data.
// Tags: attack.privilege-escalation, attack.t1484.001, attack.t1547
// ================================================================== 

SecurityEvent
| where (((AttributeLDAPDisplayName in~ ("gPCMachineExtensionNames", "gPCUserExtensionNames")) and AttributeValue contains "42B5FAAE-6536-11D2-AE5A-0000F87571E3") and (AttributeValue contains "40B6664F-4972-11D1-A7CA-0000F87571E3" or AttributeValue contains "40B66650-4972-11D1-A7CA-0000F87571E3")) or (AccessList contains "%%4417" and (RelativeTargetName endswith "\\scripts.ini" or RelativeTargetName endswith "\\psscripts.ini") and ShareName endswith "\\SYSVOL")