// Title: Scheduled Task Executed From A Suspicious Location
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-05
// Level: medium
// Description: Detects the execution of Scheduled Tasks where the Program being run is located in a suspicious location or it's an unusale program to be run from a Scheduled TaskThe equivalent table in KQL for Microsoft Sentinel is the Event table. This table contains all the events collected by Sentinel, including events from the Microsoft-Windows-TaskScheduler/Operational log source. To ensure this table is present, make sure to have the necessary data connectors or log sources configured in Sentinel to collect events from the Windows Task Scheduler service.
// Tags: attack.persistence, attack.t1053.005
// ================================================================== 

Event
| where Path contains "C:\\Windows\\Temp\\" or Path contains "\\AppData\\Local\\Temp\\" or Path contains "\\Desktop\\" or Path contains "\\Downloads\\" or Path contains "\\Users\\Public\\" or Path contains "C:\\Temp\\"