// Title: AWS Root Credentials
// Author: vitaliy0x1
// Date: 2020-01-21
// Level: medium
// Description: Detects AWS root account usageThe CloudTrail table in Microsoft Sentinel contains logs related to AWS CloudTrail service. To have this table present in Sentinel, you need to ensure that the AWS CloudTrail connector is properly configured and sending logs to Sentinel.
// Tags: attack.privilege-escalation, attack.t1078.004
// ================================================================== 

CloudTrail
| where 'userIdentity.type' =~ "Root" and (not(eventType =~ "AwsServiceEvent"))