// Title: PIM Approvals And Deny Elevation
// Author: Mark Morowczynski '@markmorow', Yochana Henderson, '@Yochana-H'
// Date: 2022-08-09
// Level: high
// Description: Detects when a PIM elevation is approved or denied. Outside of normal operations should be investigated.This table contains Azure audit logs. Ensure that Azure Monitor logs are enabled and the necessary connectors are set up in Microsoft Sentinel to collect Azure audit logs.
// Tags: attack.privilege-escalation, attack.t1078.004
// ================================================================== 

AzureActivity
| where 'properties.message' =~ "Request Approved/Denied"