// Title: User State Changed From Guest To Member
// Author: MikeDuddington, '@dudders1'
// Date: 2022-06-30
// Level: medium
// Description: Detects the change of user type from "Guest" to "Member" for potential elevation of privilege.This table contains Azure activity logs, which includes audit logs. Ensure that Azure Diagnostics logs are enabled for the Azure service in question to populate this table.
// Tags: attack.privilege-escalation, attack.initial-access, attack.t1078.004
// ================================================================== 

AzureActivity
| where Category =~ "UserManagement" and OperationName =~ "Update user" and 'properties.message' =~ "\"displayName\":\"UserType\",\"oldValue\":\"[\\\"Guest\\\"]\",\"newValue\":\"[\\\"Member\\\"]\""