// Title: Ufw Force Stop Using Ufw-Init
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-01-18
// Level: medium
// Description: Detects attempts to force stop the ufw using ufw-init
// Tags: attack.defense-evasion, attack.t1562.004
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "-ufw-init" and ProcessCommandLine contains "force-stop") or (ProcessCommandLine contains "ufw" and ProcessCommandLine contains "disable")