// Title: PowerShell Deleted Mounted Share
// Author: oscd.community, @redcanary, Zach Stanford @svch0st
// Date: 2020-10-08
// Level: medium
// Description: Detects when when a mounted share is removed. Adversaries may remove share connections that are no longer useful in order to clean up traces of their operationThis table contains security-related events, including PowerShell script execution events. Ensure that the necessary data connectors are set up to collect Windows security event logs in Sentinel.
// Tags: attack.defense-evasion, attack.t1070.005
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Remove-SmbShare" or ScriptBlockText contains "Remove-FileShare"