// Title: Firewall Rule Modified In The Windows Firewall Exception List
// Author: frack113
// Date: 2022-02-19
// Level: low
// Description: Detects when a rule has been modified in the Windows firewall exception listThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Event logs are being collected and ingested into Sentinel to query this table.
// Tags: attack.defense-evasion, attack.t1562.004, detection.threat-hunting
// ================================================================== 

SecurityEvent
| where not(((ApplicationPath contains ":\\Users\\" and ApplicationPath contains "\\AppData\\Local\\BraveSoftware\\Brave-Browser\\Application\\brave.exe") or ApplicationPath endswith "\\AppData\\Local\\Keybase\\keybase.exe" or ApplicationPath endswith "\\AppData\\Local\\Programs\\Messenger\\Messenger.exe" or (ApplicationPath contains ":\\Users\\" and ApplicationPath contains "\\AppData\\Local\\Programs\\Opera\\" and ApplicationPath contains "\\opera.exe") or ApplicationPath endswith "\\AppData\\local\\microsoft\\teams\\current\\teams.exe"))