// Title: Potentially Suspicious Regsvr32 HTTP/FTP Pattern
// Author: Florian Roth (Nextron Systems)
// Date: 2023-05-24
// Level: medium
// Description: Detects regsvr32 execution to download/install/register new DLLs that are hosted on Web or FTP servers.
// Tags: attack.defense-evasion, attack.t1218.010
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains " /i" or ProcessCommandLine contains " -i") and (FolderPath endswith "\\regsvr32.exe" or ProcessVersionInfoOriginalFileName =~ "REGSVR32.EXE") and (ProcessCommandLine contains "ftp" or ProcessCommandLine contains "http")