// Title: Devtoolslauncher.exe Executes Specified Binary
// Author: Beyu Denis, oscd.community (rule), @_felamos (idea)
// Date: 2019-10-12
// Level: high
// Description: The Devtoolslauncher.exe executes other binary
// Tags: attack.defense-evasion, attack.t1218
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "LaunchForDeploy" and FolderPath endswith "\\devtoolslauncher.exe"