// Title: Potential Provisioning Registry Key Abuse For Binary Proxy Execution - REG
// Author: Swachchhanda Shrawan Poudel
// Date: 2023-08-02
// Level: high
// Description: Detects potential abuse of the provisioning registry key for indirect command execution through "Provlaunch.exe".
// Tags: attack.defense-evasion, attack.t1218
// ================================================================== 

DeviceRegistryEvents
| where RegistryKey endswith "\\SOFTWARE\\Microsoft\\Provisioning\\Commands*"