// Title: Uncommon Child Process Of Setres.EXE
// Author: @gott_cyber, Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-11
// Level: high
// Description: Detects uncommon child process of Setres.EXE.
// Setres.EXE is a Windows server only process and tool that can be used to set the screen resolution.
// It can potentially be abused in order to launch any arbitrary file with a name containing the word "choice" from the current execution path.
// 
// Tags: attack.defense-evasion, attack.t1218, attack.t1202
// ================================================================== 

DeviceProcessEvents
| where (FolderPath contains "\\choice" and InitiatingProcessFolderPath endswith "\\setres.exe") and (not((FolderPath endswith "C:\\Windows\\System32\\choice.exe" or FolderPath endswith "C:\\Windows\\SysWOW64\\choice.exe")))