// Title: AWS ECS Task Definition That Queries The Credential Endpoint
// Author: Darin Smith
// Date: 2022-06-07
// Level: medium
// Description: Detects when an Elastic Container Service (ECS) Task Definition includes a command to query the credential endpoint.
// This can indicate a potential adversary adding a backdoor to establish persistence or escalate privileges.
// The CloudTrail table in Microsoft Sentinel contains logs related to AWS CloudTrail service. To have this table present in Sentinel, you need to ensure that the AWS connector is properly configured and collecting CloudTrail logs.
// Tags: attack.persistence, attack.t1525
// ================================================================== 

CloudTrail
| where (eventName in~ ("DescribeTaskDefinition", "RegisterTaskDefinition", "RunTask")) and eventSource =~ "ecs.amazonaws.com" and 'requestParameters.containerDefinitions.command' contains "$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI"