// Title: Azure Kubernetes Service Account Modified or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-08-07
// Level: medium
// Description: Identifies when a service account is modified or deleted.This table contains Azure Activity Logs data. Make sure to have Azure Activity Logs connector enabled in Microsoft Sentinel to populate this table.
// Tags: attack.impact, attack.t1531
// ================================================================== 

AzureActivityLogs
| where operationName in~ ("MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/SERVICEACCOUNTS/WRITE", "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/SERVICEACCOUNTS/DELETE", "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/SERVICEACCOUNTS/IMPERSONATE/ACTION")