// Title: Google Cloud Service Account Disabled or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-08-14
// Level: medium
// Description: Identifies when a service account is disabled or deleted in Google Cloud.This table contains GCP audit logs. To have this table present in Microsoft Sentinel, you need to ensure that GCP audit logs are being ingested into Sentinel. This may require setting up a data connector for GCP logs and configuring the necessary permissions.
// Tags: attack.impact, attack.t1531
// ================================================================== 

GCPAuditLogs
| where ''gcp.audit.method_name'' endswith ".serviceAccounts.disable" or ''gcp.audit.method_name'' endswith ".serviceAccounts.delete"