// Title: Azure Active Directory Hybrid Health AD FS New Server
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research), MSTIC
// Date: 2021-08-26
// Level: medium
// Description: This detection uses azureactivity logs (Administrative category) to identify the creation or update of a server instance in an Azure AD Hybrid health AD FS service.
// A threat actor can create a new AD Health ADFS service and create a fake server instance to spoof AD FS signing logs. There is no need to compromise an on-prem AD FS server.
// This can be done programmatically via HTTP requests to Azure.
// This table contains Azure activity logs data. Ensure that Azure Activity Logs connector is enabled in Microsoft Sentinel to have this table available for querying.
// Tags: attack.defense-evasion, attack.t1578
// ================================================================== 

AzureActivityLogs
| where CategoryValue =~ "Administrative" and OperationNameValue =~ "Microsoft.ADHybridHealthService/services/servicemembers/action" and ResourceId contains "AdFederationService" and ResourceProviderValue =~ "Microsoft.ADHybridHealthService"