// Title: Potential Persistence Via PlistBuddy
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-02-18
// Level: high
// Description: Detects potential persistence activity using LaunchAgents or LaunchDaemons via the PlistBuddy utility
// Tags: attack.persistence, attack.t1543.001, attack.t1543.004
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "LaunchAgents" or ProcessCommandLine contains "LaunchDaemons") and (ProcessCommandLine contains "RunAtLoad" and ProcessCommandLine contains "true") and FolderPath endswith "/PlistBuddy"