// Title: System Network Discovery - macOS
// Author: remotephone, oscd.community
// Date: 2020-10-06
// Level: informational
// Description: Detects enumeration of local network configuration
// Tags: attack.discovery, attack.t1016
// ================================================================== 

DeviceProcessEvents
| where ((FolderPath endswith "/arp" or FolderPath endswith "/ifconfig" or FolderPath endswith "/netstat" or FolderPath endswith "/networksetup" or FolderPath endswith "/socketfilterfw") or ((ProcessCommandLine contains "/Library/Preferences/com.apple.alf" and ProcessCommandLine contains "read") and FolderPath =~ "/usr/bin/defaults")) and (not(InitiatingProcessFolderPath endswith "/wifivelocityd"))