// Title: System Network Discovery - Linux
// Author: Ömer Günal and remotephone, oscd.community
// Date: 2020-10-06
// Level: informational
// Description: Detects enumeration of local network configuration
// Tags: attack.discovery, attack.t1016
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "/etc/resolv.conf" or (FolderPath endswith "/firewall-cmd" or FolderPath endswith "/ufw" or FolderPath endswith "/iptables" or FolderPath endswith "/netstat" or FolderPath endswith "/ss" or FolderPath endswith "/ip" or FolderPath endswith "/ifconfig" or FolderPath endswith "/systemd-resolve" or FolderPath endswith "/route")