// Title: Suspicious PowerShell WindowStyle Option
// Author: frack113, Tim Shelton (fp AWS)
// Date: 2021-10-20
// Level: medium
// Description: Adversaries may use hidden windows to conceal malicious activity from the plain sight of users.
// In some cases, windows that would typically be displayed when an application carries out an operation can be hidden
// This table contains Windows security event logs, including script block logging events. Ensure that the Windows Security Events connector is enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1564.003
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "powershell" and ScriptBlockText contains "WindowStyle" and ScriptBlockText contains "Hidden") and (not((ScriptBlockText contains ":\\Program Files\\Amazon\\WorkSpacesConfig\\Scripts\\" and ScriptBlockText contains "$PSScriptRoot\\Module\\WorkspaceScriptModule\\WorkspaceScriptModule")))