// Title: Okta Password Health Report Query
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2023-10-25
// Level: low
// Description: Detects all activities against the endpoint "/reports/password-health/*" which should only be accessed via OKTA Admin Console UI.
// Use this rule to hunt for potential suspicious requests. Correlate this event with "admin console" login and alert on requests without any corresponding admin console login
// This table contains Okta sign-in logs. To have this table present in Microsoft Sentinel, you need to ensure that Okta logs are being forwarded to Sentinel and that the necessary connectors or data connectors are set up to ingest Okta logs.
// Tags: attack.credential-access, detection.threat-hunting
// ================================================================== 

OktaSignInLogs
| where 'debugContext.debugData.requestUri' contains "/reports/password-health/"