// Title: User Added To Root/Sudoers Group Using Usermod
// Author: TuanLe (GTSC)
// Date: 2022-12-21
// Level: medium
// Description: Detects usage of the "usermod" binary to add users add users to the root or suoders groups
// Tags: attack.privilege-escalation, attack.persistence
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "-aG root" or ProcessCommandLine contains "-aG sudoers") and FolderPath endswith "/usermod"