// Title: Dynamic .NET Compilation Via Csc.EXE - Hunting
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-02
// Level: medium
// Description: Detects execution of "csc.exe" to compile .NET code. Attackers often leverage this to compile code on the fly and use it in other stages.
// Tags: attack.defense-evasion, attack.t1027.004, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "/noconfig /fullpaths @" and FolderPath endswith "\\csc.exe"