// Title: Microsoft Office Trusted Location Updated
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-21
// Level: medium
// Description: Detects changes to the registry keys related to "Trusted Location" of Microsoft Office. Attackers might add additional trusted locations to avoid macro security restrictions.
// Tags: attack.defense-evasion, attack.t1112, detection.threat-hunting
// ================================================================== 

DeviceRegistryEvents
| where (RegistryKey contains "Security\\Trusted Locations\\Location" and RegistryKey endswith "\\Path") and (not(((InitiatingProcessFolderPath contains ":\\Program Files\\Microsoft Office\\" or InitiatingProcessFolderPath contains ":\\Program Files (x86)\\Microsoft Office\\") or (InitiatingProcessFolderPath contains ":\\Program Files\\Common Files\\Microsoft Shared\\ClickToRun\\" and InitiatingProcessFolderPath endswith "\\OfficeClickToRun.exe"))))