// Title: Active Directory Certificate Services Denied Certificate Enrollment Request
// Author: @SerkinValery
// Date: 2024-03-07
// Level: low
// Description: Detects denied requests by Active Directory Certificate Services.
// Example of these requests denial include issues with permissions on the certificate template or invalid signatures.
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events are being collected and ingested into Sentinel to query this table.
// Tags: attack.credential-access, attack.t1553.004
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Microsoft-Windows-CertificationAuthority"