// Title: SysKey Registry Keys Access
// Author: Roberto Rodriguez @Cyb3rWard0g
// Date: 2019-08-12
// Level: high
// Description: Detects handle requests and access operations to specific registry keys to calculate the SysKey
// Tags: attack.discovery, attack.t1012
// ================================================================== 

DeviceRegistryEvents
| where RegistryKey endswith "lsa\\JD" or RegistryKey endswith "lsa\\GBG" or RegistryKey endswith "lsa\\Skew1" or RegistryKey endswith "lsa\\Data"