// Title: Potential Bucket Enumeration on AWS
// Author: Christopher Peacock @securepeacock, SCYTHE @scythe_io
// Date: 2023-01-06
// Level: low
// Description: Looks for potential enumeration of AWS buckets via ListBuckets.The CloudTrail table in Microsoft Sentinel contains logs related to AWS CloudTrail service. To query this table, ensure that you have the AWS CloudTrail connector configured in Sentinel and ingesting logs from the specified logsource.
// Tags: attack.discovery, attack.t1580
// ================================================================== 

CloudTrail
| where (eventName =~ "ListBuckets" and eventSource =~ "s3.amazonaws.com") and (not('userIdentity.type' =~ "AssumedRole"))