// Title: Tor Client/Browser Execution
// Author: frack113
// Date: 2022-02-20
// Level: high
// Description: Detects the use of Tor or Tor-Browser to connect to onion routing networks
// Tags: attack.command-and-control, attack.t1090.003
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "\\tor.exe" or FolderPath endswith "\\Tor Browser\\Browser\\firefox.exe"