// Title: Potential Mftrace.EXE Abuse
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-09
// Level: medium
// Description: Detects child processes of the "Trace log generation tool for Media Foundation Tools" (Mftrace.exe) which can abused to execute arbitrary binaries.
// Tags: attack.defense-evasion, attack.t1127
// ================================================================== 

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\mftrace.exe"