// Title: Use of Remote.exe
// Author: Christopher Peacock @SecurePeacock, SCYTHE @scythe_io
// Date: 2022-06-02
// Level: medium
// Description: Remote.exe is part of WinDbg in the Windows SDK and can be used for AWL bypass and running remote files.
// Tags: attack.defense-evasion, attack.t1127
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "\\remote.exe" or ProcessVersionInfoOriginalFileName =~ "remote.exe"