// Title: Curl Usage on Linux
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-15
// Level: low
// Description: Detects a curl process start on linux, which indicates a file download from a remote location or a simple web request to a remote server
// Tags: attack.command-and-control, attack.t1105
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "/curl"