// Title: Download File To Potentially Suspicious Directory Via Wget
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-06-02
// Level: medium
// Description: Detects the use of wget to download content to a suspicious directory
// Tags: attack.command-and-control, attack.t1105
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "/wget" and (ProcessCommandLine matches regex "\\s-O\\s" or ProcessCommandLine contains "--output-document") and ProcessCommandLine contains "/tmp/"