// Title: File Download And Execution Via IEExec.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-05-16
// Level: high
// Description: Detects execution of the IEExec utility to download and execute files
// Tags: attack.command-and-control, attack.t1105
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://") and (FolderPath endswith "\\IEExec.exe" or ProcessVersionInfoOriginalFileName =~ "IEExec.exe")