// Title: Filter Driver Unloaded Via Fltmc.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-13
// Level: medium
// Description: Detect filter driver unloading activity via fltmc.exe
// Tags: attack.defense-evasion, attack.t1070, attack.t1562, attack.t1562.002
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "unload" and (FolderPath endswith "\\fltMC.exe" or ProcessVersionInfoOriginalFileName =~ "fltMC.exe")) and (not(((ProcessCommandLine endswith "unload rtp_filesystem_filter" and InitiatingProcessFolderPath contains "\\AppData\\Local\\Temp\\" and InitiatingProcessFolderPath endswith "\\endpoint-protection-installer-x64.tmp" and InitiatingProcessFolderPath startswith "C:\\Users\\") or (ProcessCommandLine endswith "unload DFMFilter" and InitiatingProcessFolderPath =~ "C:\\Program Files (x86)\\ManageEngine\\uems_agent\\bin\\dcfaservice64.exe"))))