// Title: JAMF MDM Potential Suspicious Child Process
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-22
// Level: medium
// Description: Detects potential suspicious child processes of "jamf". Could be a sign of potential abuse of Jamf as a C2 server as seen by Typhon MythicAgent.
// Tags: attack.execution
// ================================================================== 

DeviceProcessEvents
| where (FolderPath endswith "/bash" or FolderPath endswith "/sh") and InitiatingProcessFolderPath endswith "/jamf"