// Title: Potentially Suspicious Named Pipe Created Via Mkfifo
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-16
// Level: medium
// Description: Detects the creation of a new named pipe using the "mkfifo" utility in a potentially suspicious location
// Tags: attack.execution
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains " /tmp/" and FolderPath endswith "/mkfifo"