// Title: Github Delete Action Invoked
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2023-01-19
// Level: medium
// Description: Detects delete action in the Github audit logs for codespaces, environment, project and repo.This table contains the audit logs for the Github service. To query this table in Microsoft Sentinel, ensure that the Github connector is installed and properly configured to ingest audit logs.
// Tags: attack.impact, attack.collection, attack.t1213.003
// ================================================================== 

GithubAuditLogs
| where action in~ ("codespaces.delete", "environment.delete", "project.delete", "repo.destroy")