// Title: HackTool - F-Secure C3 Load by Rundll32
// Author: Alfie Champion (ajpc500)
// Date: 2021-06-02
// Level: critical
// Description: F-Secure C3 produces DLLs with a default exported StartNodeRelay function.
// Tags: attack.defense-evasion, attack.t1218.011
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "rundll32.exe" and ProcessCommandLine contains ".dll" and ProcessCommandLine contains "StartNodeRelay"