// Title: Hidden User Creation
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2020-10-10
// Level: medium
// Description: Detects creation of a hidden user account on macOS (UserID < 500) or with IsHidden option
// Tags: attack.defense-evasion, attack.t1564.002
// ================================================================== 

DeviceProcessEvents
| where ((ProcessCommandLine contains "create" and FolderPath endswith "/dscl") and (ProcessCommandLine contains "UniqueID" and ProcessCommandLine matches regex "([0-9]|[1-9][0-9]|[1-4][0-9]{2})")) or ((ProcessCommandLine contains "create" and FolderPath endswith "/dscl") and (ProcessCommandLine contains "IsHidden" and (ProcessCommandLine contains "true" or ProcessCommandLine contains "yes" or ProcessCommandLine contains "1")))