// Title: Delete Volume Shadow Copies via WMI with PowerShell - PS Script
// Author: frack113
// Date: 2021-12-26
// Level: high
// Description: Deletes Windows Volume Shadow Copies with PowerShell code and Get-WMIObject. This technique is used by numerous ransomware families such as Sodinokibi/REvilThis table contains security event logs from Windows machines. Ensure that the Windows Security Events data connector is enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.impact, attack.t1490
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Get-WmiObject" and ScriptBlockText contains "Win32_ShadowCopy" and ScriptBlockText contains ".Delete()"