// Title: Communication To LocaltoNet Tunneling Service Initiated
// Author: Andreas Braathen (mnemonic.io)
// Date: 2024-06-17
// Level: high
// Description: Detects an executable initiating a network connection to "LocaltoNet" tunneling sub-domains.
// LocaltoNet is a reverse proxy that enables localhost services to be exposed to the Internet.
// Attackers have been seen to use this service for command-and-control activities to bypass MFA and perimeter controls.
// 
// Tags: attack.command-and-control, attack.t1572, attack.t1090, attack.t1102
// ================================================================== 

DeviceNetworkEvents
| where RemoteUrl endswith ".localto.net" or RemoteUrl endswith ".localtonet.com"