// Title: Potential PetitPotam Attack Via EFS RPC Calls
// Author: @neu5ron, @Antonlovesdnb, Mike Remen
// Date: 2021-08-17
// Level: medium
// Description: Detects usage of the windows RPC library Encrypting File System Remote Protocol (MS-EFSRPC). Variations of this RPC are used within the attack refereed to as PetitPotam.
// The usage of this RPC function should be rare if ever used at all.
// Thus usage of this function is uncommon enough that any usage of this RPC function should warrant further investigation to determine if it is legitimate.
//  View surrounding logs (within a few minutes before and after) from the Source IP to. Logs from from the Source IP would include dce_rpc, smb_mapping, smb_files, rdp, ntlm, kerberos, etc..'
// The DnsEvents table in Microsoft Sentinel contains DNS-related logs, which may include information related to DCE_RPC service activity. To have this table present, ensure that DNS logs are being collected and sent to Sentinel.
// Tags: attack.t1557.001, attack.t1187
// ================================================================== 

DnsEvents
| where operation startswith "efs"