// Title: Arbitrary File Download Via GfxDownloadWrapper.EXE
// Author: Victor Sergeev, oscd.community
// Date: 2020-10-09
// Level: medium
// Description: Detects execution of GfxDownloadWrapper.exe with a URL as an argument to download file.
// Tags: attack.command-and-control, attack.t1105
// ================================================================== 

DeviceProcessEvents
| where ((ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://") and FolderPath endswith "\\GfxDownloadWrapper.exe") and (not(ProcessCommandLine contains "https://gameplayapi.intel.com/"))