// Title: Browser Execution In Headless Mode
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-12
// Level: medium
// Description: Detects execution of Chromium based browser in headless mode
// Tags: attack.command-and-control, attack.t1105
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "--headless" and (FolderPath endswith "\\brave.exe" or FolderPath endswith "\\chrome.exe" or FolderPath endswith "\\msedge.exe" or FolderPath endswith "\\opera.exe" or FolderPath endswith "\\vivaldi.exe")