// Title: Potential Download/Upload Activity Using Type Command
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-14
// Level: medium
// Description: Detects usage of the "type" command to download/upload data from WebDAV server
// Tags: attack.command-and-control, attack.t1105
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "type \\\\" and ProcessCommandLine contains " > ") or (ProcessCommandLine contains "type " and ProcessCommandLine contains " > \\\\")