// Title: Wget Creating Files in Tmp Directory
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-06-02
// Level: medium
// Description: Detects the use of wget to download content in a temporary directory such as "/tmp" or "/var/tmp"
// Tags: attack.command-and-control, attack.t1105
// ================================================================== 

DeviceFileEvents
| where InitiatingProcessFolderPath endswith "/wget" and (FolderPath startswith "/tmp/" or FolderPath startswith "/var/tmp/")