// Title: Azure Service Principal Removed
// Author: Austin Songer @austinsonger
// Date: 2021-09-03
// Level: medium
// Description: Identifies when a service principal was removed in Azure.This table contains Azure Activity Logs data. Ensure that Azure Activity Logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.defense-evasion
// ================================================================== 

AzureActivityLogs
| where 'properties.message' =~ "Remove service principal"