// Title: Azure Service Principal Created
// Author: Austin Songer @austinsonger
// Date: 2021-09-02
// Level: medium
// Description: Identifies when a service principal is created in Azure.This table contains Azure Activity Logs data. Ensure that Azure Activity Logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.defense-evasion
// ================================================================== 

AzureActivityLogs
| where 'properties.message' =~ "Add service principal"