// Title: LiveKD Kernel Memory Dump File Created
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-16
// Level: high
// Description: Detects the creation of a file that has the same name as the default LiveKD kernel memory dump.
// Tags: attack.defense-evasion, attack.privilege-escalation
// ================================================================== 

DeviceFileEvents
| where FolderPath =~ "C:\\Windows\\livekd.dmp"