// Title: Potential Suspicious Windows Feature Enabled
// Author: frack113
// Date: 2022-09-10
// Level: medium
// Description: Detects usage of the built-in PowerShell cmdlet "Enable-WindowsOptionalFeature" used as a Deployment Image Servicing and Management tool.
// Similar to DISM.exe, this cmdlet is used to enumerate, install, uninstall, configure, and update features and packages in Windows images
// This table contains security-related events, including PowerShell script execution events. Ensure that you have the necessary connectors and data sources configured in Sentinel to collect Windows security event logs.
// Tags: attack.defense-evasion
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "Enable-WindowsOptionalFeature" and ScriptBlockText contains "-Online" and ScriptBlockText contains "-FeatureName") and (ScriptBlockText contains "TelnetServer" or ScriptBlockText contains "Internet-Explorer-Optional-amd64" or ScriptBlockText contains "TFTP" or ScriptBlockText contains "SMB1Protocol" or ScriptBlockText contains "Client-ProjFS" or ScriptBlockText contains "Microsoft-Windows-Subsystem-Linux")