// Title: Suspicious AppX Package Locations
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-11
// Level: high
// Description: Detects an appx package added the pipeline of the "to be processed" packages which is located in suspicious locationsThe equivalent table in Microsoft Sentinel for appxdeployment-server logs is AppxPackageInventory. Make sure to have the necessary connectors or data sources configured in Sentinel to collect and ingest logs from Windows servers with the appxdeployment-server service.
// Tags: attack.defense-evasion
// ================================================================== 

AppxPackageInventory
| where Path contains "C:\\Users\\Public\\" or Path contains "/users/public/" or Path contains "C:\\PerfLogs\\" or Path contains "C:/perflogs/" or Path contains "\\Desktop\\" or Path contains "/desktop/" or Path contains "\\Downloads\\" or Path contains "/Downloads/" or Path contains "C:\\Windows\\Temp\\" or Path contains "C:/Windows/Temp/" or Path contains "\\AppdData\\Local\\Temp\\" or Path contains "/AppdData/Local/Temp/"