// Title: Suspicious Digital Signature Of AppX Package
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-16
// Level: medium
// Description: Detects execution of AppX packages with known suspicious or malicious signatureThis table contains information about appx packaging events on Windows systems. To query this table in Microsoft Sentinel, ensure that the Windows Security Events data connector is enabled and collecting data from the specified log source.
// Tags: attack.defense-evasion, attack.execution
// ================================================================== 

AppxPackageEvents
| where subjectName =~ "CN=Foresee Consulting Inc., O=Foresee Consulting Inc., L=North York, S=Ontario, C=CA, SERIALNUMBER=1004913-1, OID.1.3.6.1.4.1.311.60.2.1.3=CA, OID.2.5.4.15=Private Organization"