// Title: Uncommon AppX Package Locations
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-11
// Level: medium
// Description: Detects an appx package added the pipeline of the "to be processed" packages which is located in uncommon locationsThis table contains information about installed Appx packages on Windows devices. To query this table in Microsoft Sentinel, ensure that the Microsoft-Windows-AppXDeploymentServer/Operational log is being collected and ingested into your workspace.
// Tags: attack.defense-evasion
// ================================================================== 

AppxPackageInventory
| where not(((Path contains "C:\\Program Files\\WindowsApps\\" or Path contains "C:\\Program Files (x86)\\" or Path contains "C:\\Windows\\SystemApps\\" or Path contains "C:\\Windows\\PrintDialog\\" or Path contains "C:\\Windows\\ImmersiveControlPanel\\" or Path contains "x-windowsupdate://" or Path contains "file:///C:/Program%20Files") or (Path contains "https://statics.teams.cdn.live.net/" or Path contains "https://statics.teams.cdn.office.net/" or Path contains "microsoft.com" or Path contains "https://installer.teams.static.microsoft/")))