// Title: Windows Service Terminated With Error
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-14
// Level: low
// Description: Detects Windows services that got terminated for whatever reasonThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events data connector is enabled in Sentinel to have this table available for querying.
// Tags: attack.defense-evasion
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager"