// Title: Winget Admin Settings Modification
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-17
// Level: low
// Description: Detects changes to the AppInstaller (winget) admin settings. Such as enabling local manifest installations or disabling installer hash checks
// Tags: attack.defense-evasion, attack.persistence
// ================================================================== 

DeviceRegistryEvents
| where InitiatingProcessFolderPath endswith "\\winget.exe" and RegistryKey endswith "\\LocalState\\admin_settings" and RegistryKey =~ "\\REGISTRY\\A*"