// Title: Visual Studio NodejsTools PressAnyKey Arbitrary Binary Execution
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-01-11
// Level: medium
// Description: Detects child processes of Microsoft.NodejsTools.PressAnyKey.exe that can be used to execute any other binary
// Tags: attack.execution, attack.defense-evasion, attack.t1218
// ================================================================== 

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\Microsoft.NodejsTools.PressAnyKey.exe"