// Title: QuickAssist Execution
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2024-12-19
// Level: low
// Description: Detects the execution of Microsoft Quick Assist tool "QuickAssist.exe". This utility can be used by attackers to gain remote access.
// 
// Tags: attack.command-and-control, attack.t1219
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "\\QuickAssist.exe"