// Title: Remote Access Tool - MeshAgent Command Execution via MeshCentral
// Author: @Kostastsale
// Date: 2024-09-22
// Level: medium
// Description: Detects the use of MeshAgent to execute commands on the target host, particularly when threat actors might abuse it to execute commands directly.
// MeshAgent can execute commands on the target host by leveraging win-console to obscure their activities and win-dispatcher to run malicious code through IPC with child processes.
// 
// Tags: attack.command-and-control, attack.t1219
// ================================================================== 

DeviceProcessEvents
| where (FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") and InitiatingProcessFolderPath endswith "\\meshagent.exe"