// Title: Cscript/Wscript Uncommon Script Extension Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-15
// Level: high
// Description: Detects Wscript/Cscript executing a file with an uncommon (i.e. non-script) extension
// Tags: attack.execution, attack.t1059.005, attack.t1059.007
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains ".csv" or ProcessCommandLine contains ".dat" or ProcessCommandLine contains ".doc" or ProcessCommandLine contains ".gif" or ProcessCommandLine contains ".jpeg" or ProcessCommandLine contains ".jpg" or ProcessCommandLine contains ".png" or ProcessCommandLine contains ".ppt" or ProcessCommandLine contains ".txt" or ProcessCommandLine contains ".xls" or ProcessCommandLine contains ".xml") and ((ProcessVersionInfoOriginalFileName in~ ("wscript.exe", "cscript.exe")) or (FolderPath endswith "\\wscript.exe" or FolderPath endswith "\\cscript.exe"))