// Title: OpenCanary - VNC Connection Attempt
// Author: Security Onion Solutions
// Date: 2024-03-08
// Level: high
// Description: Detects instances where a VNC service on an OpenCanary node has had a connection attempt.The OpencanaryLogs table in Microsoft Sentinel contains logs related to the Opencanary application. To have this table present in Sentinel, you need to ensure that Opencanary logs are being collected and sent to Sentinel for analysis.
// Tags: attack.lateral-movement, attack.t1021
// ================================================================== 

OpencanaryLogs
| where logtype == 12001