// Title: PowerShell Downgrade Attack - PowerShell
// Author: Florian Roth (Nextron Systems), Lee Holmes (idea), Harish Segar (improvements)
// Date: 2017-03-22
// Level: medium
// Description: Detects PowerShell downgrade attack by comparing the host versions with the actually used engine version 2.0The SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events data connector is enabled in Microsoft Sentinel to have this table available for querying.
// Tags: attack.defense-evasion, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where Data contains "EngineVersion=2." and (not(Data contains "HostVersion=2."))