// Title: AMSI Bypass Pattern Assembly GetType
// Author: Florian Roth (Nextron Systems)
// Date: 2022-11-09
// Level: high
// Description: Detects code fragments found in small and obfuscated AMSI bypass PowerShell scriptsThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the necessary data connectors are set up in Sentinel to collect Windows security event logs.
// Tags: attack.defense-evasion, attack.t1562.001, attack.execution
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "[Ref].Assembly.GetType" and ScriptBlockText contains "SetValue($null,$true)" and ScriptBlockText contains "NonPublic,Static"