// Title: AWS GuardDuty Important Change
// Author: faloker
// Date: 2020-02-11
// Level: high
// Description: Detects updates of the GuardDuty list of trusted IPs, perhaps to disable security alerts against malicious IPs.The equivalent table in Microsoft Sentinel for AWS CloudTrail logs. Ensure that the AWS CloudTrail connector is set up in Sentinel to collect and ingest these logs.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

CloudTrail
| where eventName =~ "CreateIPSet" and eventSource =~ "guardduty.amazonaws.com"