// Title: AWS CloudTrail Important Change
// Author: vitaliy0x1
// Date: 2020-01-21
// Level: medium
// Description: Detects disabling, deleting and updating of a TrailThe CloudTrail table in Microsoft Sentinel contains logs related to AWS CloudTrail service. To have this table present in Sentinel, you need to ensure that you have the AWS CloudTrail connector configured and collecting logs from your AWS environment.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

CloudTrail
| where (eventName in~ ("StopLogging", "UpdateTrail", "DeleteTrail")) and eventSource =~ "cloudtrail.amazonaws.com"