// Title: Bitbucket Secret Scanning Exempt Repository Added
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2024-02-25
// Level: high
// Description: Detects when a repository is exempted from secret scanning feature.This table contains audit logs for various services including Bitbucket. Make sure to enable the necessary connectors and data sources in Microsoft Sentinel to collect and ingest these logs.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

AuditLogs
| where 'auditType.action' =~ "Secret scanning exempt repository added" and 'auditType.category' =~ "Repositories"