// Title: Bitbucket Secret Scanning Rule Deleted
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2024-02-25
// Level: low
// Description: Detects when secret scanning rule is deleted for the project or repository.This table contains audit logs for various services including Bitbucket. Make sure to enable the appropriate connectors or data sources in Microsoft Sentinel to collect Bitbucket audit logs.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

AuditLogs
| where ('auditType.action' in~ ("Project secret scanning rule deleted", "Repository secret scanning rule deleted")) and ('auditType.category' in~ ("Projects", "Repositories"))