// Title: Bitbucket Global Secret Scanning Rule Deleted
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2024-02-25
// Level: medium
// Description: Detects Bitbucket global secret scanning rule deletion activity.This table contains audit logs for various services, including Bitbucket. Make sure to enable the necessary connectors and data sources for Bitbucket audit logs in Microsoft Sentinel.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

AuditLogs
| where 'auditType.action' =~ "Global secret scanning rule deleted" and 'auditType.category' =~ "Global administration"