// Title: Bitbucket Project Secret Scanning Allowlist Added
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2024-02-25
// Level: low
// Description: Detects when a secret scanning allowlist rule is added for projects.This table contains audit logs for various services, including Bitbucket. Make sure to enable the necessary connectors or data sources to collect Bitbucket audit logs in Sentinel.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

AuditLogs
| where 'auditType.action' =~ "Project secret scanning allowlist rule added" and 'auditType.category' =~ "Projects"