// Title: Bitbucket Audit Log Configuration Updated
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2024-02-25
// Level: medium
// Description: Detects changes to the bitbucket audit log configuration.This table contains audit logs for various services including Bitbucket. Make sure to enable the necessary connectors or data sources in Sentinel to collect Bitbucket audit logs.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

AuditLogs
| where 'auditType.action' =~ "Audit log configuration updated" and 'auditType.category' =~ "Auditing"