// Title: Cisco Disabling Logging
// Author: Austin Clark
// Date: 2019-08-11
// Level: high
// Description: Turn off logging locally or remoteThis table contains authentication logs from Cisco AAA service. Ensure that the necessary connectors or data connectors are installed in Sentinel to collect logs from Cisco devices and services.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

Cisco_AAA_AuthenticationLogs
| where "no logging" or "no aaa new-model"