// Title: Disable-WindowsOptionalFeature Command PowerShell
// Author: frack113
// Date: 2022-09-10
// Level: high
// Description: Detect built in PowerShell cmdlet Disable-WindowsOptionalFeature, Deployment Image Servicing and Management tool.
// Similar to DISM.exe, this cmdlet is used to enumerate, install, uninstall, configure, and update features and packages in Windows images
// This table contains Windows security event logs, including script block logging events. Ensure that the Windows Security Events connector is enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "Disable-WindowsOptionalFeature" and ScriptBlockText contains "-Online" and ScriptBlockText contains "-FeatureName") and (ScriptBlockText contains "Windows-Defender-Gui" or ScriptBlockText contains "Windows-Defender-Features" or ScriptBlockText contains "Windows-Defender" or ScriptBlockText contains "Windows-Defender-ApplicationGuard")