// Title: Github Secret Scanning Feature Disabled
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2024-03-07
// Level: high
// Description: Detects if the secret scanning feature is disabled for an enterprise or repository.This table contains audit logs for the Github service. To have this table present in Microsoft Sentinel, make sure to have the Github connector configured and collecting data from the audit service.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

GithubAuditLogs
| where action in~ ("business_secret_scanning.disable", "business_secret_scanning.disabled_for_new_repos", "repository_secret_scanning.disable", "secret_scanning_new_repos.disable", "secret_scanning.disable")