// Title: Microsoft Defender Tamper Protection Trigger
// Author: Bhabesh Raj, Nasreddine Bencherchali
// Date: 2021-07-05
// Level: high
// Description: Detects blocked attempts to change any of Defender's settings such as "Real Time Monitoring" and "Behavior Monitoring"The SecurityEvent table in Microsoft Sentinel contains Windows security event logs. To query this table for events related to Windows Defender, you can filter based on the 'Channel' field for 'Microsoft-Windows-Security-Mitigations' and 'ProviderName' field for 'Microsoft-Windows-Windows Defender'. Ensure that you have the necessary connectors and data sources configured in Sentinel to collect Windows security event logs.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

SecurityEvent
| where Value endswith "\\Windows Defender\\DisableAntiSpyware" or Value endswith "\\Windows Defender\\DisableAntiVirus" or Value endswith "\\Windows Defender\\Scan\\DisableArchiveScanning" or Value endswith "\\Windows Defender\\Scan\\DisableScanningNetworkFiles" or Value endswith "\\Real-Time Protection\\DisableRealtimeMonitoring" or Value endswith "\\Real-Time Protection\\DisableBehaviorMonitoring" or Value endswith "\\Real-Time Protection\\DisableIOAVProtection" or Value endswith "\\Real-Time Protection\\DisableScriptScanning"