// Title: Tamper Windows Defender Remove-MpPreference - ScriptBlockLogging
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-05
// Level: high
// Description: Detects attempts to remove Windows Defender configuration using the 'MpPreference' cmdletThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Make sure to have the necessary data connectors and log sources configured in Sentinel to collect Windows security event logs.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Remove-MpPreference" and (ScriptBlockText contains "-ControlledFolderAccessProtectedFolders " or ScriptBlockText contains "-AttackSurfaceReductionRules_Ids " or ScriptBlockText contains "-AttackSurfaceReductionRules_Actions " or ScriptBlockText contains "-CheckForSignaturesBeforeRunningScan ")