// Title: Windows Defender Configuration Changes
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-06
// Level: high
// Description: Detects suspicious changes to the Windows Defender configurationThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. To query this table for events related to Windows Defender, you can filter on the 'Channel' field with 'Microsoft-Windows-Security-Auditing' and 'EventID' field with the specific event IDs related to Windows Defender.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

SecurityEvent
| where NewValue contains "\\Windows Defender\\DisableAntiSpyware " or NewValue contains "\\Windows Defender\\Scan\\DisableRemovableDriveScanning " or NewValue contains "\\Windows Defender\\Scan\\DisableScanningMappedNetworkDrivesForFullScan " or NewValue contains "\\Windows Defender\\SpyNet\\DisableBlockAtFirstSeen " or NewValue contains "\\Real-Time Protection\\SpyNetReporting "