// Title: Windows Defender Threat Detection Service Disabled
// Author: Ján Trenčanský, frack113
// Date: 2020-07-28
// Level: medium
// Description: Detects when the "Windows Defender Threat Protection" service is disabled.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager" and (param1 in~ ("Windows Defender Antivirus Service", "Service antivirus Microsoft Defender")) and (param2 in~ ("stopped", "arrêté"))