// Title: Windows Defender Submit Sample Feature Disabled
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-06
// Level: low
// Description: Detects disabling of the "Automatic Sample Submission" feature of Windows Defender.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which can include information about Windows Defender service (windefend) events. Ensure that the Windows security events are being collected and ingested into Sentinel for this table to be available.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

SecurityEvent
| where NewValue contains "\\Real-Time Protection\\SubmitSamplesConsent = 0x0"