// Title: Windows Defender Real-Time Protection Failure/Restart
// Author: Nasreddine Bencherchali (Nextron Systems), Christopher Peacock '@securepeacock' (Update)
// Date: 2023-03-28
// Level: medium
// Description: Detects issues with Windows Defender Real-Time Protection featuresThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which can include information about Windows Defender (windefend) service events. Ensure that the Windows Security Events data connector is enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1562.001
// ================================================================== 

SecurityEvent
| where not((Feature_Name =~ "%%886" and (Reason in~ ("%%892", "%%858"))))