// Title: AWS S3 Data Management Tampering
// Author: Austin Songer @austinsonger
// Date: 2021-07-24
// Level: low
// Description: Detects when a user tampers with S3 data management in Amazon Web Services.The equivalent table in Microsoft Sentinel for AWS CloudTrail logs. Ensure that the AWS CloudTrail connector is set up in Sentinel to collect and ingest these logs.
// Tags: attack.exfiltration, attack.t1537
// ================================================================== 

CloudTrail
| where (eventName in~ ("PutBucketLogging", "PutBucketWebsite", "PutEncryptionConfiguration", "PutLifecycleConfiguration", "PutReplicationConfiguration", "ReplicateObject", "RestoreObject")) and eventSource =~ "s3.amazonaws.com"