// Title: Clipboard Collection of Image Data with Xclip Tool
// Author: Pawel Mazur
// Date: 2021-10-01
// Level: low
// Description: Detects attempts to collect image data stored in the clipboard from users with the usage of xclip tool.
// Xclip has to be installed.
// Highly recommended using rule on servers, due to high usage of clipboard utilities on user workstations.
// The SecurityEvent table in Microsoft Sentinel contains security-related events from various sources, including audit logs. To have Linux audit logs available in the SecurityEvent table, ensure that the Linux machines are onboarded to Sentinel and have the necessary data connectors or agents installed to collect and forward the audit logs.
// Tags: attack.collection, attack.t1115
// ================================================================== 

SecurityEvent
| where a0 =~ "xclip" and (a1 in~ ("-selection", "-sel")) and (a2 in~ ("clipboard", "clip")) and a3 =~ "-t" and a4 startswith "image/" and a5 =~ "-o" and type =~ "EXECVE"