// Title: PowerShell Get Clipboard
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-05-02
// Level: medium
// Description: A General detection for the Get-Clipboard commands in PowerShell logs. This could be an adversary capturing clipboard contents.This table contains security event logs from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to collect these logs.
// Tags: attack.collection, attack.t1115
// ================================================================== 

SecurityEvent
| where Payload contains "Get-Clipboard"