// Title: ADS Zone.Identifier Deleted
// Author: frack113
// Date: 2023-09-04
// Level: low
// Description: Detects the deletion of the "Zone.Identifier" ADS. Attackers can leverage this in order to bypass security restrictions that make use of the ADS such as Microsoft Office apps.
// Tags: attack.defense-evasion, attack.t1070.004, detection.threat-hunting
// ================================================================== 

DeviceFileEvents
| where FolderPath endswith ":Zone.Identifier"