// Title: Potential SolidPDFCreator.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-05-07
// Level: medium
// Description: Detects potential DLL sideloading of "SolidPDFCreator.dll"
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1574.001, attack.t1574.002
// ================================================================== 

DeviceImageLoadEvents
| where FolderPath endswith "\\SolidPDFCreator.dll" and (not(((FolderPath startswith "C:\\Program Files (x86)\\SolidDocuments\\SolidPDFCreator\\" or FolderPath startswith "C:\\Program Files\\SolidDocuments\\SolidPDFCreator\\") and InitiatingProcessFolderPath endswith "\\SolidPDFCreator.exe")))