// Title: Potential Vivaldi_elf.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-08-03
// Level: medium
// Description: Detects potential DLL sideloading of "vivaldi_elf.dll"
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1574.001, attack.t1574.002
// ================================================================== 

DeviceImageLoadEvents
| where FolderPath endswith "\\vivaldi_elf.dll" and (not((FolderPath contains "\\Vivaldi\\Application\\" and InitiatingProcessFolderPath endswith "\\Vivaldi\\Application\\vivaldi.exe")))