// Title: Potential ShellDispatch.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-06-20
// Level: medium
// Description: Detects potential DLL sideloading of "ShellDispatch.dll"
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1574.001, attack.t1574.002
// ================================================================== 

DeviceImageLoadEvents
| where FolderPath endswith "\\ShellDispatch.dll" and (not(((FolderPath contains ":\\Users\\" and FolderPath contains "\\AppData\\Local\\Temp\\") or FolderPath contains ":\\Windows\\Temp\\")))