// Title: Potential EACore.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-08-03
// Level: high
// Description: Detects potential DLL sideloading of "EACore.dll"
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1574.001, attack.t1574.002
// ================================================================== 

DeviceImageLoadEvents
| where FolderPath endswith "\\EACore.dll" and (not((FolderPath startswith "C:\\Program Files\\Electronic Arts\\EA Desktop\\" and (InitiatingProcessFolderPath contains "C:\\Program Files\\Electronic Arts\\EA Desktop\\" and InitiatingProcessFolderPath contains "\\EACoreServer.exe"))))