// Title: ETW Logging/Processing Option Disabled On IIS Server
// Author: frack113, Nasreddine Bencherchali
// Date: 2024-10-06
// Level: medium
// Description: Detects changes to of the IIS server configuration in order to disable/remove the ETW logging/processing option.This table corresponds to IIS configuration logs in Microsoft Sentinel. To have this table present, ensure that the necessary data connectors for Windows and IIS logs are configured in Sentinel.
// Tags: attack.defense-evasion, attack.t1562.002, attack.t1505.004
// ================================================================== 

IISConfig
| where (Configuration endswith "@logTargetW3C" and OldValue contains "ETW") and (not(NewValue contains "ETW"))