// Title: HTTP Logging Disabled On IIS Server
// Author: frack113
// Date: 2024-10-06
// Level: high
// Description: Detects changes to of the IIS server configuration in order to disable HTTP logging for successful requests.This table contains IIS configuration data for Windows systems. Ensure that the required data connectors for Windows and IIS logs are enabled in Microsoft Sentinel to have this table available for querying.
// Tags: attack.defense-evasion, attack.t1562.002, attack.t1505.004
// ================================================================== 

IISConfiguration
| where Configuration =~ "/system.webServer/httpLogging/@dontLog" and NewValue =~ "true"