// Title: New Module Module Added To IIS Server
// Author: frack113
// Date: 2024-10-06
// Level: medium
// Description: Detects the addition of a new module to an IIS server.This table corresponds to IIS configuration logs in Microsoft Sentinel. Ensure that the necessary connectors are set up to collect IIS configuration logs from Windows servers.
// Tags: attack.defense-evasion, attack.persistence, attack.t1562.002, attack.t1505.004
// ================================================================== 

IISConfig
| where Configuration contains "/system.webServer/modules/add" and (not(((NewValue in~ ("AnonymousAuthenticationModule", "CustomErrorModule", "DefaultDocumentModule", "DirectoryListingModule", "FileCacheModule", "HttpCacheModule", "HttpLoggingModule", "ProtocolSupportModule", "RequestFilteringModule", "StaticCompressionModule", "StaticFileModule", "TokenCacheModule", "UriCacheModule")) or NewValue =~ "")))