// Title: OpenCanary - NTP Monlist Request
// Author: Security Onion Solutions
// Date: 2024-03-08
// Level: high
// Description: Detects instances where an NTP service on an OpenCanary node has had a NTP monlist request.This table contains logs related to the Opencanary application. To have this table present in Microsoft Sentinel, ensure that Opencanary logs are being collected and sent to Sentinel for analysis.
// Tags: attack.impact, attack.t1498
// ================================================================== 

OpencanaryLogs
| where logtype == 11001