// Title: Anonymous IP Address
// Author: Gloria Lee, '@gleeiamglo'
// Date: 2023-08-22
// Level: high
// Description: Indicates sign-ins from an anonymous IP address, for example, using an anonymous browser or VPN.The AzureActivity table in Microsoft Sentinel contains logs related to Azure activity, including risk detection events. To ensure this table is populated, make sure to have the Azure Monitor logs solution installed in Sentinel and properly configured to collect logs from the Azure service.
// Tags: attack.t1528, attack.credential-access
// ================================================================== 

AzureActivity
| where riskEventType =~ "anonymizedIPAddress"