// Title: Microsoft Teams Sensitive File Access By Uncommon Applications
// Author: @SerkinValery
// Date: 2024-07-22
// Level: medium
// Description: Detects file access attempts to sensitive Microsoft teams files (leveldb, cookies) by an uncommon process.
// 
// Tags: attack.credential-access, attack.t1528
// ================================================================== 

DeviceFileEvents
| where (FileName contains "\\Microsoft\\Teams\\Cookies" or FileName contains "\\Microsoft\\Teams\\Local Storage\\leveldb") and (not(InitiatingProcessFolderPath endswith "\\Microsoft\\Teams\\current\\Teams.exe"))