// Title: Potential Active Directory Enumeration Using AD Module - PsModule
// Author: Nasreddine Bencherchali (Nextron Systems), frack113
// Date: 2023-01-22
// Level: medium
// Description: Detects usage of the "Import-Module" cmdlet to load the "Microsoft.ActiveDirectory.Management.dl" DLL. Which is often used by attackers to perform AD enumeration.This table contains security-related events from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.reconnaissance, attack.discovery, attack.impact
// ================================================================== 

SecurityEvent
| where (Payload contains "Import-Module " or Payload contains "ipmo ") and Payload contains "Microsoft.ActiveDirectory.Management.dll"