// Title: Potential Active Directory Enumeration Using AD Module - PsScript
// Author: frack113, Nasreddine Bencherchali
// Date: 2023-01-22
// Level: medium
// Description: Detects usage of the "Import-Module" cmdlet to load the "Microsoft.ActiveDirectory.Management.dl" DLL. Which is often used by attackers to perform AD enumeration.This table contains Windows security event logs, including PowerShell script block logging events. Ensure that the Windows Security Events data connector is enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.reconnaissance, attack.discovery, attack.impact
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "Import-Module " and ScriptBlockText contains "Microsoft.ActiveDirectory.Management.dll") or ScriptBlockText contains "ipmo Microsoft.ActiveDirectory.Management.dll"