// Title: Suspicious Use of /dev/tcp
// Author: frack113
// Date: 2021-12-10
// Level: medium
// Description: Detects suspicious command with /dev/tcpThis table contains Linux audit logs. Ensure that the Linux machines are onboarded to Microsoft Sentinel and the Linux audit logs are being collected and forwarded to Sentinel for this table to be populated.
// Tags: attack.reconnaissance
// ================================================================== 

LinuxAuditLogs
| where "cat </dev/tcp/" or "exec 3<>/dev/tcp/" or "echo >/dev/tcp/" or "bash -i >& /dev/tcp/" or "sh -i >& /dev/udp/" or "0<&196;exec 196<>/dev/tcp/" or "exec 5<>/dev/tcp/" or "(sh)0>/dev/tcp/" or "bash -c 'bash -i >& /dev/tcp/" or "echo -e '#!/bin/bash\\nbash -i >& /dev/tcp/"