// Title: Potential In-Memory Execution Using Reflection.Assembly
// Author: frack113
// Date: 2022-12-25
// Level: medium
// Description: Detects usage of "Reflection.Assembly" load functions to dynamically load assemblies in memoryThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which can include information about PowerShell script execution. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1620
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "[Reflection.Assembly]::load"