// Title: PowerShell Credential Prompt
// Author: John Lambert (idea), Florian Roth (Nextron Systems)
// Date: 2017-04-09
// Level: high
// Description: Detects PowerShell calling a credential promptThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include events related to PowerShell script execution. Ensure that the Windows security events are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.credential-access, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "PromptForCredential"