// Title: Remote Access Tool Services Have Been Installed - System
// Author: Connor Martin, Nasreddine Bencherchali
// Date: 2022-12-23
// Level: medium
// Description: Detects service installation of different remote access tools software. These software are often abused by threat actors to performThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Make sure to have the Windows Security Events connector enabled in Sentinel to collect these logs.
// Tags: attack.persistence, attack.t1543.003, attack.t1569.002
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager" and (ServiceName contains "AmmyyAdmin" or ServiceName contains "Atera" or ServiceName contains "BASupportExpressSrvcUpdater" or ServiceName contains "BASupportExpressStandaloneService" or ServiceName contains "chromoting" or ServiceName contains "GoToAssist" or ServiceName contains "GoToMyPC" or ServiceName contains "jumpcloud" or ServiceName contains "LMIGuardianSvc" or ServiceName contains "LogMeIn" or ServiceName contains "monblanking" or ServiceName contains "Parsec" or ServiceName contains "RManService" or ServiceName contains "RPCPerformanceService" or ServiceName contains "RPCService" or ServiceName contains "SplashtopRemoteService" or ServiceName contains "SSUService" or ServiceName contains "TeamViewer" or ServiceName contains "TightVNC" or ServiceName contains "vncserver" or ServiceName contains "Zoho")