// Title: Azure AD Account Credential Leaked
// Author: Mark Morowczynski '@markmorow', Gloria Lee, '@gleeiamglo'
// Date: 2023-09-03
// Level: high
// Description: Indicates that the user's valid credentials have been leaked.The AzureActivity table in Microsoft Sentinel contains logs related to Azure services, including risk detection events. Ensure that Azure Activity logs are being collected and ingested into Sentinel to query this table.
// Tags: attack.t1589, attack.reconnaissance
// ================================================================== 

AzureActivity
| where riskEventType =~ "leakedCredentials"