// Title: New Kubernetes Service Account Created
// Author: Leo Tsaousis (@laripping)
// Date: 2024-03-26
// Level: low
// Description: Detects creation of new Kubernetes service account, which could indicate an attacker's attempt to persist within a cluster.
// This table contains Kubernetes audit logs. To have this table present in Microsoft Sentinel, ensure that you have the necessary connectors or data sources configured to collect Kubernetes audit logs.
// Tags: attack.t1136
// ================================================================== 

KubeEvents
| where 'objectRef.resource' =~ "serviceaccounts" and verb =~ "create"