// Title: Important Scheduled Task Deleted
// Author: frack113
// Date: 2023-01-13
// Level: high
// Description: Detects when adversaries try to stop system services or processes by deleting their respective scheduled tasks in order to conduct data destructive activities
// The equivalent table in KQL for Microsoft Sentinel is the Event table. This table contains all the events collected by Sentinel, including events from the Microsoft-Windows-TaskScheduler/Operational log source. To ensure this table is present, make sure to have the necessary data connectors and log sources configured in Sentinel to collect events from the Windows Task Scheduler service.
// Tags: attack.impact, attack.t1489
// ================================================================== 

Event
| where (TaskName contains "\\Windows\\SystemRestore\\SR" or TaskName contains "\\Windows\\Windows Defender\\" or TaskName contains "\\Windows\\BitLocker" or TaskName contains "\\Windows\\WindowsBackup\\" or TaskName contains "\\Windows\\WindowsUpdate\\" or TaskName contains "\\Windows\\UpdateOrchestrator\\" or TaskName contains "\\Windows\\ExploitGuard") and (not((UserName contains "AUTHORI" or UserName contains "AUTORI")))