// Title: PUA - Nmap/Zenmap Execution
// Author: frack113
// Date: 2021-12-10
// Level: medium
// Description: Detects usage of namp/zenmap. Adversaries may attempt to get a listing of services running on remote hosts, including those that may be vulnerable to remote software exploitation
// Tags: attack.discovery, attack.t1046
// ================================================================== 

DeviceProcessEvents
| where (FolderPath endswith "\\nmap.exe" or FolderPath endswith "\\zennmap.exe") or (ProcessVersionInfoOriginalFileName in~ ("nmap.exe", "zennmap.exe"))