// Title: Suspicious Network Communication With IPFS
// Author: Gavin Knapp
// Date: 2023-03-16
// Level: low
// Description: Detects connections to interplanetary file system (IPFS) containing a user's email address which mirrors behaviours observed in recent phishing campaigns leveraging IPFS to host credential harvesting webpages.This table contains proxy logs, which can be queried in Microsoft Sentinel. Make sure to have the necessary connectors or data sources configured in Sentinel to collect proxy logs and populate this table.
// Tags: attack.credential-access, attack.t1056
// ================================================================== 

ProxyLog
| where 'cs-uri' matches regex "(?i)(ipfs\\.io/|ipfs\\.io\\s).+\\..+@.+\\.[a-z]+"