// Title: ESXi VSAN Information Discovery Via ESXCLI
// Author: Nasreddine Bencherchali (Nextron Systems), Cedric Maurugeon
// Date: 2023-09-04
// Level: medium
// Description: Detects execution of the "esxcli" command with the "vsan" flag in order to retrieve information about virtual storage. Seen used by malware such as DarkSide.
// Tags: attack.discovery, attack.t1033, attack.t1007
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains " get" or ProcessCommandLine contains " list") and (ProcessCommandLine contains "vsan" and FolderPath endswith "/esxcli")