// Title: New BgInfo.EXE Custom WMI Query Registry Configuration
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-16
// Level: medium
// Description: Detects setting of a new registry value related to BgInfo configuration, which can be abused to execute custom WMI query via "BgInfo.exe"
// Tags: attack.defense-evasion, attack.t1112
// ================================================================== 

DeviceRegistryEvents
| where RegistryValueData startswith "6" and ActionType =~ "RegistryValueSet" and RegistryKey endswith "\\Software\\Winternals\\BGInfo\\UserFields*"