// Title: Windows Binary Executed From WSL
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-14
// Level: medium
// Description: Detects the execution of Windows binaries from within a WSL instance.
// This could be used to masquerade parent-child relationships
// The SecurityEvent table in Microsoft Sentinel contains process creation events on Windows systems. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.execution, attack.defense-evasion, attack.t1202
// ================================================================== 

SecurityEvent
| where CurrentDirectory contains "\\\\wsl.localhost" and FolderPath matches regex "[a-zA-Z]:\\\\"