// Title: Suspicious Execution From Outlook Temporary Folder
// Author: Florian Roth (Nextron Systems)
// Date: 2019-10-01
// Level: high
// Description: Detects a suspicious program execution in Outlook temp folder
// Tags: attack.initial-access, attack.t1566.001
// ================================================================== 

DeviceProcessEvents
| where FolderPath contains "\\Temporary Internet Files\\Content.Outlook\\"