// Title: Remote Printing Abuse for Lateral Movement
// Author: Sagie Dulce, Dekel Paz
// Date: 2022-01-01
// Level: high
// Description: Detects remote RPC calls to possibly abuse remote printing service via MS-RPRN / MS-PARThis table may not exist by default in Microsoft Sentinel. To have this table present, you may need to enable RPC Firewall logging in your environment and ensure that the logs are being sent to Sentinel for ingestion.
// Tags: attack.lateral-movement
// ================================================================== 

rpc_firewall_logs
| where EventLog =~ "RPCFW" and (InterfaceUuid in~ ("12345678-1234-abcd-ef00-0123456789ab", "76f03f96-cdfd-44fc-a22c-64950a001209", "0b6edbfa-4a24-4fc6-8a23-942b1eca65d1", "ae33069b-a2a8-46ee-a235-ddfd339be281"))