// Title: Potential Process Hollowing Activity
// Author: Christopher Peacock '@securepeacock', SCYTHE '@scythe_io', Sittikorn S
// Date: 2022-01-25
// Level: medium
// Description: Detects when a memory process image does not match the disk image, indicative of process hollowing.The SecurityEvent table in Microsoft Sentinel contains information about security-related events on Windows machines. To query process tampering events, you can filter on the EventID field for specific process tampering event IDs. Ensure that the necessary data connectors are set up in Sentinel to collect Windows security event logs.
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1055.012
// ================================================================== 

SecurityEvent
| where Type =~ "Image is replaced" and (not((InitiatingProcessFolderPath contains ":\\Program Files (x86)" or InitiatingProcessFolderPath contains ":\\Program Files\\" or InitiatingProcessFolderPath contains ":\\Windows\\System32\\wbem\\WMIADAP.exe" or InitiatingProcessFolderPath contains ":\\Windows\\SysWOW64\\wbem\\WMIADAP.exe"))) and (not((InitiatingProcessFolderPath endswith "\\WindowsApps\\MicrosoftEdge.exe" or (InitiatingProcessFolderPath contains "\\AppData\\Local\\Programs\\Opera\\" and InitiatingProcessFolderPath endswith "\\opera.exe"))))