// Title: Powershell Keylogging
// Author: frack113
// Date: 2021-07-30
// Level: medium
// Description: Adversaries may log user keystrokes to intercept credentials as the user types them.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.collection, attack.t1056.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Get-Keystrokes" or (ScriptBlockText contains "Get-ProcAddress user32.dll GetAsyncKeyState" and ScriptBlockText contains "Get-ProcAddress user32.dll GetForegroundWindow")