// Title: Bitbucket Global SSH Settings Changed
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2024-02-25
// Level: medium
// Description: Detects Bitbucket global SSH access configuration changes.This table contains audit logs for various services including Bitbucket. Make sure to enable the necessary connectors and log sources for Bitbucket in Microsoft Sentinel to populate this table.
// Tags: attack.lateral-movement, attack.defense-evasion, attack.t1562.001, attack.t1021.004
// ================================================================== 

AuditLogs
| where 'auditType.action' =~ "SSH settings changed" and 'auditType.category' =~ "Global administration"