// Title: Silenttrinity Stager Msbuild Activity
// Author: Kiran kumar s, oscd.community
// Date: 2020-10-11
// Level: high
// Description: Detects a possible remote connections to Silenttrinity c2
// Tags: attack.execution, attack.t1127.001
// ================================================================== 

DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\msbuild.exe" and (RemotePort in~ ("80", "443"))