// Title: Windows Mail App Mailbox Access Via PowerShell Script
// Author: frack113
// Date: 2023-07-08
// Level: medium
// Description: Detects PowerShell scripts that try to access the default Windows MailApp MailBox. This indicates manipulation of or access to the stored emails of a user. E.g. this could be used by an attacker to exfiltrate or delete the content of the emails.This table contains security event logs from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1070.008, detection.threat-hunting
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "\\Comms\\Unistore\\data"