// Title: Copy .DMP/.DUMP Files From Remote Share Via Cmd.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-27
// Level: high
// Description: Detects usage of the copy builtin cmd command to copy files with the ".dmp"/".dump" extension from a remote share
// Tags: attack.credential-access
// ================================================================== 

DeviceProcessEvents
| where ((ProcessCommandLine contains ".dmp" or ProcessCommandLine contains ".dump" or ProcessCommandLine contains ".hdmp") and (ProcessCommandLine contains "copy " and ProcessCommandLine contains " \\\\")) and (FolderPath endswith "\\cmd.exe" or ProcessVersionInfoOriginalFileName =~ "Cmd.Exe")