// Title: Azure Subscription Permission Elevation Via ActivityLogs
// Author: Austin Songer @austinsonger
// Date: 2021-11-26
// Level: high
// Description: Detects when a user has been elevated to manage all Azure Subscriptions.
// This change should be investigated immediately if it isn't planned.
// This setting could allow an attacker access to Azure subscriptions in your environment.
// This table contains Azure Activity Logs, which can be queried in KQL for Microsoft Sentinel. Ensure that Azure Activity Logs are being collected and ingested into Sentinel for this table to be available.
// Tags: attack.initial-access, attack.t1078.004
// ================================================================== 

AzureActivityLog
| where operationName =~ "MICROSOFT.AUTHORIZATION/ELEVATEACCESS/ACTION"