// Title: Failed Authentications From Countries You Do Not Operate Out Of
// Author: MikeDuddington, '@dudders1'
// Date: 2022-07-28
// Level: low
// Description: Detect failed authentications from countries you do not operate out of.The equivalent table in Microsoft Sentinel for Azure signin logs. Ensure that Azure Active Directory logs are being collected and ingested into Sentinel to query this table.
// Tags: attack.initial-access, attack.credential-access, attack.t1078.004, attack.t1110
// ================================================================== 

SigninLogs
| where (not(Status =~ "Success")) and (not(Location contains "<Countries you DO operate out of e,g GB, use OR for multiple>"))