// Title: Login to Disabled Account
// Author: AlertIQ
// Date: 2021-10-10
// Level: medium
// Description: Detect failed attempts to sign in to disabled accounts.The equivalent table in Microsoft Sentinel for Azure signin logs. Ensure that Azure Active Directory logs are being ingested into Sentinel to have this table available.
// Tags: attack.initial-access, attack.t1078.004
// ================================================================== 

SigninLogs
| where ResultDescription =~ "User account is disabled. The account has been disabled by an administrator." and ResultType == 50057