// Title: Multifactor Authentication Interrupted
// Author: AlertIQ
// Date: 2021-10-10
// Level: medium
// Description: Identifies user login with multifactor authentication failures, which might be an indication an attacker has the password for the account but can't pass the MFA challenge.The equivalent table in Microsoft Sentinel for Azure sign-in logs. Ensure that Azure Active Directory logs are being ingested into Sentinel to have this table available.
// Tags: attack.initial-access, attack.credential-access, attack.t1078.004, attack.t1110, attack.t1621
// ================================================================== 

SigninLogs
| where (ResultDescription contains "Authentication failed during strong authentication request" and ResultType == 500121) or (ResultDescription contains "Strong Auth required" and ResultType == 50074)