// Title: Potential MFA Bypass Using Legacy Client Authentication
// Author: Harjot Singh, '@cyb3rjy0t'
// Date: 2023-03-20
// Level: high
// Description: Detects successful authentication from potential clients using legacy authentication via user agent strings. This could be a sign of MFA bypass using a password spray attack.This table contains Azure Active Directory sign-in logs. Ensure that Azure Active Directory logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.initial-access, attack.credential-access, attack.t1078.004, attack.t1110
// ================================================================== 

SigninLogs
| where Status =~ "Success" and (userAgent contains "BAV2ROPC" or userAgent contains "CBAinPROD" or userAgent contains "CBAinTAR")