// Title: Successful Authentications From Countries You Do Not Operate Out Of
// Author: MikeDuddington, '@dudders1'
// Date: 2022-07-28
// Level: medium
// Description: Detect successful authentications from countries you do not operate out of.This table contains Azure Active Directory sign-in logs. Ensure that Azure Active Directory logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.initial-access, attack.credential-access, attack.t1078.004, attack.t1110
// ================================================================== 

SigninLogs
| where Status =~ "Success" and (not(Location contains "<Countries you DO operate out of e,g GB, use OR for multiple>"))