// Title: Use of Legacy Authentication Protocols
// Author: Yochana Henderson, '@Yochana-H'
// Date: 2022-06-17
// Level: high
// Description: Alert on when legacy authentication has been used on an accountThe equivalent table in Microsoft Sentinel for Azure signin logs. Make sure to have the Azure Activity Log connector enabled in Sentinel to collect these logs.
// Tags: attack.initial-access, attack.credential-access, attack.t1078.004, attack.t1110
// ================================================================== 

SigninLogs
| where ActivityDetails =~ "Sign-ins" and (ClientApp in~ ("Other client", "IMAP", "POP3", "MAPI", "SMTP", "Exchange ActiveSync", "Exchange Web Services")) and Username =~ "UPN"