// Title: Users Authenticating To Other Azure AD Tenants
// Author: MikeDuddington, '@dudders1'
// Date: 2022-06-30
// Level: medium
// Description: Detect when users in your Azure AD tenant are authenticating to other Azure AD Tenants.The equivalent table in Microsoft Sentinel for Azure signin logs. Make sure to have the Azure Activity Log connector enabled in Sentinel to collect these logs.
// Tags: attack.initial-access, attack.t1078.004
// ================================================================== 

SigninLogs
| where (HomeTenantId =~ "HomeTenantID" and Status =~ "Success") and (not(ResourceTenantId contains "HomeTenantID"))