// Title: DNS TOR Proxies
// Author: Saw Winn Naung , Azure-Sentinel
// Date: 2021-08-15
// Level: medium
// Description: Identifies IPs performing DNS lookups associated with common Tor proxies.The equivalent table in Microsoft Sentinel for DNS events. Ensure that the necessary connectors are set up to collect Zeek logs and map them to the DnsEvents table.
// Tags: attack.exfiltration, attack.t1048
// ================================================================== 

DnsEvents
| where query in~ ("tor2web.org", "tor2web.com", "torlink.co", "onion.to", "onion.ink", "onion.cab", "onion.nu", "onion.link", "onion.it", "onion.city", "onion.direct", "onion.top", "onion.casa", "onion.plus", "onion.rip", "onion.dog", "tor2web.fi", "tor2web.blutmagie.de", "onion.sh", "onion.lu", "onion.pet", "t2w.pw", "tor2web.ae.org", "tor2web.io", "tor2web.xyz", "onion.lt", "s1.tor-gateways.de", "s2.tor-gateways.de", "s3.tor-gateways.de", "s4.tor-gateways.de", "s5.tor-gateways.de", "hiddenservice.net")