// Title: Potential DLL Sideloading Of MsCorSvc.DLL
// Author: Wietze Beukema
// Date: 2024-07-11
// Level: medium
// Description: Detects potential DLL sideloading of "mscorsvc.dll".
// Tags: attack.defense-evasion, attack.t1574.002
// ================================================================== 

DeviceImageLoadEvents
| where FolderPath endswith "\\mscorsvc.dll" and (not((FolderPath startswith "C:\\Windows\\Microsoft.NET\\Framework\\" or FolderPath startswith "C:\\Windows\\Microsoft.NET\\Framework64\\" or FolderPath startswith "C:\\Windows\\WinSxS\\")))