// Title: HackTool - LittleCorporal Generated Maldoc Injection
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-09
// Level: high
// Description: Detects the process injection of a LittleCorporal generated Maldoc.This table contains information about process creation events in Windows. To query this table in Microsoft Sentinel, ensure that you have the necessary data connectors set up to collect process access logs from Windows machines.
// Tags: attack.execution, attack.t1204.002, attack.t1055.003
// ================================================================== 

ProcessCreationEvents
| where (CallTrace contains ":\\Windows\\Microsoft.NET\\Framework64\\v2." and CallTrace contains "UNKNOWN") and InitiatingProcessFolderPath endswith "\\winword.exe"