// Title: Change to Authentication Method
// Author: AlertIQ
// Date: 2021-10-10
// Level: medium
// Description: Change to authentication method could be an indicator of an attacker adding an auth method to the account so they can have continued access.This table contains Azure activity logs, including audit logs. Ensure that Azure Diagnostics logs are enabled for the Azure service in question to populate this table.
// Tags: attack.credential-access, attack.t1556, attack.persistence, attack.defense-evasion, attack.t1098
// ================================================================== 

AzureActivity
| where Category =~ "UserManagement" and LoggedByService =~ "Authentication Methods" and OperationName =~ "User registered security info"