// Title: Possible Shadow Credentials Added
// Author: Nasreddine Bencherchali (Nextron Systems), Elastic (idea)
// Date: 2022-10-17
// Level: high
// Description: Detects possible addition of shadow credentials to an active directory object.This table contains security-related events, including the event IDs mentioned in the logsource section. Make sure to have the necessary security data connectors enabled in Microsoft Sentinel to ingest these events.
// Tags: attack.credential-access, attack.t1556
// ================================================================== 

SecurityEvent
| where AttributeLDAPDisplayName =~ "msDS-KeyCredentialLink"