// Title: Password Protected ZIP File Opened (Suspicious Filenames)
// Author: Florian Roth (Nextron Systems)
// Date: 2022-05-09
// Level: high
// Description: Detects the extraction of password protected ZIP archives with suspicious file names. See the filename variable for more details on which file has been opened.The SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. To have this table present, ensure that you have the necessary connectors or data sources configured in Sentinel to collect security events from Windows machines.
// Tags: attack.command-and-control, attack.defense-evasion, attack.t1027, attack.t1105, attack.t1036
// ================================================================== 

SecurityEvent
| where TargetName contains "Microsoft_Windows_Shell_ZipFolder:filename" and (TargetName contains "invoice" or TargetName contains "new order" or TargetName contains "rechnung" or TargetName contains "factura" or TargetName contains "delivery" or TargetName contains "purchase" or TargetName contains "order" or TargetName contains "payment")