// Title: Suspicious FromBase64String Usage On Gzip Archive - Process Creation
// Author: frack113
// Date: 2022-12-23
// Level: medium
// Description: Detects attempts of decoding a base64 Gzip archive via PowerShell. This technique is often used as a method to load malicious content into memory afterward.
// Tags: attack.command-and-control, attack.t1132.001
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "FromBase64String" and ProcessCommandLine contains "MemoryStream" and ProcessCommandLine contains "H4sI"