// Title: Microsoft Excel Add-In Loaded
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-12
// Level: low
// Description: Detects Microsoft Excel loading an Add-In (.xll) file
// Tags: attack.execution, attack.t1204.002, detection.threat-hunting
// ================================================================== 

DeviceImageLoadEvents
| where FolderPath endswith ".xll" and InitiatingProcessFolderPath endswith "\\excel.exe"