// Title: HackTool - Dumpert Process Dumper Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2020-02-04
// Level: critical
// Description: Detects the use of Dumpert process dumper, which dumps the lsass.exe process memory
// Tags: attack.credential-access, attack.t1003.001
// ================================================================== 

DeviceProcessEvents
| where MD5 startswith "09D278F9DE118EF09163C6140255C690" or ProcessCommandLine contains "Dumpert.dll"