// Title: Logging Configuration Changes on Linux Host
// Author: Mikhail Larin, oscd.community
// Date: 2019-10-25
// Level: high
// Description: Detect changes of syslog daemons configuration filesThe SecurityEvent table in Microsoft Sentinel contains security-related events from various sources, including audit logs. To have Linux audit logs available in the SecurityEvent table, you need to ensure that the Linux machines are onboarded to Sentinel and have the necessary data connectors or agents installed to collect and send the audit logs to Sentinel.
// Tags: attack.defense-evasion, attack.t1562.006
// ================================================================== 

SecurityEvent
| where (name in~ ("/etc/syslog.conf", "/etc/rsyslog.conf", "/etc/syslog-ng/syslog-ng.conf")) and type =~ "PATH"