// Title: Okta User Session Start Via An Anonymising Proxy Service
// Author: kelnage
// Date: 2023-09-07
// Level: high
// Description: Detects when an Okta user session starts where the user is behind an anonymising proxy service.This table contains Okta sign-in logs. To have this table present in Microsoft Sentinel, you need to ensure that Okta logs are being forwarded to Sentinel and that the Okta connector is properly configured.
// Tags: attack.defense-evasion, attack.t1562.006
// ================================================================== 

OktaSignInLogs
| where eventtype =~ "user.session.start" and 'securitycontext.isproxy' =~ "true"