// Title: AWS EC2 VM Export Failure
// Author: Diogo Braz
// Date: 2020-04-16
// Level: low
// Description: An attempt to export an AWS EC2 instance has been detected. A VM Export might indicate an attempt to extract information from an instance.The equivalent table in Microsoft Sentinel for AWS CloudTrail logs. Make sure to have the AWS CloudTrail connector set up in Sentinel to collect and store these logs.
// Tags: attack.collection, attack.t1005, attack.exfiltration, attack.t1537
// ================================================================== 

CloudTrail
| where (eventName =~ "CreateInstanceExportTask" and eventSource =~ "ec2.amazonaws.com") and (not((errorMessage startswith "" or errorCode startswith "" or responseElements contains "Failure")))