// Title: Zip A Folder With PowerShell For Staging In Temp - PowerShell
// Author: Nasreddine Bencherchali (Nextron Systems), frack113
// Date: 2021-07-20
// Level: medium
// Description: Detects PowerShell scripts that make use of the "Compress-Archive" Cmdlet in order to compress folders and files where the output is stored in a potentially suspicious location that is used often by malware for exfiltration.
// An adversary might compress data (e.g., sensitive documents) that is collected prior to exfiltration in order to make it portable and minimize the amount of data sent over the network.
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which can include PowerShell activity. Make sure to have the necessary connectors or data sources configured in Sentinel to collect Windows security event logs.
// Tags: attack.collection, attack.t1074.001
// ================================================================== 

SecurityEvent
| where (Data contains "Compress-Archive -Path" and Data contains "-DestinationPath $env:TEMP") or (Data contains "Compress-Archive -Path" and Data contains "-DestinationPath" and Data contains "\\AppData\\Local\\Temp\\") or (Data contains "Compress-Archive -Path" and Data contains "-DestinationPath" and Data contains ":\\Windows\\Temp\\")