// Title: Zip A Folder With PowerShell For Staging In Temp  - PowerShell Module
// Author: Nasreddine Bencherchali (Nextron Systems), frack113
// Date: 2021-07-20
// Level: medium
// Description: Detects PowerShell scripts that make use of the "Compress-Archive" Cmdlet in order to compress folders and files where the output is stored in a potentially suspicious location that is used often by malware for exfiltration.
// An adversary might compress data (e.g., sensitive documents) that is collected prior to exfiltration in order to make it portable and minimize the amount of data sent over the network.
// This table contains security-related events from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to collect data from this table.
// Tags: attack.collection, attack.t1074.001
// ================================================================== 

SecurityEvent
| where (ContextInfo contains "Compress-Archive -Path" and ContextInfo contains "-DestinationPath $env:TEMP") and (ContextInfo contains "Compress-Archive -Path" and ContextInfo contains "-DestinationPath" and ContextInfo contains "\\AppData\\Local\\Temp\\") and (ContextInfo contains "Compress-Archive -Path" and ContextInfo contains "-DestinationPath" and ContextInfo contains ":\\Windows\\Temp\\")