// Title: Credential Dumping Tools Service Execution - Security
// Author: Florian Roth (Nextron Systems), Teymur Kheirkhabarov, Daniil Yugoslavskiy, oscd.community
// Date: 2017-03-05
// Level: high
// Description: Detects well-known credential dumping tools execution via service execution eventsThis table contains security-related events, including event ID 4697. Make sure to have the Windows Security Events data connector enabled in Microsoft Sentinel to access this table.
// Tags: attack.credential-access, attack.execution, attack.t1003.001, attack.t1003.002, attack.t1003.004, attack.t1003.005, attack.t1003.006, attack.t1569.002, attack.s0005
// ================================================================== 

SecurityEvent
| where ServiceFileName contains "cachedump" or ServiceFileName contains "dumpsvc" or ServiceFileName contains "fgexec" or ServiceFileName contains "gsecdump" or ServiceFileName contains "mimidrv" or ServiceFileName contains "pwdump" or ServiceFileName contains "servpw"