// Title: Credential Dumping Attempt Via WerFault
// Author: Florian Roth (Nextron Systems)
// Date: 2012-06-27
// Level: high
// Description: Detects process LSASS memory dump using Mimikatz, NanoDump, Invoke-Mimikatz, Procdump or Taskmgr based on the CallTrace pointing to ntdll.dll, dbghelp.dll or dbgcore.dll for win10, server2016 and up.This table contains information about process creation events in Windows. To have this table present in Microsoft Sentinel, ensure that you have the necessary connectors or data sources configured to collect process access logs from Windows machines.
// Tags: attack.credential-access, attack.t1003.001, attack.s0002
// ================================================================== 

ProcessCreationEvents
| where GrantedAccess =~ "0x1FFFFF" and InitiatingProcessFolderPath endswith "\\WerFault.exe" and TargetImage endswith "\\lsass.exe"