// Title: Credential Dumping Activity By Python Based Tool
// Author: Bhabesh Raj, Jonhnathan Ribeiro
// Date: 2023-11-27
// Level: high
// Description: Detects LSASS process access for potential credential dumping by a Python-like tool such as LaZagne or Pypykatz.This table contains information about process creation events in Windows. To query this table in Microsoft Sentinel, ensure that you have the necessary data connectors enabled for Windows security logs or Sysmon logs.
// Tags: attack.credential-access, attack.t1003.001, attack.s0349
// ================================================================== 

ProcessCreationEvents
| where (CallTrace contains "python27.dll+" or (CallTrace contains "python3" and CallTrace contains ".dll+")) and (CallTrace contains "_ctypes.pyd+" and CallTrace contains ":\\Windows\\System32\\KERNELBASE.dll+" and CallTrace contains ":\\Windows\\SYSTEM32\\ntdll.dll+") and GrantedAccess =~ "0x1FFFFF" and TargetImage endswith "\\lsass.exe"