// Title: Credential Dumping Tools Service Execution - System
// Author: Florian Roth (Nextron Systems), Teymur Kheirkhabarov, Daniil Yugoslavskiy, oscd.community
// Date: 2017-03-05
// Level: high
// Description: Detects well-known credential dumping tools execution via service execution eventsThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events data connector is enabled in Sentinel to have this table available for querying.
// Tags: attack.credential-access, attack.execution, attack.t1003.001, attack.t1003.002, attack.t1003.004, attack.t1003.005, attack.t1003.006, attack.t1569.002, attack.s0005
// ================================================================== 

SecurityEvent
| where (ImagePath contains "cachedump" or ImagePath contains "dumpsvc" or ImagePath contains "fgexec" or ImagePath contains "gsecdump" or ImagePath contains "mimidrv" or ImagePath contains "pwdump" or ImagePath contains "servpw") and Provider_Name =~ "Service Control Manager"