// Title: HackTool - Credential Dumping Tools Named Pipe Created
// Author: Teymur Kheirkhabarov, oscd.community
// Date: 2019-11-01
// Level: critical
// Description: Detects well-known credential dumping tools execution via specific named pipe creationThis table contains Sysmon events, including Named Pipe Events (Event ID 17 and Event ID 18). To query this table, make sure to have Sysmon installed on the Windows machines and have the Sysmon connector configured in Microsoft Sentinel.
// Tags: attack.credential-access, attack.t1003.001, attack.t1003.002, attack.t1003.004, attack.t1003.005
// ================================================================== 

SysmonEvent
| where PipeName contains "\\cachedump" or PipeName contains "\\lsadump" or PipeName contains "\\wceservicepipe"