// Title: LSASS Access From Non System Account
// Author: Roberto Rodriguez @Cyb3rWard0g
// Date: 2019-06-20
// Level: medium
// Description: Detects potential mimikatz-like tools accessing LSASS from non system accountThe SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. To have this table present, ensure that the Windows Security events are being collected and sent to Microsoft Sentinel.
// Tags: attack.credential-access, attack.t1003.001
// ================================================================== 

SecurityEvent
| where ((AccessMask in~ ("0x100000", "0x1010", "0x1400", "0x1410", "0x1418", "0x1438", "0x143a", "0x1f0fff", "0x1f1fff", "0x1f2fff", "0x1f3fff", "0x40", "143a", "1f0fff", "1f1fff", "1f2fff", "1f3fff")) and RegistryKey endswith "\\lsass.exe") and (not(((InitiatingProcessFolderPath contains ":\\Program Files\\" or InitiatingProcessFolderPath contains ":\\Program Files (x86)\\") or SubjectUserName endswith "$" or (AccessMask =~ "0x1410" and InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\wbem\\WmiPrvSE.exe")))) and (not(InitiatingProcessFolderPath contains "\\SteamLibrary\\steamapps\\"))