// Title: Password Dumper Remote Thread in LSASS
// Author: Thomas Patzke
// Date: 2017-02-19
// Level: high
// Description: Detects password dumper activity by monitoring remote thread creation EventID 8 in combination with the lsass.exe process as TargetImage.
// The process in field Process is the malicious program. A single execution can lead to hundreds of events.
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs. To query for events related to creating remote threads, you can filter based on the EventID associated with the 'create_remote_thread' category. Make sure to have the necessary connectors and data sources configured in Sentinel to collect Windows security event logs.
// Tags: attack.credential-access, attack.s0005, attack.t1003.001
// ================================================================== 

SecurityEvent
| where StartModule =~ "" and TargetImage endswith "\\lsass.exe"