// Title: Password Dumper Activity on LSASS
// Author: sigma
// Date: 2017-02-12
// Level: high
// Description: Detects process handle on LSASS process with certain access mask and object type SAM_DOMAINThe SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. To have this table present, ensure that you have the necessary connectors and data sources configured in Sentinel to collect security events from Windows machines.
// Tags: attack.credential-access, attack.t1003.001
// ================================================================== 

SecurityEvent
| where AccessMask =~ "0x705" and InitiatingProcessFolderPath endswith "\\lsass.exe"