// Title: Potential Credential Dumping Activity Via LSASS
// Author: Samir Bousseaden, Michael Haag
// Date: 2019-04-03
// Level: medium
// Description: Detects process access requests to the LSASS process with specific call trace calls and access masks.
// This behaviour is expressed by many credential dumping tools such as Mimikatz, NanoDump, Invoke-Mimikatz, Procdump and even the Taskmgr dumping feature.
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would likely include process access events. Ensure that the Windows Security events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.credential-access, attack.t1003.001, attack.s0002
// ================================================================== 

SecurityEvent
| where ((CallTrace contains "dbgcore.dll" or CallTrace contains "dbghelp.dll" or CallTrace contains "kernel32.dll" or CallTrace contains "kernelbase.dll" or CallTrace contains "ntdll.dll") and (GrantedAccess contains "0x1038" or GrantedAccess contains "0x1438" or GrantedAccess contains "0x143a" or GrantedAccess contains "0x1fffff") and TargetImage endswith "\\lsass.exe") and (not((SourceUser contains "AUTHORI" or SourceUser contains "AUTORI"))) and (not((InitiatingProcessFolderPath endswith ":\\Windows\\Sysmon64.exe" or ((CallTrace contains ":\\Windows\\Temp\\asgard2-agent\\" and CallTrace contains "\\thor\\thor64.exe+" and CallTrace contains "|UNKNOWN(") and GrantedAccess =~ "0x103800"))))