// Title: Potential Credential Dumping Attempt Via PowerShell Remote Thread
// Author: oscd.community, Natalia Shornikova
// Date: 2020-10-06
// Level: high
// Description: Detects remote thread creation by PowerShell processes into "lsass.exe"The SecurityEvent table in Microsoft Sentinel contains Windows security event logs. To query for events related to creating remote threads, you can filter on the EventID field for events related to process creation (EventID 4688) and look for specific details in the EventData field.
// Tags: attack.credential-access, attack.t1003.001
// ================================================================== 

SecurityEvent
| where (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") and TargetImage endswith "\\lsass.exe"