// Title: Potential Credential Dumping Via WER - Application
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-07
// Level: high
// Description: Detects Windows error reporting event where the process that crashed is lsass. This could be the cause of an intentional crash by techniques such as Lsass-Shtinkering to dump credentialThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.credential-access, attack.t1003.001
// ================================================================== 

SecurityEvent
| where AppName =~ "lsass.exe" and ExceptionCode =~ "c0000001" and Provider_Name =~ "Application Error"