// Title: Suspicious Unsigned Dbghelp/Dbgcore DLL Loaded
// Author: Perez Diego (@darkquassar), oscd.community, Ecco
// Date: 2019-10-27
// Level: high
// Description: Detects the load of dbghelp/dbgcore DLL (used to make memory dumps) by suspicious processes.
// Tools like ProcessHacker and some attacker tradecract use MiniDumpWriteDump API found in dbghelp.dll or dbgcore.dll.
// As an example, SilentTrynity C2 Framework has a module that leverages this API to dump the contents of Lsass.exe and transfer it over the network back to the attacker's machine.
// This table contains information about image loading events on Windows systems. Ensure that the Microsoft-Windows-Sysmon data connector is enabled in Sentinel to collect this type of data.
// Tags: attack.credential-access, attack.t1003.001
// ================================================================== 

ImageLoadEvents
| where (FolderPath endswith "\\dbghelp.dll" or FolderPath endswith "\\dbgcore.dll") and Signed =~ "false"