// Title: MSExchange Transport Agent Installation - Builtin
// Author: Tobias Michalski (Nextron Systems)
// Date: 2021-06-08
// Level: medium
// Description: Detects the Installation of a Exchange Transport AgentThis table contains logs related to Microsoft Exchange management activities in Microsoft Sentinel. Ensure that the Microsoft 365 Defender connector is configured and collecting data from the Microsoft Exchange service to have this table available for querying.
// Tags: attack.persistence, attack.t1505.002
// ================================================================== 

OfficeActivity
| where "Install-TransportAgent"