// Title: Cisco Show Commands Input
// Author: Austin Clark
// Date: 2019-08-11
// Level: medium
// Description: See what commands are being input into the device by other people, full credentials can be in the historyThis table contains authentication logs for Cisco AAA service. Ensure that the Cisco Security Extension is installed in Microsoft Sentinel to have access to this table.
// Tags: attack.credential-access, attack.t1552.003
// ================================================================== 

Cisco_AAA_AuthenticationLogs
| where "show history" or "show history all" or "show logging"