// Title: Arbitrary Command Execution Using WSL
// Author: oscd.community, Zach Stanford @svch0st, Nasreddine Bencherchali (Nextron Systems)
// Date: 2020-10-05
// Level: medium
// Description: Detects potential abuse of Windows Subsystem for Linux (WSL) binary as a Living of the Land binary in order to execute arbitrary Linux or Windows commands.
// 
// Tags: attack.execution, attack.defense-evasion, attack.t1218, attack.t1202, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where ((ProcessCommandLine contains " -e " or ProcessCommandLine contains " --exec" or ProcessCommandLine contains " --system" or ProcessCommandLine contains " --shell-type " or ProcessCommandLine contains " /mnt/c" or ProcessCommandLine contains " --user root" or ProcessCommandLine contains " -u root" or ProcessCommandLine contains "--debug-shell") and (FolderPath endswith "\\wsl.exe" or ProcessVersionInfoOriginalFileName =~ "wsl.exe")) and (not(((ProcessCommandLine contains " -d " and ProcessCommandLine contains " -e kill ") and InitiatingProcessFolderPath endswith "\\cmd.exe")))