// Title: Cleartext Protocol Usage
// Author: Alexandr Yampolskyi, SOC Prime, Tim Shelton
// Date: 2019-03-26
// Level: low
// Description: Ensure that all account usernames and authentication credentials are transmitted across networks using encrypted channels.
// Ensure that an encryption is used for all sensitive information in transit. Ensure that an encrypted channels is used for all administrative account access.
// This table contains firewall logs. Ensure that the appropriate connectors are set up in Microsoft Sentinel to collect firewall logs.
// Tags: attack.credential-access
// ================================================================== 

FirewallLog
| where (dst_port in~ ("8080", "21", "80", "23", "50000", "1521", "27017", "3306", "1433", "11211", "15672", "5900", "5901", "5902", "5903", "5904")) and ((action in~ ("forward", "accept", "2")) or blocked =~ "false")