// Title: Cleartext Protocol Usage Via Netflow
// Author: Alexandr Yampolskyi, SOC Prime
// Date: 2019-03-26
// Level: low
// Description: Ensure that all account usernames and authentication credentials are transmitted across networks using encrypted channels
// Ensure that an encryption is used for all sensitive information in transit.
// Ensure that an encrypted channels is used for all administrative account access.
// This table contains NetFlow data and can be queried in Kusto Query Language (KQL) in Microsoft Sentinel. Ensure that NetFlow data is being collected and ingested into Sentinel for this table to be available.
// Tags: attack.credential-access
// ================================================================== 

NetFlow
| where 'destination.port' in~ ("8080", "21", "80", "23", "50000", "1521", "27017", "1433", "11211", "3306", "15672", "5900", "5901", "5902", "5903", "5904")