// Title: Google Cloud Kubernetes Secrets Modified or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-08-09
// Level: medium
// Description: Identifies when the Secrets are Modified or Deleted.This table contains GCP audit logs. Ensure that the GCP connector is set up in Microsoft Sentinel to collect logs from the GCP service.
// Tags: attack.credential-access
// ================================================================== 

GCPAuditLogs
| where ('gcp.audit.method_name' contains "io.k8s.core.v" and 'gcp.audit.method_name' contains ".secrets.create") or ('gcp.audit.method_name' contains "io.k8s.core.v" and 'gcp.audit.method_name' contains ".secrets.update") or ('gcp.audit.method_name' contains "io.k8s.core.v" and 'gcp.audit.method_name' contains ".secrets.patch") or ('gcp.audit.method_name' contains "io.k8s.core.v" and 'gcp.audit.method_name' contains ".secrets.delete")