// Title: Kubernetes Secrets Modified or Deleted
// Author: kelnage
// Date: 2024-07-11
// Level: medium
// Description: Detects when Kubernetes Secrets are Modified or Deleted.
// The KubeEvents table in Microsoft Sentinel contains Kubernetes audit logs. To have this table present, ensure that you have the necessary connectors or data sources configured in Sentinel to collect Kubernetes audit logs.
// Tags: attack.credential-access
// ================================================================== 

KubeEvents
| where 'objectRef.resource' =~ "secrets" and (verb in~ ("create", "delete", "patch", "replace", "update"))