// Title: Multi Factor Authentication Disabled For User Account
// Author: Harjot Singh (@cyb3rjy0t)
// Date: 2024-08-21
// Level: medium
// Description: Detects changes to the "StrongAuthenticationRequirement" value, where the state is set to "0" or "Disabled".
// Threat actors were seen disabling multi factor authentication for users in order to maintain or achieve access to the account. Also see in SIM Swap attacks.
// This table contains Azure audit logs, which can be queried to retrieve information about TargetResources. Make sure to have Azure Activity logs enabled in your Sentinel workspace.
// Tags: attack.credential-access, attack.persistence
// ================================================================== 

AzureActivity
| where Category =~ "UserManagement" and LoggedByService =~ "Core Directory" and OperationName =~ "Update user" and 'TargetResources.ModifiedProperties.DisplayName' =~ "StrongAuthenticationRequirement" and 'TargetResources.ModifiedProperties.NewValue' contains "State\":0"