// Title: Remote Thread Creation In Mstsc.Exe From Suspicious Location
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-07-28
// Level: high
// Description: Detects remote thread creation in the "mstsc.exe" process by a process located in a potentially suspicious location.
// This technique is often used by attackers in order to hook some APIs used by DLLs loaded by "mstsc.exe" during RDP authentications in order to steal credentials.
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs. To query for events related to creating remote threads, you can filter on the EventID and other relevant fields.
// Tags: attack.credential-access
// ================================================================== 

SecurityEvent
| where (InitiatingProcessFolderPath contains ":\\Temp\\" or InitiatingProcessFolderPath contains ":\\Users\\Public\\" or InitiatingProcessFolderPath contains ":\\Windows\\PerfLogs\\" or InitiatingProcessFolderPath contains ":\\Windows\\Tasks\\" or InitiatingProcessFolderPath contains ":\\Windows\\Temp\\" or InitiatingProcessFolderPath contains "\\AppData\\Local\\Temp\\") and TargetImage endswith "\\mstsc.exe"