// Title: Veeam Backup Servers Credential Dumping Script Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-04
// Level: high
// Description: Detects execution of a PowerShell script that contains calls to the "Veeam.Backup" class, in order to dump stored credentials.This table contains security-related events from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to collect this data.
// Tags: attack.credential-access
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "[Credentials]" and ScriptBlockText contains "[Veeam.Backup.Common.ProtectedStorage]::GetLocalString" and ScriptBlockText contains "Invoke-Sqlcmd" and ScriptBlockText contains "Veeam Backup and Replication"