// Title: Scheduled Task Created - Registry
// Author: Center for Threat Informed Defense (CTID) Summiting the Pyramid Team
// Date: 2023-09-27
// Level: low
// Description: Detects the creation of a scheduled task via Registry keys.
// Tags: attack.execution, attack.persistence, attack.privilege-escalation, attack.s0111, attack.t1053.005, car.2013-08-001, detection.threat-hunting
// ================================================================== 

DeviceRegistryEvents
| where RegistryKey endswith "\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tasks*" or RegistryKey endswith "\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tree*"