// Title: Binary Padding - Linux
// Author: Igor Fits, oscd.community
// Date: 2020-10-13
// Level: high
// Description: Adversaries may use binary padding to add junk data and change the on-disk representation of malware.
// This rule detect using dd and truncate to add a junk data to file.
// The LinuxAudit table in Microsoft Sentinel contains audit logs from Linux systems. To have this table present, ensure that the Linux machines are onboarded to Sentinel and the necessary data connectors are configured to collect audit logs.
// Tags: attack.defense-evasion, attack.t1027.001
// ================================================================== 

LinuxAudit
| where type =~ "EXECVE" and (("truncate" and "-s") or (("dd" and "if=") and (not("of="))))