// Title: Failed Code Integrity Checks
// Author: Thomas Patzke
// Date: 2019-12-03
// Level: informational
// Description: Detects code integrity failures such as missing page hashes or corrupted drivers due unauthorized modification. This could be a sign of tampered binaries.
// The SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. Make sure to have the Windows Security Events connector enabled in Sentinel to populate this table.
// Tags: attack.defense-evasion, attack.t1027.001
// ================================================================== 

SecurityEvent
| where not(((param1 contains "\\CSFalconServiceUninstallTool_" or param1 contains "\\Program Files\\CrowdStrike\\" or param1 contains "\\System32\\drivers\\CrowdStrike\\" or param1 contains "\\Windows\\System32\\ScriptControl64_") or param1 contains "\\Program Files\\Sophos\\"))