// Description: This query was originally published in the threat analytics report, EvilQuest signals the rise of Mac ransomware.
// As of the time of this writing (October 2020), ransomware designed to target macOS is relatively rare. EvilQuest is one of the few examples of this kind of malware on the platform.
// The query below can detect the creation of a ransom note according to the typical methods of EvilQuest operators. The command the query searches for is associated with, but not definitely indicative of, EvilQuest infections.
// Other queries related to EvilQuest ransomware can be found under the See also section below.
// Required Connectors: MicrosoftThreatProtection (Types: DeviceFileEvents, DeviceProcessEvents)

union DeviceFileEvents, DeviceProcessEvents  
| where Timestamp >= ago(7d)  
| where ProcessCommandLine has "say \\\"Your files are encrypted\\\" waiting until completion false"