// Title: Azure Keyvault Secrets Modified or Deleted
// Author: Austin Songer @austinsonger
// Date: 2021-08-16
// Level: medium
// Description: Identifies when secrets are modified or deleted in Azure.This table contains Azure Activity Logs data. Ensure that Azure Activity Logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.impact, attack.credential-access, attack.t1552, attack.t1552.001
// ================================================================== 

AzureActivityLogs
| where operationName in~ ("MICROSOFT.KEYVAULT/VAULTS/SECRETS/WRITE", "MICROSOFT.KEYVAULT/VAULTS/SECRETS/DELETE", "MICROSOFT.KEYVAULT/VAULTS/SECRETS/BACKUP/ACTION", "MICROSOFT.KEYVAULT/VAULTS/SECRETS/PURGE/ACTION", "MICROSOFT.KEYVAULT/VAULTS/SECRETS/UPDATE/ACTION", "MICROSOFT.KEYVAULT/VAULTS/SECRETS/RECOVER/ACTION", "MICROSOFT.KEYVAULT/VAULTS/SECRETS/RESTORE/ACTION", "MICROSOFT.KEYVAULT/VAULTS/SECRETS/SETSECRET/ACTION")