// Title: GUI Input Capture - macOS
// Author: remotephone, oscd.community
// Date: 2020-10-13
// Level: low
// Description: Detects attempts to use system dialog prompts to capture user credentials
// Tags: attack.credential-access, attack.t1056.002
// ================================================================== 

DeviceProcessEvents
| where FolderPath =~ "/usr/sbin/osascript" and (ProcessCommandLine contains "-e" and ProcessCommandLine contains "display" and ProcessCommandLine contains "dialog" and ProcessCommandLine contains "answer") and (ProcessCommandLine contains "admin" or ProcessCommandLine contains "administrator" or ProcessCommandLine contains "authenticate" or ProcessCommandLine contains "authentication" or ProcessCommandLine contains "credentials" or ProcessCommandLine contains "pass" or ProcessCommandLine contains "password" or ProcessCommandLine contains "unlock")