// Title: Eventlog Cleared
// Author: Florian Roth (Nextron Systems)
// Date: 2017-01-10
// Level: medium
// Description: One of the Windows Eventlogs has been cleared. e.g. caused by "wevtutil cl" command executionThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1070.001, car.2016-04-002
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Microsoft-Windows-Eventlog" and (not((Channel in~ ("Microsoft-Windows-PowerShell/Operational", "Microsoft-Windows-Sysmon/Operational", "PowerShellCore/Operational", "Security", "System", "Windows PowerShell"))))