// Title: Security Eventlog Cleared
// Author: Florian Roth (Nextron Systems)
// Date: 2017-01-10
// Level: high
// Description: One of the Windows Eventlogs has been cleared. e.g. caused by "wevtutil cl" command executionThe SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. To query this table, ensure that you have the necessary data connectors set up in Sentinel to collect security events from Windows machines.
// Tags: attack.defense-evasion, attack.t1070.001, car.2016-04-002
// ================================================================== 

SecurityEvent
| where Provider_Name in~ ("Microsoft-Windows-Eventlog", "Security")