// Title: Suspicious Eventlog Clear
// Author: Nasreddine Bencherchali (Nextron Systems), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2022-09-12
// Level: medium
// Description: Detects usage of known powershell cmdlets such as "Clear-EventLog" to clear the Windows event logsThis table contains security-related events, including PowerShell script execution events. To query for PowerShell script execution events, filter on EventID 4104.
// Tags: attack.defense-evasion, attack.t1070.001
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "Clear-EventLog " or ScriptBlockText contains "Remove-EventLog " or ScriptBlockText contains "Limit-EventLog " or ScriptBlockText contains "Clear-WinEvent ") or (ScriptBlockText contains "Eventing.Reader.EventLogSession" and ScriptBlockText contains "ClearLog") or (ScriptBlockText contains "Diagnostics.EventLog" or ScriptBlockText contains "Clear")