// Title: DMP/HDMP File Creation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-07
// Level: low
// Description: Detects the creation of a file with the ".dmp"/".hdmp" extension. Often created by software during a crash. Memory dumps can sometimes contain sensitive information such as credentials. It's best to determine the source of the crash.
// Tags: attack.defense-evasion, detection.threat-hunting
// ================================================================== 

DeviceFileEvents
| where FolderPath endswith ".dmp" or FolderPath endswith ".dump" or FolderPath endswith ".hdmp"