// Title: CMSTP Execution Process Access
// Author: Nik Seetharaman
// Date: 2018-07-16
// Level: high
// Description: Detects various indicators of Microsoft Connection Manager Profile Installer executionThe SecurityEvent table in Microsoft Sentinel contains process access logs for Windows systems. Ensure that the Windows Security events are being collected and ingested into Sentinel to query this table.
// Tags: attack.defense-evasion, attack.t1218.003, attack.execution, attack.t1559.001, attack.g0069, attack.g0080, car.2019-04-001
// ================================================================== 

SecurityEvent
| where CallTrace contains "cmlua.dll"