// Title: Bypass UAC Using DelegateExecute
// Author: frack113
// Date: 2022-01-05
// Level: high
// Description: Bypasses User Account Control using a fileless method
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.t1548.002
// ================================================================== 

DeviceRegistryEvents
| where RegistryValueData =~ "(Empty)" and RegistryKey endswith "\\open\\command\\DelegateExecute"