// Title: Potential UAC Bypass Via Sdclt.EXE
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-05-02
// Level: medium
// Description: A General detection for sdclt being spawned as an elevated process. This could be an indicator of sdclt being used for bypass UAC techniques.
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.t1548.002
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "sdclt.exe" and (ProcessIntegrityLevel in~ ("High", "S-1-16-12288"))