// Title: Okta Admin Role Assigned to an User or Group
// Author: Austin Songer @austinsonger
// Date: 2021-09-12
// Level: medium
// Description: Detects when an the Administrator role is assigned to an user or group.This table contains Okta sign-in logs. To have this table present in Microsoft Sentinel, ensure that you have the Okta connector configured and collecting data from the Okta service.
// Tags: attack.persistence, attack.t1098.003
// ================================================================== 

OktaSignInLogs
| where eventtype in~ ("group.privilege.grant", "user.account.privilege.grant")