// Title: Local System Accounts Discovery - MacOs
// Author: Alejandro Ortuno, oscd.community
// Date: 2020-10-08
// Level: low
// Description: Detects enumeration of local systeam accounts on MacOS
// Tags: attack.discovery, attack.t1087.001
// ================================================================== 

DeviceProcessEvents
| where ((ProcessCommandLine contains "list" and ProcessCommandLine contains "/users") and FolderPath endswith "/dscl") or ((ProcessCommandLine contains "-q" and ProcessCommandLine contains "user") and FolderPath endswith "/dscacheutil") or ProcessCommandLine contains "'x:0:'" or ((ProcessCommandLine contains "/etc/passwd" or ProcessCommandLine contains "/etc/sudoers") and FolderPath endswith "/cat") or FolderPath endswith "/id" or (ProcessCommandLine contains "-u" and FolderPath endswith "/lsof")