// Title: PowerShell Script Change Permission Via Set-Acl - PsScript
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-07-18
// Level: low
// Description: Detects PowerShell scripts set ACL to of a file or a folderThis table contains security event logs from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to collect this data.
// Tags: attack.defense-evasion, attack.t1222
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Set-Acl " and ScriptBlockText contains "-AclObject " and ScriptBlockText contains "-Path "