// Title: Mimikatz DC Sync
// Author: Benjamin Delpy, Florian Roth (Nextron Systems), Scott Dermott, Sorina Ionescu
// Date: 2018-06-03
// Level: high
// Description: Detects Mimikatz DC sync security eventsThe SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. Make sure to have the Windows Security Events connector enabled in Sentinel to populate this table.
// Tags: attack.credential-access, attack.s0002, attack.t1003.006
// ================================================================== 

SecurityEvent
| where (AccessMask =~ "0x100" and (Properties contains "Replicating Directory Changes All" or Properties contains "1131f6ad-9c07-11d1-f79f-00c04fc2dcd2" or Properties contains "1131f6aa-9c07-11d1-f79f-00c04fc2dcd2" or Properties contains "9923a32a-3607-11d2-b9be-0000f87a36b2" or Properties contains "89e95b76-444d-4c62-991a-0facbeda640c")) and (not((SubjectDomainName =~ "Window Manager" or (SubjectUserName startswith "NT AUT" or SubjectUserName startswith "MSOL_") or SubjectUserName endswith "$")))