// Title: Suspicious Get-ADReplAccount
// Author: frack113
// Date: 2022-02-06
// Level: medium
// Description: The DSInternals PowerShell Module exposes several internal features of Active Directory and Azure Active Directory.
// These include FIDO2 and NGC key auditing, offline ntds.dit file manipulation, password auditing, DC recovery from IFM backups and password hash calculation.
// This table contains Windows security event logs, including script block logging events. Enable the Microsoft Monitoring Agent on Windows machines and configure the appropriate data connectors in Sentinel to collect and ingest these logs.
// Tags: attack.credential-access, attack.t1003.006
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Get-ADReplAccount" and ScriptBlockText contains "-All " and ScriptBlockText contains "-Server "