// Title: Disabling Security Tools - Builtin
// Author: Ömer Günal, Alejandro Ortuno, oscd.community
// Date: 2020-06-17
// Level: medium
// Description: Detects disabling security toolsThe equivalent table in Microsoft Sentinel for syslog data. Ensure that the necessary connectors or data sources are configured to ingest syslog data into Sentinel for this table to be populated.
// Tags: attack.defense-evasion, attack.t1562.004
// ================================================================== 

Syslog
| where "stopping iptables" or "stopping ip6tables" or "stopping firewalld" or "stopping cbdaemon" or "stopping falcon-sensor"