// Title: Flush Iptables Ufw Chain
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-01-18
// Level: medium
// Description: Detect use of iptables to flush all firewall rules, tables and chains and allow all network traffic
// Tags: attack.defense-evasion, attack.t1562.004
// ================================================================== 

DeviceProcessEvents
| where (FolderPath endswith "/iptables" or FolderPath endswith "/xtables-legacy-multi" or FolderPath endswith "/iptables-legacy-multi" or FolderPath endswith "/ip6tables" or FolderPath endswith "/ip6tables-legacy-multi") and (ProcessCommandLine contains "-F" or ProcessCommandLine contains "-Z" or ProcessCommandLine contains "-X") and (ProcessCommandLine contains "ufw-logging-deny" or ProcessCommandLine contains "ufw-logging-allow" or ProcessCommandLine contains "ufw6-logging-deny" or ProcessCommandLine contains "ufw6-logging-allow")