// Title: New Firewall Rule Added In Windows Firewall Exception List Via WmiPrvSE.EXE
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-05-10
// Level: medium
// Description: Detects the addition of a new "Allow" firewall rule by the WMI process (WmiPrvSE.EXE).
// This can occur if an attacker leverages PowerShell cmdlets such as "New-NetFirewallRule", or directly uses WMI CIM classes such as "MSFT_NetFirewallRule".
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would likely include firewall events from a Windows server. Ensure that the Windows Security Events connector is enabled in Sentinel to collect these logs.
// Tags: attack.defense-evasion, attack.t1562.004
// ================================================================== 

SecurityEvent
| where Action == 3 and ModifyingApplication endswith ":\\Windows\\System32\\wbem\\WmiPrvSE.exe"