// Title: Uncommon New Firewall Rule Added In Windows Firewall Exception List
// Author: frack113
// Date: 2022-02-19
// Level: medium
// Description: Detects when a rule has been added to the Windows Firewall exception listThe SecurityEvent table in Microsoft Sentinel contains Windows security events, which would likely include firewall logs from the 'firewall-as' service on Windows machines. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1562.004
// ================================================================== 

SecurityEvent
| where (not((Action == 2 or (ApplicationPath contains "C:\\PerfLogs\\" or ApplicationPath contains "C:\\Temp\\" or ApplicationPath contains "C:\\Tmp\\" or ApplicationPath contains "C:\\Users\\Public\\" or ApplicationPath contains "C:\\Windows\\Tasks\\" or ApplicationPath contains "C:\\Windows\\Temp\\" or ApplicationPath contains "\\AppData\\Local\\Temp\\") or (ApplicationPath startswith "C:\\Program Files (x86)\\" or ApplicationPath startswith "C:\\Program Files\\" or ApplicationPath startswith "C:\\Windows\\System32\\" or ApplicationPath startswith "C:\\Windows\\SysWOW64\\" or ApplicationPath startswith "C:\\Windows\\WinSxS\\") or isnull(ApplicationPath)))) and (not(((ModifyingApplication endswith "\\MsMpEng.exe" and ModifyingApplication startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\") or (ApplicationPath =~ "" and (ModifyingApplication in~ ("C:\\Windows\\System32\\svchost.exe", "C:\\Windows\\System32\\dllhost.exe"))))))