// Title: Driver/DLL Installation Via Odbcconf.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-22
// Level: medium
// Description: Detects execution of "odbcconf" with "INSTALLDRIVER" which installs a new ODBC driver. Attackers abuse this to install and run malicious DLLs.
// Tags: attack.defense-evasion, attack.t1218.008
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "INSTALLDRIVER " and ProcessCommandLine contains ".dll") and (FolderPath endswith "\\odbcconf.exe" or ProcessVersionInfoOriginalFileName =~ "odbcconf.exe")