// Title: Suspicious Driver/DLL Installation Via Odbcconf.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-23
// Level: high
// Description: Detects execution of "odbcconf" with the "INSTALLDRIVER" action where the driver doesn't contain a ".dll" extension. This is often used as a defense evasion method.
// Tags: attack.defense-evasion, attack.t1218.008
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "INSTALLDRIVER " and (FolderPath endswith "\\odbcconf.exe" or ProcessVersionInfoOriginalFileName =~ "odbcconf.exe")) and (not(ProcessCommandLine contains ".dll"))