// Title: Malicious Usage Of IMDS Credentials Outside Of AWS Infrastructure
// Author: jamesc-grafana
// Date: 2024-07-11
// Level: high
// Description: Detects when an instance identity has taken an action that isn't inside SSM.
// This can indicate that a compromised EC2 instance is being used as a pivot point.
// The equivalent table in Microsoft Sentinel for AWS CloudTrail logs. Ensure that the AWS CloudTrail connector is set up in Sentinel to collect and ingest these logs.
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.t1078, attack.t1078.002
// ================================================================== 

CloudTrail
| where 'userIdentity.arn' matches regex ".+:assumed-role/aws:.+" and (not((eventSource =~ "ssm.amazonaws.com" or eventName =~ "RegisterManagedInstance" or sourceIPAddress =~ "AWS Internal")))