// Title: Python Path Configuration File Creation - MacOS
// Author: Andreas Braathen (mnemonic.io)
// Date: 2024-04-25
// Level: medium
// Description: Detects creation of a Python path configuration file (.pth) in Python library folders, which can be maliciously abused for code execution and persistence.
// Modules referenced by these files are run at every Python startup (v3.5+), regardless of whether the module is imported by the calling script.
// Default paths are '\lib\site-packages\*.pth' (Windows) and '/lib/pythonX.Y/site-packages/*.pth' (Unix and macOS).
// 
// Tags: attack.execution, attack.t1059.006, detection.threat-hunting
// ================================================================== 

DeviceFileEvents
| where FolderPath endswith ".pth" and FolderPath matches regex "(?i)/lib/python3\\.([5-9]|[0-9]{2})/site-packages/"