// Title: Touch Suspicious Service File
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-01-11
// Level: medium
// Description: Detects usage of the "touch" process in service file.
// Tags: attack.defense-evasion, attack.t1070.006
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains " -t " and ProcessCommandLine endswith ".service" and FolderPath endswith "/touch"