// Title: Meterpreter or Cobalt Strike Getsystem Service Installation - System
// Author: Teymur Kheirkhabarov, Ecco, Florian Roth (Nextron Systems)
// Date: 2019-10-26
// Level: high
// Description: Detects the use of getsystem Meterpreter/Cobalt Strike command by detecting a specific service installationThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events data connector is enabled in Sentinel to have this table available for querying.
// Tags: attack.privilege-escalation, attack.t1134.001, attack.t1134.002
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager" and (((ImagePath contains "cmd" or ImagePath contains "%COMSPEC%") and (ImagePath contains "/c" and ImagePath contains "echo" and ImagePath contains "\\pipe\\")) or (ImagePath contains "rundll32" and ImagePath contains ".dll,a" and ImagePath contains "/p:") or ImagePath startswith "\\\\127.0.0.1\\ADMIN$\\")