// Title: Root Certificate Installed - PowerShell
// Author: oscd.community, @redcanary, Zach Stanford @svch0st
// Date: 2020-10-10
// Level: medium
// Description: Adversaries may install a root certificate on a compromised system to avoid warnings when connecting to adversary controlled web servers.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. To ensure this table is populated with the necessary logs, make sure to have the appropriate data connectors and log sources configured in Sentinel to collect Windows security event logs.
// Tags: attack.defense-evasion, attack.t1553.004
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "Move-Item" and ScriptBlockText contains "Cert:\\LocalMachine\\Root") or (ScriptBlockText contains "Import-Certificate" and ScriptBlockText contains "Cert:\\LocalMachine\\Root")