// Title: Chmod Suspicious Directory
// Author: Christopher Peacock @SecurePeacock, SCYTHE @scythe_io
// Date: 2022-06-03
// Level: medium
// Description: Detects chmod targeting files in abnormal directory paths.
// Tags: attack.defense-evasion, attack.t1222.002
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "/tmp/" or ProcessCommandLine contains "/.Library/" or ProcessCommandLine contains "/etc/" or ProcessCommandLine contains "/opt/") and FolderPath endswith "/chmod"