// Title: CodePage Modification Via MODE.COM
// Author: Nasreddine Bencherchali (Nextron Systems), Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2024-01-19
// Level: low
// Description: Detects a CodePage modification using the "mode.com" utility.
// This behavior has been used by threat actors behind Dharma ransomware.
// 
// Tags: attack.defense-evasion, attack.t1036, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains " con " and ProcessCommandLine contains " cp " and ProcessCommandLine contains " select=") and (FolderPath endswith "\\mode.com" or ProcessVersionInfoOriginalFileName =~ "MODE.COM")