// Title: Github New Secret Created
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2023-01-20
// Level: low
// Description: Detects when a user creates action secret for the organization, environment, codespaces or repository.This table contains audit logs for the Github service. Make sure to have the Github connector installed in Microsoft Sentinel to access this table.
// Tags: attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.initial-access, attack.t1078.004
// ================================================================== 

GithubAuditLogs
| where action in~ ("codespaces.create_an_org_secret", "environment.create_actions_secret", "org.create_actions_secret", "repo.create_actions_secret")