// Title: Sign-ins by Unknown Devices
// Author: Michael Epping, '@mepples21'
// Date: 2022-06-28
// Level: low
// Description: Monitor and alert for Sign-ins by unknown devices from non-Trusted locations.The equivalent table in Microsoft Sentinel for Azure sign-in logs. Ensure that Azure Active Directory logs are being ingested into Sentinel to have this table available.
// Tags: attack.defense-evasion, attack.t1078.004
// ================================================================== 

SigninLogs
| where AuthenticationRequirement =~ "singleFactorAuthentication" and 'DeviceDetail.deviceId' =~ "" and NetworkLocationDetails =~ "[]" and ResultType == 0