// Title: Sign-ins from Non-Compliant Devices
// Author: Michael Epping, '@mepples21'
// Date: 2022-06-28
// Level: high
// Description: Monitor and alert for sign-ins where the device was non-compliant.The equivalent table in Microsoft Sentinel for Azure signin logs. Ensure that Azure Activity Logs are being ingested into Sentinel to have this table available.
// Tags: attack.defense-evasion, attack.t1078.004
// ================================================================== 

SigninLogs
| where 'DeviceDetail.isCompliant' =~ "false"