// Title: Users Added to Global or Device Admin Roles
// Author: Michael Epping, '@mepples21'
// Date: 2022-06-28
// Level: high
// Description: Monitor and alert for users added to device admin roles.This table contains Azure activity logs, which includes audit logs. Ensure that Azure Diagnostics logs are enabled for the Azure service in question to populate this table.
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1078.004
// ================================================================== 

AzureActivity
| where Category =~ "RoleManagement" and (OperationName contains "Add" and OperationName contains "member to role") and (TargetResources contains "7698a772-787b-4ac8-901f-60d6b08affd2" or TargetResources contains "62e90394-69f5-4237-9190-012177145e10")