// Title: Bitsadmin to Uncommon IP Server Address
// Author: Florian Roth (Nextron Systems)
// Date: 2022-06-10
// Level: high
// Description: Detects Bitsadmin connections to IP addresses instead of FQDN namesThis table contains proxy logs, which can be queried to retrieve information related to proxy activity. Make sure to have the necessary connectors or data sources configured in Sentinel to collect proxy logs.
// Tags: attack.command-and-control, attack.t1071.001, attack.defense-evasion, attack.persistence, attack.t1197, attack.s0190
// ================================================================== 

ProxyLog
| where 'c-useragent' startswith "Microsoft BITS/" and (''cs-host'' endswith "1" or ''cs-host'' endswith "2" or ''cs-host'' endswith "3" or ''cs-host'' endswith "4" or ''cs-host'' endswith "5" or ''cs-host'' endswith "6" or ''cs-host'' endswith "7" or ''cs-host'' endswith "8" or ''cs-host'' endswith "9")