// Title: Change User Agents with WebRequest
// Author: frack113
// Date: 2022-01-23
// Level: medium
// Description: Adversaries may communicate using application layer protocols associated with web traffic to avoid detection/network filtering by blending in with existing traffic.
// Commands to the remote system, and often the results of those commands, will be embedded within the protocol traffic between the client and server.
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows Security events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.command-and-control, attack.t1071.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Invoke-WebRequest" and ScriptBlockText contains "-UserAgent "