// Title: Cloudflared Tunnels Related DNS Requests
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-12-20
// Level: medium
// Description: Detects DNS requests to Cloudflared tunnels domains.
// Attackers can abuse that feature to establish a reverse shell or persistence on a machine.
// The DnsEvents table in Microsoft Sentinel contains DNS query logs. Ensure that the Windows DNS events data connector is enabled in Sentinel to populate this table.
// Tags: attack.command-and-control, attack.t1071.001
// ================================================================== 

DnsEvents
| where QueryName endswith ".v2.argotunnel.com" or QueryName endswith "protocol-v2.argotunnel.com" or QueryName endswith "trycloudflare.com" or QueryName endswith "update.argotunnel.com"