// Title: Crypto Miner User Agent
// Author: Florian Roth (Nextron Systems)
// Date: 2019-10-21
// Level: high
// Description: Detects suspicious user agent strings used by crypto miners in proxy logsThis table contains proxy logs, which can be queried in Microsoft Sentinel. Make sure to have the necessary connectors or data sources configured in Sentinel to collect and ingest proxy logs.
// Tags: attack.command-and-control, attack.t1071.001
// ================================================================== 

ProxyLog
| where ''c-useragent'' startswith "XMRig " or ''c-useragent'' startswith "ccminer"