// Title: Potential Base64 Encoded User-Agent
// Author: Florian Roth (Nextron Systems), Brian Ingram (update)
// Date: 2022-07-08
// Level: medium
// Description: Detects User Agent strings that end with an equal sign, which can be a sign of base64 encoding.This table contains proxy logs. Make sure to have the necessary connectors or data sources set up in Sentinel to collect and ingest proxy logs.
// Tags: attack.command-and-control, attack.t1071.001
// ================================================================== 

ProxyLog
| where 'c-useragent' endswith "="