// Title: PwnDrp Access
// Author: Florian Roth (Nextron Systems)
// Date: 2020-04-15
// Level: critical
// Description: Detects downloads from PwnDrp web servers developed for red team testing and most likely also used for criminal activityThis table contains proxy logs, which can be queried in Microsoft Sentinel. Ensure that the necessary connectors or data sources are set up to collect proxy logs in Sentinel.
// Tags: attack.command-and-control, attack.t1071.001, attack.t1102.001, attack.t1102.003
// ================================================================== 

ProxyLog
| where 'c-uri' contains "/pwndrop/"