// Title: System Shutdown/Reboot - Linux
// Author: Igor Fits, oscd.community
// Date: 2020-10-15
// Level: informational
// Description: Adversaries may shutdown/reboot systems to interrupt access to, or aid in the destruction of, those systems.The equivalent table in Microsoft Sentinel for Linux audit logs. Ensure that the Linux machines are onboarded to Sentinel and the necessary data connectors are configured to collect audit logs from the auditd service.
// Tags: attack.impact, attack.t1529
// ================================================================== 

LinuxAuditLogs
| where type =~ "EXECVE" and (("shutdown" or "reboot" or "halt" or "poweroff") or (("init" or "telinit") and (0 or 6)))