// Title: Data Exfiltration with Wget
// Author: Pawel Mazur
// Date: 2021-11-18
// Level: medium
// Description: Detects attempts to post the file with the usage of wget utility.
// The adversary can bypass the permission restriction with the misconfigured sudo permission for wget utility which could allow them to read files like /etc/shadow.
// The table containing Linux audit logs in Microsoft Sentinel. Ensure that the Linux machines are onboarded to Sentinel and the necessary data connectors are configured to collect audit logs from the auditd service on the Linux machines.
// Tags: attack.exfiltration, attack.t1048.003
// ================================================================== 

LinuxAuditLogs
| where a0 =~ "wget" and a1 startswith "--post-file=" and type =~ "EXECVE"