// Title: Suspicious DNS Query with B64 Encoded String
// Author: Florian Roth (Nextron Systems)
// Date: 2018-05-10
// Level: medium
// Description: Detects suspicious DNS queries using base64 encodingThis table contains DNS events, which can be queried to retrieve information related to DNS activity. Ensure that the required connectors are set up to collect DNS logs in Sentinel.
// Tags: attack.exfiltration, attack.t1048.003, attack.command-and-control, attack.t1071.004
// ================================================================== 

DnsEvents
| where query contains "==."