// Title: Diskshadow Child Process Spawned
// Author: Harjot Singh @cyb3rjy0t
// Date: 2023-09-15
// Level: medium
// Description: Detects any child process spawning from "Diskshadow.exe". This could be due to executing Diskshadow in interpreter mode or script mode and using the "exec" flag to launch other applications.
// Tags: attack.defense-evasion, attack.t1218, attack.execution, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\diskshadow.exe" and (not(FolderPath endswith ":\\Windows\\System32\\WerFault.exe"))