// Title: Remote Server Service Abuse for Lateral Movement
// Author: Sagie Dulce, Dekel Paz
// Date: 2022-01-01
// Level: high
// Description: Detects remote RPC calls to possibly abuse remote encryption service via MS-EFSRThis table contains logs related to RPC Firewall activity. To have this table present in Microsoft Sentinel, ensure that RPC Firewall logs are being collected and sent to Sentinel.
// Tags: attack.lateral-movement, attack.t1569.002
// ================================================================== 

rpc_firewall_logs
| where EventLog =~ "RPCFW" and InterfaceUuid =~ "367abb81-9844-35f1-ad32-98f038001003"