// Title: Powershell Execute Batch Script
// Author: frack113
// Date: 2022-01-02
// Level: medium
// Description: Adversaries may abuse the Windows command shell for execution.
// The Windows command shell ([cmd](https://attack.mitre.org/software/S0106)) is the primary command prompt on Windows systems.
// The Windows command prompt can be used to control almost any aspect of a system, with various permission levels required for different subsets of commands.
// Batch files (ex: .bat or .cmd) also provide the shell with a list of sequential commands to run, as well as normal scripting operations such as conditionals and loops.
// Common uses of batch files include long or repetitive tasks, or the need to run the same set of commands on multiple system
// This table contains Windows security event logs, including PowerShell script block logs. Enable the necessary data connectors in Microsoft Sentinel to ingest this data.
// Tags: attack.execution, attack.t1059.003
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains ".cmd" or ScriptBlockText contains ".bat") and ScriptBlockText contains "Start-Process"