// Title: Remote Access Tool - ScreenConnect File Transfer
// Author: Ali Alwashali
// Date: 2023-10-10
// Level: low
// Description: Detects file being transferred via ScreenConnect RMMThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.execution, attack.t1059.003
// ================================================================== 

SecurityEvent
| where Data contains "Transferred files with action" and Provider_Name =~ "ScreenConnect"