// Title: Dump Credentials from Windows Credential Manager With PowerShell
// Author: frack113
// Date: 2021-12-20
// Level: medium
// Description: Adversaries may search for common password storage locations to obtain user credentials.
// Passwords are stored in several places on a system, depending on the operating system or application holding the credentials.
// This table contains security-related events, including PowerShell script execution events. Ensure that the necessary connectors are set up to collect Windows security event logs in Sentinel.
// Tags: attack.credential-access, attack.t1555
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "Get-PasswordVaultCredentials" or ScriptBlockText contains "Get-CredManCreds") or (ScriptBlockText contains "New-Object" and ScriptBlockText contains "Windows.Security.Credentials.PasswordVault") or (ScriptBlockText contains "New-Object" and ScriptBlockText contains "Microsoft.CSharp.CSharpCodeProvider" and ScriptBlockText contains "[System.Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory())" and ScriptBlockText contains "Collections.ArrayList" and ScriptBlockText contains "System.CodeDom.Compiler.CompilerParameters")