// Title: Enumerate Credentials from Windows Credential Manager With PowerShell
// Author: frack113
// Date: 2021-12-20
// Level: medium
// Description: Adversaries may search for common password storage locations to obtain user credentials.
// Passwords are stored in several places on a system, depending on the operating system or application holding the credentials.
// This table contains Windows security event logs, including script block logging events. Enable the necessary data connectors in Microsoft Sentinel to collect Windows security event logs.
// Tags: attack.credential-access, attack.t1555
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "vaultcmd" and ScriptBlockText contains "/listcreds:") and (ScriptBlockText contains "Windows Credentials" or ScriptBlockText contains "Web Credentials")