// Title: Manipulation of User Computer or Group Security Principals Across AD
// Author: frack113
// Date: 2021-12-28
// Level: medium
// Description: Adversaries may create a domain account to maintain access to victim systems.
// Domain accounts are those managed by Active Directory Domain Services where access and permissions are configured across systems and services that are part of that domain..
// This table contains security-related events, including script block logging events. To query for the specific events related to the Sigma rule, filter on the 'EventID' field and look for events with EventID 4104.
// Tags: attack.persistence, attack.t1136.002
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "System.DirectoryServices.AccountManagement"