// Title: OpenCanary - GIT Clone Request
// Author: Security Onion Solutions
// Date: 2024-03-08
// Level: high
// Description: Detects instances where a GIT service on an OpenCanary node has had Git Clone request.The equivalent table in Microsoft Sentinel for Opencanary logs. Ensure Opencanary logs are being collected and ingested into Sentinel for this table to be populated.
// Tags: attack.collection, attack.t1213
// ================================================================== 

OpencanaryLogs
| where logtype == 16001