// Title: Dump Ntds.dit To Suspicious Location
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-14
// Level: medium
// Description: Detects potential abuse of ntdsutil to dump ntds.dit database to a suspicious locationThe WindowsEvent table in Microsoft Sentinel contains logs related to Windows events, which can include application logs. Ensure that the necessary data connectors are set up in Sentinel to collect Windows event logs.
// Tags: attack.execution
// ================================================================== 

WindowsEvent
| where (Data contains ":\\ntds.dit" or Data contains "\\Appdata\\" or Data contains "\\Desktop\\" or Data contains "\\Downloads\\" or Data contains "\\Perflogs\\" or Data contains "\\Temp\\" or Data contains "\\Users\\Public\\") and (Data contains "ntds.dit" and Provider_Name =~ "ESENT")