// Title: Enable BPF Kprobes Tracing
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-25
// Level: medium
// Description: Detects common command used to enable bpf kprobes tracing
// Tags: attack.execution, attack.defense-evasion
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "/myprobe/enable" or ProcessCommandLine contains "/myretprobe/enable") and (ProcessCommandLine contains "echo 1 >" and ProcessCommandLine contains "/sys/kernel/debug/tracing/events/kprobes/")