// Title: Loading Diagcab Package From Remote Path
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-14
// Level: high
// Description: Detects loading of diagcab packages from a remote path, as seen in DogWalk vulnerabilityThe WindowsEvent table in Microsoft Sentinel contains logs related to Windows events. To query logs related to 'diagnosis-scripted' service, you may need to ensure that the necessary data connectors are set up in Sentinel to collect Windows event logs.
// Tags: attack.execution
// ================================================================== 

WindowsEvent
| where PackagePath contains "\\\\"