// Title: MSI Installation From Suspicious Locations
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-31
// Level: medium
// Description: Detects MSI package installation from suspicious locationsThis table contains Windows event logs, which can be queried for application-related events. Ensure that the Windows Security Events data connector is enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.execution
// ================================================================== 

WindowsEvent
| where ((Data contains ":\\Windows\\TEMP\\" or Data contains "\\\\" or Data contains "\\Desktop\\" or Data contains "\\PerfLogs\\" or Data contains "\\Users\\Public\\") and Provider_Name =~ "MsiInstaller") and (not((Data contains "C:\\Windows\\TEMP\\UpdHealthTools.msi" or Data contains "\\AppData\\Local\\Temp\\WinGet\\")))