// Title: Space After Filename
// Author: Ömer Günal
// Date: 2020-06-17
// Level: low
// Description: Detects space after filenameThis table contains Linux audit logs. To have this table present in Microsoft Sentinel, ensure that you have the Linux agent installed on your Linux machines and properly configured to send audit logs to Sentinel.
// Tags: attack.execution
// ================================================================== 

LinuxAuditLogs
| where "echo \"*\" > * && chmod +x *" and "mv * \"* \""