// Title: Suspicious Application Installed
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-14
// Level: medium
// Description: Detects suspicious application installed by looking at the added shortcut to the app resolver cacheThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.execution
// ================================================================== 

SecurityEvent
| where (Name contains "Zenmap" or Name contains "AnyDesk" or Name contains "wireshark" or Name contains "openvpn") or (AppID contains "zenmap.exe" or AppID contains "prokzult ad" or AppID contains "wireshark" or AppID contains "openvpn")