// Title: Suspicious Nohup Execution
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-06-02
// Level: high
// Description: Detects execution of binaries located in potentially suspicious locations via "nohup"
// Tags: attack.execution
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "/tmp/" and FolderPath endswith "/nohup"