// Title: Suspicious Usage of CVE_2021_34484 or CVE 2022_21919
// Author: Cybex
// Date: 2022-08-16
// Level: low
// Description: During exploitation of this vulnerability, two logs (Provider_Name:Microsoft-Windows-User Profiles Service) with EventID 1511 and 1515 (maybe lot of false positives with this event) are created. Moreover, it appears the directory \Users\TEMP is created may be created during the exploitation. Viewed on 2008 ServerThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.execution
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Microsoft-Windows-User Profiles Service"