// Title: Remove Immutable File Attribute - Auditd
// Author: Jakob Weinzettl, oscd.community
// Date: 2019-09-23
// Level: medium
// Description: Detects removing immutable file attribute.The LinuxAudit table in Microsoft Sentinel contains audit logs from Linux systems. To have this table present, ensure that the Linux machines are onboarded to Sentinel and the necessary data connectors are configured to collect audit logs.
// Tags: attack.defense-evasion, attack.t1222.002
// ================================================================== 

LinuxAudit
| where a0 contains "chattr" and a1 contains "-i" and type =~ "EXECVE"