// Title: Steganography Unzip Hidden Information From Picture File
// Author: Pawel Mazur
// Date: 2021-09-09
// Level: low
// Description: Detects extracting of zip file from image fileThe equivalent table in Microsoft Sentinel for Linux audit logs. Ensure that the Linux machines are onboarded to Sentinel and the appropriate data connectors are set up to collect and ingest audit logs from the auditd service on the Linux machines.
// Tags: attack.defense-evasion, attack.t1027.003
// ================================================================== 

LinuxAuditLogs
| where (a0 =~ "unzip" and type =~ "EXECVE") and (a1 endswith ".jpg" or a1 endswith ".png")