// Title: Steganography Hide Files with Steghide
// Author: Pawel Mazur
// Date: 2021-09-11
// Level: low
// Description: Detects embedding of files with usage of steghide binary, the adversaries may use this technique to prevent the detection of hidden information.The table name in Microsoft Sentinel for Linux audit logs. Ensure that the Linux machines are onboarded to Sentinel and the Linux agent is configured to send audit logs to Sentinel.
// Tags: attack.defense-evasion, attack.t1027.003
// ================================================================== 

LinuxAudit
| where a0 =~ "steghide" and a1 =~ "embed" and (a2 in~ ("-cf", "-ef")) and (a4 in~ ("-cf", "-ef")) and type =~ "EXECVE"