// Title: Steganography Hide Zip Information in Picture File
// Author: Pawel Mazur
// Date: 2021-09-09
// Level: low
// Description: Detects appending of zip file to imageThis table contains Linux audit logs. To have this table present in Microsoft Sentinel, ensure that the Linux machines are onboarded and configured to send audit logs to Sentinel.
// Tags: attack.defense-evasion, attack.t1027.003
// ================================================================== 

LinuxAuditLogs
| where (a0 =~ "cat" and type =~ "EXECVE") and (a1 endswith ".jpg" or a1 endswith ".png") and a2 endswith ".zip"