// Title: New Kind of Network (NKN) Detection
// Author: Michael Portera (@mportatoes)
// Date: 2022-04-21
// Level: low
// Description: NKN is a networking service using blockchain technology to support a decentralized network of peers. While there are legitimate uses for it, it can also be used as a C2 channel. This rule looks for a DNS request to the ma>The equivalent table in Microsoft Sentinel for DNS events. Ensure that the Zeek logs are being ingested into Sentinel to have this table available.
// Tags: attack.command-and-control
// ================================================================== 

DnsEvents
| where query contains "seed" and query contains ".nkn.org"