// Title: Suspicious C2 Activities
// Author: Marie Euler
// Date: 2020-05-18
// Level: medium
// Description: Detects suspicious activities as declared by Florian Roth in its 'Best Practice Auditd Configuration'.
// This includes the detection of the following commands; wget, curl, base64, nc, netcat, ncat, ssh, socat, wireshark, rawshark, rdesktop, nmap.
// These commands match a few techniques from the tactics "Command and Control", including not exhaustively the following; Application Layer Protocol (T1071), Non-Application Layer Protocol (T1095), Data Encoding (T1132)
// The LinuxAudit table in Microsoft Sentinel contains audit logs from Linux systems. To have this table present, ensure that the Linux machines are onboarded to Sentinel and the necessary data connectors are configured to collect audit logs.
// Tags: attack.command-and-control
// ================================================================== 

LinuxAudit
| where key =~ "susp_activity"