// Title: AWS ElastiCache Security Group Created
// Author: Austin Songer @austinsonger
// Date: 2021-07-24
// Level: low
// Description: Detects when an ElastiCache security group has been created.The CloudTrail table in Microsoft Sentinel contains logs related to AWS CloudTrail service. To query this table, ensure that the AWS CloudTrail connector is set up in Sentinel and ingesting logs from the specified AWS account.
// Tags: attack.persistence, attack.t1136, attack.t1136.003
// ================================================================== 

CloudTrail
| where eventName =~ "CreateCacheSecurityGroup" and eventSource =~ "elasticache.amazonaws.com"