// Title: Invocation Of Crypto-Classes From The "Cryptography" PowerShell Namespace
// Author: Andreas Braathen (mnemonic.io)
// Date: 2023-12-01
// Level: medium
// Description: Detects the invocation of PowerShell commands with references to classes from the "System.Security.Cryptography" namespace.
// The PowerShell namespace "System.Security.Cryptography" provides classes for on-the-fly encryption and decryption.
// These can be used for example in decrypting malicious payload for defense evasion.
// 
// Tags: attack.defense-evasion, attack.t1059.001, attack.t1027.010, detection.threat-hunting
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains ".AesCryptoServiceProvider" or ProcessCommandLine contains ".DESCryptoServiceProvider" or ProcessCommandLine contains ".DSACryptoServiceProvider" or ProcessCommandLine contains ".RC2CryptoServiceProvider" or ProcessCommandLine contains ".Rijndael" or ProcessCommandLine contains ".RSACryptoServiceProvider" or ProcessCommandLine contains ".TripleDESCryptoServiceProvider") and ProcessCommandLine contains "System.Security.Cryptography." and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")))