// Description: Bazacall malware uses emails that contain a phone number for the user to call in order to cancel a fake subscription. These emails contain no links or attachments, and use automatic payment lures to trick users into contacting the number included in the email.
// Required Connectors: MicrosoftThreatProtection (Types: EmailEvents)

EmailEvents
| where Subject matches regex @"[A-Z]{1,3}\d{9,15}"
    and Subject has_any('trial', 'free', 'demo', 'membership', 'premium', 'gold', 'notification', 'notice', 'claim', 'order', 'license', 'licenses')