// Title: Unattend.XML File Access Attempt
// Author: frack113
// Date: 2024-07-22
// Level: low
// Description: Detects attempts to access the "unattend.xml" file, where credentials might be stored.
// This file is used during the unattended windows install process.
// 
// Tags: attack.credential-access, attack.t1552.001, detection.threat-hunting
// ================================================================== 

DeviceFileEvents
| where FileName endswith "\\Panther\\unattend.xml"