// Title: CSExec Service Installation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-07
// Level: medium
// Description: Detects CSExec service installation and execution eventsThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events data connector is enabled in Sentinel to have this table available for querying.
// Tags: attack.execution, attack.t1569.002
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager" and (ServiceName =~ "csexecsvc" or ImagePath endswith "\\csexecsvc.exe")