// Title: PAExec Service Installation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-26
// Level: medium
// Description: Detects PAExec service installationThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.execution, attack.t1569.002
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager" and (ServiceName startswith "PAExec-" or ImagePath startswith "C:\\WINDOWS\\PAExec-")