// Title: PowerShell Scripts Installed as Services
// Author: oscd.community, Natalia Shornikova
// Date: 2020-10-06
// Level: high
// Description: Detects powershell script installed as a ServiceThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events are being collected and forwarded to Sentinel for this table to be populated.
// Tags: attack.execution, attack.t1569.002
// ================================================================== 

SecurityEvent
| where (ImagePath contains "powershell" or ImagePath contains "pwsh") and Provider_Name =~ "Service Control Manager"