// Title: PsExec Tool Execution From Suspicious Locations - PipeName
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-04
// Level: medium
// Description: Detects PsExec default pipe creation where the image executed is located in a suspicious location. Which could indicate that the tool is being used in an attackThis table contains Sysmon events, including Named Pipe Events (Event ID 17 and Event ID 18). To have this table present in Sentinel, you need to have Sysmon installed on the Windows machines and have the Sysmon connector configured to send data to Sentinel.
// Tags: attack.execution, attack.t1569.002, attack.s0029
// ================================================================== 

SysmonEvent
| where (InitiatingProcessFolderPath contains ":\\Users\\Public\\" or InitiatingProcessFolderPath contains ":\\Windows\\Temp\\" or InitiatingProcessFolderPath contains "\\AppData\\Local\\Temp\\" or InitiatingProcessFolderPath contains "\\Desktop\\" or InitiatingProcessFolderPath contains "\\Downloads\\") and PipeName =~ "\\PSEXESVC"