// Title: PsExec Service Installation
// Author: Thomas Patzke
// Date: 2017-06-12
// Level: medium
// Description: Detects PsExec service installation and execution eventsThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.execution, attack.t1569.002, attack.s0029
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager" and (ServiceName =~ "PSEXESVC" or ImagePath endswith "\\PSEXESVC.exe")