// Title: PUA - PAExec Default Named Pipe
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-26
// Level: medium
// Description: Detects PAExec default named pipeThis table contains Sysmon events, including Named Pipe Events (Event ID 17 and Event ID 18). To have this table present in Microsoft Sentinel, you need to have Sysmon installed on your Windows endpoints and configured to log Named Pipe Events.
// Tags: attack.execution, attack.t1569.002
// ================================================================== 

SysmonEvent
| where PipeName startswith "\\PAExec"