// Title: RemCom Service Installation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-07
// Level: medium
// Description: Detects RemCom service installation and execution eventsThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events are being collected and forwarded to Sentinel for this table to be populated.
// Tags: attack.execution, attack.t1569.002
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager" and (ServiceName =~ "RemComSvc" or ImagePath endswith "\\RemComSvc.exe")