// Title: Remote Schedule Task Recon via ITaskSchedulerService
// Author: Sagie Dulce, Dekel Paz
// Date: 2022-01-01
// Level: high
// Description: Detects remote RPC calls to read information about scheduled tasksThis table may not exist by default in Microsoft Sentinel. To have this table present, you may need to enable RPC Firewall logging in your environment and ensure that the logs are being sent to Sentinel for ingestion.
// Tags: attack.discovery
// ================================================================== 

rpc_firewall_logs
| where (EventLog =~ "RPCFW" and InterfaceUuid =~ "86d35949-83c9-4044-b424-db363231fd0c") and (not((OpNum in~ ("1", "3", "4", "10", "11", "12", "13", "14", "15"))))