// Title: Remote Registry Recon
// Author: Sagie Dulce, Dekel Paz
// Date: 2022-01-01
// Level: high
// Description: Detects remote RPC calls to collect informationThis table may not exist by default in Microsoft Sentinel. To have this table present, you may need to enable RPC Firewall logging in your environment and ensure that the logs are being sent to Sentinel for ingestion.
// Tags: attack.discovery
// ================================================================== 

rpc_firewall_logs
| where (EventLog =~ "RPCFW" and InterfaceUuid =~ "338cd001-2244-31f1-aaaa-900038001003") and (not((OpNum in~ ("6", "7", "8", "13", "18", "19", "21", "22", "23", "35"))))