// Title: Remote Event Log Recon
// Author: Sagie Dulce, Dekel Paz
// Date: 2022-01-01
// Level: high
// Description: Detects remote RPC calls to get event log information via EVEN or EVEN6This table contains logs related to the RPC Firewall. To have this table present in Microsoft Sentinel, make sure to enable RPC Firewall logging and configure the necessary connectors or data sources to ingest these logs.
// Tags: attack.discovery
// ================================================================== 

rpc_firewall_logs
| where EventLog =~ "RPCFW" and (InterfaceUuid in~ ("82273fdc-e32a-18c3-3f78-827929dc23ea", "f6beaff7-1e19-4fbb-9f8f-b89e2018337c"))