// Title: Azure Kubernetes CronJob
// Author: Austin Songer @austinsonger
// Date: 2021-11-22
// Level: medium
// Description: Identifies when a Azure Kubernetes CronJob runs in Azure Cloud. Kubernetes Job is a controller that creates one or more pods and ensures that a specified number of them successfully terminate.
// Kubernetes Job can be used to run containers that perform finite tasks for batch jobs. Kubernetes CronJob is used to schedule Jobs.
// An Adversary may use Kubernetes CronJob for scheduling execution of malicious code that would run as a container in the cluster.
// This table contains Azure activity logs. Ensure that Azure Activity Logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.persistence, attack.t1053.003, attack.privilege-escalation, attack.execution
// ================================================================== 

AzureActivityLogs
| where (operationName endswith "/CRONJOBS/WRITE" or operationName endswith "/JOBS/WRITE") and (operationName startswith "MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/BATCH" or operationName startswith "MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS/BATCH")