// Title: Cisco Collect Data
// Author: Austin Clark
// Date: 2019-08-11
// Level: low
// Description: Collect pertinent data from the configuration filesThis table contains authentication logs from Cisco AAA service. Make sure to have the necessary connectors or data sources configured in Sentinel to collect logs from Cisco devices.
// Tags: attack.discovery, attack.credential-access, attack.collection, attack.t1087.001, attack.t1552.001, attack.t1005
// ================================================================== 

Cisco_AAA_AuthenticationLogs
| where "show running-config" or "show startup-config" or "show archive config" or "more"