// Title: Suspicious Mount-DiskImage
// Author: frack113
// Date: 2022-02-01
// Level: low
// Description: Adversaries may abuse container files such as disk image (.iso, .vhd) file formats to deliver malicious payloads that may not be tagged with MOTW.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script block logging. Ensure that the Windows Security events are being collected and ingested into Sentinel.
// Tags: attack.defense-evasion, attack.t1553.005
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Mount-DiskImage " and ScriptBlockText contains "-ImagePath "