// Title: Password Policy Enumerated
// Author: Zach Mathis
// Date: 2023-05-19
// Level: medium
// Description: Detects when the password policy is enumerated.This table contains security-related events from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to populate this table.
// Tags: attack.discovery, attack.t1201
// ================================================================== 

SecurityEvent
| where AccessList contains "%%5392" and ObjectServer =~ "Security Account Manager"