// Title: Password Policy Discovery - Linux
// Author: Ömer Günal, oscd.community, Pawel Mazur
// Date: 2020-10-08
// Level: low
// Description: Detects password policy discovery commandsThe LinuxAuditLogs table in Microsoft Sentinel contains audit logs from Linux systems. To have this table present, ensure that the Linux machines are onboarded to Sentinel and the necessary data connectors are configured to collect audit logs.
// Tags: attack.discovery, attack.t1201
// ================================================================== 

LinuxAuditLogs
| where (a0 =~ "chage" and (a1 in~ ("--list", "-l")) and type =~ "EXECVE") or ((name in~ ("/etc/login.defs", "/etc/pam.d/auth", "/etc/pam.d/common-account", "/etc/pam.d/common-auth", "/etc/pam.d/common-password", "/etc/pam.d/system-auth", "/etc/security/pwquality.conf")) and type =~ "PATH") or (a0 =~ "passwd" and (a1 in~ ("-S", "--status")) and type =~ "EXECVE")