// Title: Password Policy Discovery With Get-AdDefaultDomainPasswordPolicy
// Author: frack113
// Date: 2022-03-17
// Level: low
// Description: Detetcts PowerShell activity in which Get-Addefaultdomainpasswordpolicy is used to get the default password policy for an Active Directory domain.This table contains Windows security event logs, including script block logging events. Enable the appropriate data connectors in Microsoft Sentinel to collect Windows security event logs.
// Tags: attack.discovery, attack.t1201
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Get-AdDefaultDomainPasswordPolicy"