// Title: Linux Keylogging with Pam.d
// Author: Pawel Mazur
// Date: 2021-05-24
// Level: high
// Description: Detect attempt to enable auditing of TTY inputThe equivalent table in Microsoft Sentinel for Linux audit logs. Ensure that the Linux machines are onboarded to Sentinel and the necessary data connectors are configured to collect audit logs from the auditd service on the Linux machines.
// Tags: attack.credential-access, attack.t1003, attack.t1056.001
// ================================================================== 

LinuxAuditLogs
| where ((name in~ ("/etc/pam.d/system-auth", "/etc/pam.d/password-auth")) and type =~ "PATH") or (type in~ ("TTY", "USER_TTY"))