// Title: OpenCanary - MySQL Login Attempt
// Author: Security Onion Solutions
// Date: 2024-03-08
// Level: high
// Description: Detects instances where a MySQL service on an OpenCanary node has had a login attempt.The OpencanaryLog table in Microsoft Sentinel contains logs related to the Opencanary application. To query this table, ensure that the Opencanary logs are being collected and sent to Sentinel for analysis.
// Tags: attack.credential-access, attack.collection, attack.t1003, attack.t1213
// ================================================================== 

OpencanaryLog
| where logtype == 8001