// Title: OpenCanary - MSSQL Login Attempt Via SQLAuth
// Author: Security Onion Solutions
// Date: 2024-03-08
// Level: high
// Description: Detects instances where an MSSQL service on an OpenCanary node has had a login attempt using SQLAuth.
// This table contains logs from the Opencanary application. To have this table present in Microsoft Sentinel, you need to ensure that Opencanary logs are being collected and sent to Sentinel for analysis.
// Tags: attack.credential-access, attack.collection, attack.t1003, attack.t1213
// ================================================================== 

OpencanaryLogs
| where logtype == 9001