// Title: Suspicious Plink Port Forwarding
// Author: Florian Roth (Nextron Systems)
// Date: 2021-01-19
// Level: high
// Description: Detects suspicious Plink tunnel port forwarding to a local port
// Tags: attack.command-and-control, attack.t1572, attack.lateral-movement, attack.t1021.001
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains " -R " and ProcessVersionInfoFileDescription =~ "Command-line SSH, Telnet, and Rlogin client"