// Title: Potential RDP Tunneling Via SSH
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-12
// Level: high
// Description: Execution of ssh.exe to perform data exfiltration and tunneling through RDP
// Tags: attack.command-and-control, attack.t1572
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains ":3389" and FolderPath endswith "\\ssh.exe"