// Title: RDP to HTTP or HTTPS Target Ports
// Author: Florian Roth (Nextron Systems)
// Date: 2022-04-29
// Level: high
// Description: Detects svchost hosting RDP termsvcs communicating to target systems on TCP port 80 or 443
// Tags: attack.command-and-control, attack.t1572, attack.lateral-movement, attack.t1021.001, car.2013-07-002
// ================================================================== 

DeviceNetworkEvents
| where (RemotePort in~ ("80", "443")) and InitiatingProcessFolderPath endswith "\\svchost.exe" and LocalPort == 3389