// Title: Mount Execution With Hidepid Parameter
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-01-12
// Level: medium
// Description: Detects execution of the "mount" command with "hidepid" parameter to make invisible processes to other users from the system
// Tags: attack.credential-access, attack.t1564
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "hidepid=2" and ProcessCommandLine contains " -o ") and FolderPath endswith "/mount"