// Title: Google Cloud Kubernetes CronJob
// Author: Austin Songer @austinsonger
// Date: 2021-11-22
// Level: medium
// Description: Identifies when a Google Cloud Kubernetes CronJob runs in Azure Cloud. Kubernetes Job is a controller that creates one or more pods and ensures that a specified number of them successfully terminate.
// Kubernetes Job can be used to run containers that perform finite tasks for batch jobs. Kubernetes CronJob is used to schedule Jobs.
// An Adversary may use Kubernetes CronJob for scheduling execution of malicious code that would run as a container in the cluster.
// This table contains GCP audit logs. Ensure that the GCP connector is set up in Microsoft Sentinel to collect GCP audit logs.
// Tags: attack.persistence, attack.privilege-escalation, attack.execution
// ================================================================== 

GCPAuditLogs
| where ('gcp.audit.method_name' contains "io.k8s.api.batch.v" and 'gcp.audit.method_name' contains ".Job") or ('gcp.audit.method_name' contains "io.k8s.api.batch.v" and 'gcp.audit.method_name' contains ".CronJob")