// Title: MSSQL SPProcoption Set
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-13
// Level: high
// Description: Detects when the a stored procedure is set or cleared for automatic execution in MSSQL. A stored procedure that is set to automatic execution runs every time an instance of SQL Server is startedThis table contains security-related events, including application log events. Make sure to have the Windows Security Events data connector enabled in Microsoft Sentinel to access this table.
// Tags: attack.persistence
// ================================================================== 

SecurityEvent
| where (Data contains "object_name:sp_procoption" and Data contains "statement:EXEC") and Provider_Name contains "MSSQL"