// Title: MSSQL Add Account To Sysadmin Role
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-13
// Level: high
// Description: Detects when an attacker tries to backdoor the MSSQL server by adding a backdoor account to the sysadmin fixed server roleThis table contains security-related events, including MSSQL audit policy events. Make sure to have the necessary connectors or data sources configured in Sentinel to collect Windows security events.
// Tags: attack.persistence
// ================================================================== 

SecurityEvent
| where (Data contains "object_name:sysadmin" and Data contains "statement:alter server role [sysadmin] add member ") and Provider_Name contains "MSSQL"