// Title: Potential Suspicious BPF Activity - Linux
// Author: Red Canary (idea), Nasreddine Bencherchali
// Date: 2023-01-25
// Level: high
// Description: Detects the presence of "bpf_probe_write_user" BPF helper-generated warning messages. Which could be a sign of suspicious eBPF activity on the system.This table contains Linux audit logs, which can be queried in Microsoft Sentinel. Ensure that the Linux machines are onboarded to Sentinel and the necessary data connectors are set up to collect audit logs from these machines.
// Tags: attack.persistence, attack.defense-evasion
// ================================================================== 

LinuxAuditLogs
| where "bpf_probe_write_user"