// Title: Remote Utilities Host Service Install
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-31
// Level: medium
// Description: Detects Remote Utilities Host service installation on the target system.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events are being collected and ingested into Sentinel for this table to be available.
// Tags: attack.persistence
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager" and ((ImagePath contains "\\rutserv.exe" and ImagePath contains "-service") or ServiceName =~ "Remote Utilities - Host")