// Title: RTCore Suspicious Service Installation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-30
// Level: high
// Description: Detects the installation of RTCore service. Which could be an indication of Micro-Star MSI Afterburner vulnerable driver abuseThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.persistence
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Service Control Manager" and ServiceName =~ "RTCore64"