// Title: Unsigned AppX Installation Attempt Using Add-AppxPackage - PsScript
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-31
// Level: medium
// Description: Detects usage of the "Add-AppxPackage" or it's alias "Add-AppPackage" to install unsigned AppX packagesThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events data connector is enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.persistence, attack.defense-evasion
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "Add-AppPackage " or ScriptBlockText contains "Add-AppxPackage ") and ScriptBlockText contains " -AllowUnsigned"