// Title: Hidden Executable In NTFS Alternate Data Stream
// Author: Florian Roth (Nextron Systems), @0xrawsec
// Date: 2018-06-03
// Level: medium
// Description: Detects the creation of an ADS (Alternate Data Stream) that contains an executable by looking at a non-empty ImphashThis table contains Sysmon events which can be queried for Imphash logging. Ensure Sysmon is installed and configured on the Windows machines sending logs to Sentinel.
// Tags: attack.defense-evasion, attack.s0139, attack.t1564.004
// ================================================================== 

SysmonEvent
| where Hash contains "IMPHASH=" and (not(Hash contains "IMPHASH=00000000000000000000000000000000"))