// Title: Powershell Store File In Alternate Data Stream
// Author: frack113
// Date: 2021-09-02
// Level: medium
// Description: Storing files in Alternate Data Stream (ADS) similar to Astaroth malware.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows security events are being collected and ingested into Microsoft Sentinel.
// Tags: attack.defense-evasion, attack.t1564.004
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Start-Process" and ScriptBlockText contains "-FilePath \"$env:comspec\" " and ScriptBlockText contains "-ArgumentList " and ScriptBlockText contains ">"