// Title: Bitbucket Unauthorized Access To A Resource
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2024-02-25
// Level: critical
// Description: Detects unauthorized access attempts to a resource.This table contains audit logs for various services including Bitbucket. Ensure that the necessary connectors are set up to collect Bitbucket audit logs in Sentinel.
// Tags: attack.resource-development, attack.t1586
// ================================================================== 

AuditLogs
| where 'auditType.action' =~ "Unauthorized access to a resource" and 'auditType.category' =~ "Security"