// Title: Potential DLL Sideloading Of MpSvc.DLL
// Author: Nasreddine Bencherchali (Nextron Systems), Wietze Beukema
// Date: 2024-07-11
// Level: medium
// Description: Detects potential DLL sideloading of "MpSvc.dll".
// Tags: attack.defense-evasion, attack.t1574.002
// ================================================================== 

DeviceImageLoadEvents
| where FolderPath endswith "\\MpSvc.dll" and (not((FolderPath startswith "C:\\Program Files\\Windows Defender\\" or FolderPath startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\" or FolderPath startswith "C:\\Windows\\WinSxS\\")))