// Title: PowerShell Decompress Commands
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-05-02
// Level: informational
// Description: A General detection for specific decompress commands in PowerShell logs. This could be an adversary decompressing files.This table contains security event logs from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to collect these logs.
// Tags: attack.defense-evasion, attack.t1140
// ================================================================== 

SecurityEvent
| where Payload contains "Expand-Archive"