// Title: Okta MFA Reset or Deactivated
// Author: Austin Songer @austinsonger
// Date: 2021-09-21
// Level: medium
// Description: Detects when an attempt at deactivating  or resetting MFA.This table contains Okta sign-in logs. To have this table present in Microsoft Sentinel, you need to ensure that the Okta connector is set up and configured to send sign-in logs to Sentinel.
// Tags: attack.persistence, attack.credential-access, attack.defense-evasion, attack.t1556.006
// ================================================================== 

OktaSignInLogs
| where eventtype in~ ("user.mfa.factor.deactivate", "user.mfa.factor.reset_all")