// Title: AWS STS GetSessionToken Misuse
// Author: Austin Songer @austinsonger
// Date: 2021-07-24
// Level: low
// Description: Identifies the suspicious use of GetSessionToken. Tokens could be created and used by attackers to move laterally and escalate privileges.The CloudTrail table in Microsoft Sentinel is the equivalent table to query for AWS CloudTrail logs. To have this table present in Sentinel, you need to ensure that the AWS CloudTrail connector is configured and collecting logs from your AWS account.
// Tags: attack.lateral-movement, attack.privilege-escalation, attack.t1548, attack.t1550, attack.t1550.001
// ================================================================== 

CloudTrail
| where eventName =~ "GetSessionToken" and eventSource =~ "sts.amazonaws.com" and 'userIdentity.type' =~ "IAMUser"