// Title: AWS STS AssumeRole Misuse
// Author: Austin Songer @austinsonger
// Date: 2021-07-24
// Level: low
// Description: Identifies the suspicious use of AssumeRole. Attackers could move laterally and escalate privileges.The CloudTrail table in Microsoft Sentinel contains logs related to AWS CloudTrail service. To have this table present in Sentinel, ensure that the AWS CloudTrail connector is set up and configured to ingest logs into Sentinel.
// Tags: attack.lateral-movement, attack.privilege-escalation, attack.t1548, attack.t1550, attack.t1550.001
// ================================================================== 

CloudTrail
| where 'userIdentity.sessionContext.sessionIssuer.type' =~ "Role" and 'userIdentity.type' =~ "AssumedRole"