// Title: Potentially Suspicious Shell Script Creation in Profile Folder
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-06-02
// Level: low
// Description: Detects the creation of shell scripts under the "profile.d" path.
// Tags: attack.persistence
// ================================================================== 

DeviceFileEvents
| where FolderPath contains "/etc/profile.d/" and (FolderPath endswith ".csh" or FolderPath endswith ".sh")