// Title: Nohup Execution
// Author: Christopher Peacock @SecurePeacock, SCYTHE @scythe_io
// Date: 2022-06-06
// Level: medium
// Description: Detects usage of nohup which could be leveraged by an attacker to keep a process running or break out from restricted environments
// Tags: attack.execution, attack.t1059.004
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "/nohup"