// Title: DNS Query for Anonfiles.com Domain - DNS Client
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-16
// Level: high
// Description: Detects DNS queries for anonfiles.com, which is an anonymous file upload platform often used for malicious purposesThis table contains DNS client events from the Microsoft-Windows-DNS Client Events/Operational Event Log. Ensure that the Microsoft-Windows-DNS Client Events/Operational Event Log is enabled and collected in order to populate this table in Microsoft Sentinel.
// Tags: attack.exfiltration, attack.t1567.002
// ================================================================== 

DnsEvents
| where QueryName contains ".anonfiles.com"