// Title: DNS Query To MEGA Hosting Website
// Author: Aaron Greetham (@beardofbinary) - NCC Group
// Date: 2021-05-26
// Level: medium
// Description: Detects DNS queries for subdomains related to MEGA sharing websiteThe DnsEvents table in Microsoft Sentinel contains DNS query logs. Ensure that the necessary connectors are set up to collect Windows DNS query logs in order to query this table.
// Tags: attack.exfiltration, attack.t1567.002
// ================================================================== 

DnsEvents
| where QueryName contains "userstorage.mega.co.nz"