// Title: DNS Query To Ufile.io - DNS Client
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-16
// Level: low
// Description: Detects DNS queries to "ufile.io", which was seen abused by malware and threat actors as a method for data exfiltrationThis table contains DNS client events from the Microsoft-Windows-DNS Client Events/Operational Event Log. Make sure to enable and collect this log in order to query this table.
// Tags: attack.exfiltration, attack.t1567.002
// ================================================================== 

DnsEvents
| where QueryName contains "ufile.io"