// Title: DNS Query To MEGA Hosting Website - DNS Client
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-16
// Level: medium
// Description: Detects DNS queries for subdomains related to MEGA sharing websiteThis table contains DNS client events from the Microsoft-Windows-DNS Client Events/Operational Event Log. Ensure that the Microsoft-Windows-DNS Client Events/Operational Event Log is enabled and collected in order to have data in this table.
// Tags: attack.exfiltration, attack.t1567.002
// ================================================================== 

DnsEvents
| where QueryName contains "userstorage.mega.co.nz"