// Title: DNS Query for Anonfiles.com Domain - Sysmon
// Author: pH-T (Nextron Systems)
// Date: 2022-07-15
// Level: high
// Description: Detects DNS queries for "anonfiles.com", which is an anonymous file upload platform often used for malicious purposesThe DnsEvents table in Microsoft Sentinel contains DNS query logs. Ensure that the Windows Security Events data connector is enabled in Sentinel to collect these logs.
// Tags: attack.exfiltration, attack.t1567.002
// ================================================================== 

DnsEvents
| where QueryName contains ".anonfiles.com"