// Title: ProxyLogon MSExchange OabVirtualDirectory
// Author: Florian Roth (Nextron Systems)
// Date: 2021-08-09
// Level: critical
// Description: Detects specific patterns found after a successful ProxyLogon exploitation in relation to a Commandlet invocation of Set-OabVirtualDirectoryThis table contains logs related to Microsoft Exchange management activities. To have this table present in Microsoft Sentinel, ensure that you have the necessary connectors or data sources configured to collect logs from Microsoft Exchange servers with the 'msexchange-management' service.
// Tags: attack.t1587.001, attack.resource-development
// ================================================================== 

ExchangeAdmin
| where ("OabVirtualDirectory" and " -ExternalUrl ") and ("eval(request" or "http://f/<script" or "\"unsafe\"};" or "function Page_Load()")