// Title: T1047 Wmiprvse Wbemcomn DLL Hijack
// Author: Roberto Rodriguez @Cyb3rWard0g, Open Threat Research (OTR)
// Date: 2020-10-12
// Level: high
// Description: Detects a threat actor creating a file named `wbemcomn.dll` in the `C:\Windows\System32\wbem\` directory over the network for a WMI DLL Hijack scenario.The SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. To query this table, ensure that you have the necessary data connectors set up in Sentinel to collect security events from Windows machines.
// Tags: attack.execution, attack.t1047, attack.lateral-movement, attack.t1021.002
// ================================================================== 

SecurityEvent
| where RelativeTargetName endswith "\\wbem\\wbemcomn.dll" and (not(SubjectUserName endswith "$"))