// Title: WMI Event Consumer Created Named Pipe
// Author: Florian Roth (Nextron Systems)
// Date: 2021-09-01
// Level: medium
// Description: Detects the WMI Event Consumer service scrcons.exe creating a named pipeThis table contains Sysmon events, including Named Pipe Events (Event ID 17 and Event ID 18). To have this table present in Sentinel, you need to have Sysmon installed on your Windows endpoints and configured to log Named Pipe Events.
// Tags: attack.t1047, attack.execution
// ================================================================== 

SysmonEvent
| where InitiatingProcessFolderPath endswith "\\scrcons.exe"