// Title: WMImplant Hack Tool
// Author: NVISO
// Date: 2020-03-26
// Level: high
// Description: Detects parameters used by WMImplantThe SecurityEvent table in Microsoft Sentinel contains logs related to security events on Windows machines. To ensure that Script Block Logging events are present in this table, ensure that the appropriate data connectors are set up in Sentinel to collect Windows security event logs.
// Tags: attack.execution, attack.t1047, attack.t1059.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "WMImplant" or ScriptBlockText contains " change_user " or ScriptBlockText contains " gen_cli " or ScriptBlockText contains " command_exec " or ScriptBlockText contains " disable_wdigest " or ScriptBlockText contains " disable_winrm " or ScriptBlockText contains " enable_wdigest " or ScriptBlockText contains " enable_winrm " or ScriptBlockText contains " registry_mod " or ScriptBlockText contains " remote_posh " or ScriptBlockText contains " sched_job " or ScriptBlockText contains " service_mod " or ScriptBlockText contains " process_kill " or ScriptBlockText contains " active_users " or ScriptBlockText contains " basic_info " or ScriptBlockText contains " power_off " or ScriptBlockText contains " vacant_system " or ScriptBlockText contains " logon_events "