// Title: Netcat The Powershell Version
// Author: frack113
// Date: 2021-07-21
// Level: medium
// Description: Adversaries may use a non-application layer protocol for communication between host and C2 server or among infected hosts within a networkThis table contains Windows security event logs, which can be queried to find information related to the 'ps_classic_start' category. Ensure that the Windows Security Events data connector is enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.command-and-control, attack.t1095
// ================================================================== 

SecurityEvent
| where Data contains "powercat " or Data contains "powercat.ps1"