// Title: Suspicious DNS Z Flag Bit Set
// Author: @neu5ron, SOC Prime Team, Corelight
// Date: 2021-05-04
// Level: medium
// Description: The DNS Z flag is bit within the DNS protocol header that is, per the IETF design, meant to be used reserved (unused).
// Although recently it has been used in DNSSec, the value being set to anything other than 0 should be rare.
// Otherwise if it is set to non 0 and DNSSec is being used, then excluding the legitimate domains is low effort and high reward.
// Determine if multiple of these files were accessed in a short period of time to further enhance the possibility of seeing if this was a one off or the possibility of larger sensitive file gathering.
// This Sigma query is designed to accompany the Corelight Threat Hunting Guide, which can be found here: https://www3.corelight.com/corelights-introductory-guide-to-threat-hunting-with-zeek-bro-logs'
// The equivalent table in Microsoft Sentinel for DNS events. Ensure that the Zeek connector is enabled in Sentinel to collect Zeek logs and populate this table.
// Tags: attack.t1095, attack.t1571, attack.command-and-control
// ================================================================== 

DnsEvents
| where (not(Z == 0)) and query contains "." and (not(((query endswith ".arpa" or query endswith ".local" or query endswith ".ultradns.net" or query endswith ".twtrdns.net" or query endswith ".azuredns-prd.info" or query endswith ".azure-dns.com" or query endswith ".azuredns-ff.info" or query endswith ".azuredns-ff.org" or query endswith ".azuregov-dns.org") or (qtype_name in~ ("ns", "mx")) or answers endswith "\\x00" or ('id.resp_p' in~ ("137", "138", "139")))))