// Title: Group Has Been Deleted Via Groupdel
// Author: Tuan Le (NCSGroup)
// Date: 2022-12-26
// Level: medium
// Description: Detects execution of the "groupdel" binary. Which is used to delete a group. This is sometimes abused by threat actors in order to cover their tracks
// Tags: attack.impact, attack.t1531
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "/groupdel"