// Title: Changes to Device Registration Policy
// Author: Michael Epping, '@mepples21'
// Date: 2022-06-28
// Level: high
// Description: Monitor and alert for changes to the device registration policy.This table contains Azure audit logs. Ensure that Azure Monitor logs are enabled and the necessary connectors are set up in Microsoft Sentinel to ingest Azure audit logs into this table.
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1484
// ================================================================== 

AzureActivity
| where ActivityDisplayName =~ "Set device registration policies" and Category =~ "Policy"