// Title: Invocation of Active Directory Diagnostic Tool (ntdsutil.exe)
// Author: Thomas Patzke
// Date: 2019-01-16
// Level: medium
// Description: Detects execution of ntdsutil.exe, which can be used for various attacks against the NTDS database (NTDS.DIT)
// Tags: attack.credential-access, attack.t1003.003
// ================================================================== 

DeviceProcessEvents
| where FolderPath endswith "\\ntdsutil.exe"