// Title: Azure Subscription Permission Elevation Via AuditLogs
// Author: Austin Songer @austinsonger
// Date: 2021-11-26
// Level: high
// Description: Detects when a user has been elevated to manage all Azure Subscriptions.
// This change should be investigated immediately if it isn't planned.
// This setting could allow an attacker access to Azure subscriptions in your environment.
// This table contains Azure activity logs, including audit logs. Ensure that Azure Diagnostics logs are enabled for the Azure service in question to populate this table.
// Tags: attack.initial-access, attack.t1078
// ================================================================== 

AzureActivity
| where Category =~ "Administrative" and OperationName =~ "Assigns the caller to user access admin"