// Title: Azure Domain Federation Settings Modified
// Author: Austin Songer
// Date: 2021-09-06
// Level: medium
// Description: Identifies when an user or application modified the federation settings on the domain.The AzureActivity table in Microsoft Sentinel contains Azure audit logs. Ensure that Azure Monitor logs are enabled for the Azure service being monitored in order to have data in this table.
// Tags: attack.initial-access, attack.t1078
// ================================================================== 

AzureActivity
| where ActivityDisplayName =~ "Set federation settings on domain"