// Title: Cisco BGP Authentication Failures
// Author: Tim Brown
// Date: 2023-01-09
// Level: low
// Description: Detects BGP failures which may be indicative of brute force attacks to manipulate routingThis table contains network analytics data including BGP logs from Cisco devices. Ensure that the Cisco Network Analytics solution is installed in Sentinel to have access to this table.
// Tags: attack.initial-access, attack.persistence, attack.privilege-escalation, attack.defense-evasion, attack.credential-access, attack.collection, attack.t1078, attack.t1110, attack.t1557
// ================================================================== 

CiscoNetworkAnalytics_CL
| where ":179" and "IP-TCP-3-BADAUTH"