// Title: Failed Logon From Public IP
// Author: NVISO
// Date: 2020-05-06
// Level: medium
// Description: Detects a failed logon attempt from a public IP. A login from a public IP can indicate a misconfigured firewall or network boundary.The SecurityEvent table in Microsoft Sentinel contains security-related events from Windows systems. Make sure to have the Windows Security Events connector enabled in Sentinel to populate this table.
// Tags: attack.initial-access, attack.persistence, attack.t1078, attack.t1190, attack.t1133
// ================================================================== 

SecurityEvent
| where not((IpAddress contains "-" or (ipv4_is_in_range(IpAddress, "::1/128") or ipv4_is_in_range(IpAddress, "10.0.0.0/8") or ipv4_is_in_range(IpAddress, "127.0.0.0/8") or ipv4_is_in_range(IpAddress, "172.16.0.0/12") or ipv4_is_in_range(IpAddress, "192.168.0.0/16") or ipv4_is_in_range(IpAddress, "169.254.0.0/16") or ipv4_is_in_range(IpAddress, "fc00::/7") or ipv4_is_in_range(IpAddress, "fe80::/10"))))