// Title: Juniper BGP Missing MD5
// Author: Tim Brown
// Date: 2023-01-09
// Level: low
// Description: Detects juniper BGP missing MD5 digest. Which may be indicative of brute force attacks to manipulate routing.This table contains logs related to Juniper devices, including BGP logs. Ensure that the Juniper Networks connector is installed in Sentinel to ingest these logs.
// Tags: attack.initial-access, attack.persistence, attack.privilege-escalation, attack.defense-evasion, attack.credential-access, attack.collection, attack.t1078, attack.t1110, attack.t1557
// ================================================================== 

JuniperNetworks_CL
| where ":179" and "missing MD5 digest"