// Title: Suspicious Computer Machine Password by PowerShell
// Author: frack113
// Date: 2022-02-21
// Level: medium
// Description: The Reset-ComputerMachinePassword cmdlet changes the computer account password that the computers use to authenticate to the domain controllers in the domain.
// You can use it to reset the password of the local computer.
// This table contains security-related events from Windows machines. Make sure to have the Windows Security Events data connector enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.initial-access, attack.t1078
// ================================================================== 

SecurityEvent
| where ContextInfo contains "Reset-ComputerMachinePassword"