// Title: Potentially Suspicious Execution From Tmp Folder
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-06-02
// Level: high
// Description: Detects a potentially suspicious execution of a process located in the '/tmp/' folder
// Tags: attack.defense-evasion, attack.t1036
// ================================================================== 

DeviceProcessEvents
| where FolderPath startswith "/tmp/"