// Title: Added Credentials to Existing Application
// Author: Mark Morowczynski '@markmorow', Bailey Bercik '@baileybercik'
// Date: 2022-05-26
// Level: high
// Description: Detects when a new credential is added to an existing application. Any additional credentials added outside of expected processes could be a malicious actor using those credentials.This table contains Azure activity logs, which include audit logs. Ensure that Azure Diagnostics logs are being sent to Log Analytics workspace in Sentinel to have this table available.
// Tags: attack.t1098.001, attack.persistence
// ================================================================== 

AzureActivity
| where 'properties.message' in~ ("Update Application-Certificates and secrets management", "Update Service principal/Update Application")