// Title: External Disk Drive Or USB Storage Device Was Recognized By The System
// Author: Keith Wright
// Date: 2019-11-20
// Level: low
// Description: Detects external disk drives or plugged-in USB devices.The SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. Make sure to have the Windows Security Events connector enabled in Sentinel to populate this table.
// Tags: attack.t1091, attack.t1200, attack.lateral-movement, attack.initial-access
// ================================================================== 

SecurityEvent
| where ClassName =~ "DiskDrive" or DeviceDescription =~ "USB Mass Storage Device"