// Title: Renamed BOINC Client Execution
// Author: Matt Anderson (Huntress)
// Date: 2024-07-23
// Level: medium
// Description: Detects the execution of a renamed BOINC binary.
// Tags: attack.defense-evasion, attack.t1553
// ================================================================== 

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "BOINC.exe" and (not(FolderPath endswith "\\BOINC.exe"))