// Title: Interesting Service Enumeration Via Sc.EXE
// Author: Swachchhanda Shrawan Poudel
// Date: 2024-02-12
// Level: low
// Description: Detects the enumeration and query of interesting and in some cases sensitive services on the system via "sc.exe".
// Attackers often try to enumerate the services currently running on a system in order to find different attack vectors.
// 
// Tags: attack.t1003
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "query" and ProcessCommandLine contains "termservice" and (FolderPath endswith "\\sc.exe" or ProcessVersionInfoOriginalFileName =~ "sc.exe")