// Title: F5 BIG-IP iControl Rest API Command Execution - Webserver
// Author: Nasreddine Bencherchali (Nextron Systems), Thurein Oo
// Date: 2023-11-08
// Level: medium
// Description: Detects POST requests to the F5 BIG-IP iControl Rest API "bash" endpoint, which allows the execution of commands on the BIG-IPThis table contains web server logs. Ensure that the appropriate connectors are set up in Sentinel to collect web server logs and populate this table.
// Tags: attack.execution, attack.t1190
// ================================================================== 

WebBrowserStats
| where 'cs-method' =~ "POST" and 'cs-uri-query' endswith "/mgmt/tm/util/bash"