// Title: Docker Container Discovery Via Dockerenv Listing
// Author: Seth Hanford
// Date: 2023-08-23
// Level: low
// Description: Detects listing or file reading of ".dockerenv" which can be a sing of potential container discovery
// Tags: attack.discovery, attack.t1082
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine endswith ".dockerenv" and (FolderPath endswith "/cat" or FolderPath endswith "/dir" or FolderPath endswith "/find" or FolderPath endswith "/ls" or FolderPath endswith "/stat" or FolderPath endswith "/test" or FolderPath endswith "grep")