// Title: Suspicious Remote Logon with Explicit Credentials
// Author: oscd.community, Teymur Kheirkhabarov @HeirhabarovT, Zach Stanford @svch0st, Tim Shelton
// Date: 2020-10-05
// Level: medium
// Description: Detects suspicious processes logging on with explicit credentialsThe SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. To query this table, ensure that you have the necessary data connectors set up in Sentinel to collect security events from Windows machines.
// Tags: attack.t1078, attack.lateral-movement
// ================================================================== 

SecurityEvent
| where (InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe" or InitiatingProcessFolderPath endswith "\\winrs.exe" or InitiatingProcessFolderPath endswith "\\wmic.exe" or InitiatingProcessFolderPath endswith "\\net.exe" or InitiatingProcessFolderPath endswith "\\net1.exe" or InitiatingProcessFolderPath endswith "\\reg.exe") and (not((TargetServerName =~ "localhost" or (SubjectUserName endswith "$" and TargetUserName endswith "$"))))