// Description: This query checks for attempts to clear at least 10 log entries from event logs using wevtutil.
// Required Connectors: MicrosoftThreatProtection (Types: DeviceProcessEvents)

// Look for use of wevtutil to clear multiple logs
DeviceProcessEvents
| where Timestamp > ago(1d)
| where ProcessCommandLine has "WEVTUTIL" and ProcessCommandLine has "CL"
| summarize LogClearCount = dcount(ProcessCommandLine), ClearedLogList = make_set(ProcessCommandLine) by DeviceId, bin(Timestamp, 5m)
| where LogClearCount > 10