// Description: Use this query to locate successful delivery of associated malicious downloads that can lead to ransomware
// Required Connectors: MicrosoftThreatProtection (Types: DeviceFileEvents)

DeviceFileEvents 
| where InitiatingProcessFileName in~("msedge.exe", "chrome.exe", "explorer.exe", "7zFM.exe", "firefox.exe", "browser_broker.exe") 
| where FileOriginReferrerUrl has ".php" and FileOriginReferrerUrl has ".top" and FileOriginUrl  has_any("googleusercontent", "google", "docs")