// Title: Github Self Hosted Runner Changes Detected
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2023-01-27
// Level: low
// Description: A self-hosted runner is a system that you deploy and manage to execute jobs from GitHub Actions on GitHub.com.
// This rule detects changes to self-hosted runners configurations in the environment. The self-hosted runner configuration changes once detected,
// it should be validated from GitHub UI because the log entry may not provide full context.
// This table contains audit logs for the Github service. To have access to this table in Microsoft Sentinel, make sure to have the Github connector configured and collecting data from the audit service.
// Tags: attack.impact, attack.discovery, attack.collection, attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.initial-access, attack.t1526, attack.t1213.003, attack.t1078.004
// ================================================================== 

GithubAuditLogs
| where action in~ ("org.remove_self_hosted_runner", "org.runner_group_created", "org.runner_group_removed", "org.runner_group_runner_removed", "org.runner_group_runners_added", "org.runner_group_runners_updated", "org.runner_group_updated", "repo.register_self_hosted_runner", "repo.remove_self_hosted_runner")