// Title: Split A File Into Pieces - Linux
// Author: Igor Fits, oscd.community
// Date: 2020-10-15
// Level: low
// Description: Detection use of the command "split" to split files into parts and possible transfer.The equivalent table in Microsoft Sentinel for Linux audit logs. Ensure that the Linux machines are onboarded to Sentinel and the necessary data connectors are configured to collect audit logs from the auditd service.
// Tags: attack.exfiltration, attack.t1030
// ================================================================== 

LinuxAuditLogs
| where comm =~ "split" and type =~ "SYSCALL"