// Title: Account Lockout
// Author: AlertIQ
// Date: 2021-10-10
// Level: medium
// Description: Identifies user account which has been locked because the user tried to sign in too many times with an incorrect user ID or password.The equivalent table in Microsoft Sentinel for Azure signin logs. Make sure to have the Azure Activity Log solution enabled in Sentinel to have access to this table.
// Tags: attack.credential-access, attack.t1110
// ================================================================== 

SigninLogs
| where ResultType == 50053