// Title: Password Spray Activity
// Author: Mark Morowczynski '@markmorow', Gloria Lee, '@gleeiamglo'
// Date: 2023-09-03
// Level: high
// Description: Indicates that a password spray attack has been successfully performed.The AzureActivity table in Microsoft Sentinel contains logs related to Azure activity, including risk detection events. Ensure that Azure Activity logs are being collected and ingested into Sentinel to query this table.
// Tags: attack.t1110, attack.credential-access
// ================================================================== 

AzureActivity
| where riskEventType =~ "passwordSpray"