// Title: User Access Blocked by Azure Conditional Access
// Author: AlertIQ
// Date: 2021-10-10
// Level: medium
// Description: Detect access has been blocked by Conditional Access policies.
// The access policy does not allow token issuance which might be sights≈ of unauthorizeed login to valid accounts.
// The equivalent table in Microsoft Sentinel for Azure signin logs. Ensure that Azure Active Directory logs are being collected and ingested into Sentinel to have this table present.
// Tags: attack.credential-access, attack.initial-access, attack.t1110, attack.t1078.004
// ================================================================== 

SigninLogs
| where ResultType == 53003