// Title: WMI Persistence - Security
// Author: Florian Roth (Nextron Systems), Gleb Sukhodolskiy, Timur Zinniatullin oscd.community
// Date: 2017-08-22
// Level: medium
// Description: Detects suspicious WMI event filter and command line event consumer based on WMI and Security Logs.
// Tags: attack.persistence, attack.privilege-escalation, attack.t1546.003
// ================================================================== 

DeviceRegistryEvents
| where RegistryKey contains "subscription"