// Title: Potential DLL Sideloading Of Libcurl.DLL Via GUP.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-05
// Level: medium
// Description: Detects potential DLL sideloading of "libcurl.dll" by the "gup.exe" process from an uncommon location
// Tags: attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.t1574.001, attack.t1574.002
// ================================================================== 

DeviceImageLoadEvents
| where (FolderPath endswith "\\libcurl.dll" and InitiatingProcessFolderPath endswith "\\gup.exe") and (not(InitiatingProcessFolderPath endswith "\\Notepad++\\updater\\GUP.exe"))