// Title: HackTool - EfsPotato Named Pipe Creation
// Author: Florian Roth (Nextron Systems)
// Date: 2021-08-23
// Level: high
// Description: Detects the pattern of a pipe name as used by the hack tool EfsPotatoThis table contains Sysmon events, including Named Pipe Events (Event ID 17 and Event ID 18). To have this table present in Microsoft Sentinel, you need to have Sysmon installed on your Windows endpoints and configured to log Named Pipe Events.
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1055
// ================================================================== 

SysmonEvent
| where (PipeName contains "\\pipe\\" or PipeName contains "\\pipe\\srvsvc") and (not((PipeName contains "\\CtxShare" or PipeName startswith "\\pipe\\")))