// Title: Malicious Named Pipe Created
// Author: Florian Roth (Nextron Systems), blueteam0ps, elhoim
// Date: 2017-11-06
// Level: critical
// Description: Detects the creation of a named pipe seen used by known APTs or malware.This table contains Sysmon events, including Named Pipe Events (Event ID 17 and Event ID 18). To have this table present in Microsoft Sentinel, you need to have Sysmon installed on your Windows endpoints and configured to log Named Pipe Events.
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1055
// ================================================================== 

SysmonEvent
| where PipeName in~ ("\\46a676ab7f179e511e30dd2dc41bd388", "\\583da945-62af-10e8-4902-a8f205c72b2e", "\\6e7645c4-32c5-4fe3-aabf-e94c2f4370e7", "\\9f81f59bc58452127884ce513865ed20", "\\adschemerpc", "\\ahexec", "\\AnonymousPipe", "\\bc31a7", "\\bc367", "\\bizkaz", "\\csexecsvc", "\\dce_3d", "\\e710f28d59aa529d6792ca6ff0ca1b34", "\\gruntsvc", "\\isapi_dg", "\\isapi_dg2", "\\isapi_http", "\\jaccdpqnvbrrxlaf", "\\lsassw", "\\NamePipe_MoreWindows", "\\pcheap_reuse", "\\rpchlp_3", "\\sdlrpc", "\\svcctl", "\\testPipe", "\\winsession") or PipeName startswith "\\Posh"