// Title: PowerShell ShellCode
// Author: David Ledbetter (shellcode), Florian Roth (Nextron Systems)
// Date: 2018-11-17
// Level: high
// Description: Detects Base64 encoded ShellcodeThis table contains Windows security event logs, which may include information about script block logging being enabled. Make sure to have the necessary connectors and data sources configured in Sentinel to collect Windows security event logs.
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1055, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "OiCAAAAYInlM" or ScriptBlockText contains "OiJAAAAYInlM"