// Title: CodeIntegrity - Unmet WHQL Requirements For Loaded Kernel Module
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-06
// Level: high
// Description: Detects loaded kernel modules that did not meet the WHQL signing requirements.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which may include code integrity operational events. Ensure that the Windows Security Events data connector is enabled in Sentinel to query this table.
// Tags: attack.privilege-escalation
// ================================================================== 

SecurityEvent
| where not((FileNameBuffer in~ ("system32\\drivers\\vsock.sys", "System32\\drivers\\vmci.sys")))