// Title: HackTool - DiagTrackEoP Default Named Pipe
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-03
// Level: critical
// Description: Detects creation of default named pipe used by the DiagTrackEoP POC, a tool that abuses "SeImpersonate" privilege.This table contains Sysmon events, including Named Pipe Events (Event ID 17 and Event ID 18). To have this table present in Sentinel, you need to ensure that Sysmon is deployed on the Windows machines and configured to log the necessary events.
// Tags: attack.privilege-escalation
// ================================================================== 

SysmonEvent
| where PipeName contains "thisispipe"