// Title: Kubernetes Unauthorized or Unauthenticated Access
// Author: kelnage
// Date: 2024-04-12
// Level: low
// Description: Detects when a request to the Kubernetes API is rejected due to lack of authorization or due to an expired authentication token being used.
// This may indicate an attacker attempting to leverage credentials they have obtained.
// The KubeEvents table in Microsoft Sentinel contains Kubernetes audit logs. To have this table present, ensure that you have the Kubernetes data connector enabled in Sentinel and that it is properly configured to collect audit logs.
// Tags: attack.privilege-escalation
// ================================================================== 

KubeEvents
| where 'responseStatus.code' in~ ("401", "403")