// Title: Invoke-Obfuscation COMPRESS OBFUSCATION - PowerShell Module
// Author: Timur Zinniatullin, oscd.community
// Date: 2020-10-18
// Level: medium
// Description: Detects Obfuscated Powershell via COMPRESS OBFUSCATIONThis table contains security events from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to collect this data.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (Payload contains "system.io.compression.deflatestream" or Payload contains "system.io.streamreader") and (Payload contains "new-object" and Payload contains "text.encoding]::ascii") and Payload endswith "readtoend"