// Title: Invoke-Obfuscation VAR+ Launcher - Security
// Author: Jonathan Cheong, oscd.community
// Date: 2020-10-15
// Level: high
// Description: Detects Obfuscated use of Environment Variables to execute PowerShellThis table contains security-related events, including event ID 4697. Make sure to have the Windows Security Events data connector enabled in Microsoft Sentinel to query this table.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ServiceFileName contains "/c" or ServiceFileName contains "/r") and (ServiceFileName contains "cmd" and ServiceFileName contains "\"set" and ServiceFileName contains "-f")