// Title: Invoke-Obfuscation CLIP+ Launcher - Security
// Author: Jonathan Cheong, oscd.community
// Date: 2020-10-13
// Level: high
// Description: Detects Obfuscated use of Clip.exe to execute PowerShellThis table contains security-related events, including event ID 4697. Make sure to have the Windows Security Events data connector enabled in Microsoft Sentinel to query this table.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where ServiceFileName contains "cmd" and ServiceFileName contains "&&" and ServiceFileName contains "clipboard]::"