// Title: Invoke-Obfuscation CLIP+ Launcher - PowerShell
// Author: Jonathan Cheong, oscd.community
// Date: 2020-10-13
// Level: high
// Description: Detects Obfuscated use of Clip.exe to execute PowerShellThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText matches regex "cmd.{0,5}(?:/c|/r).+clip(?:\\.exe)?.{0,4}&&.+clipboard]::\\(\\s\\\\"\\{\\d\\}.+-f.+""