// Title: Invoke-Obfuscation CLIP+ Launcher - System
// Author: Jonathan Cheong, oscd.community
// Date: 2020-10-13
// Level: high
// Description: Detects Obfuscated use of Clip.exe to execute PowerShellThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ImagePath contains "cmd" and ImagePath contains "&&" and ImagePath contains "clipboard]::") and Provider_Name =~ "Service Control Manager"