// Title: Invoke-Obfuscation Via Use MSHTA - System
// Author: Nikita Nazarov, oscd.community
// Date: 2020-10-09
// Level: high
// Description: Detects Obfuscated Powershell via use MSHTA in ScriptsThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events data connector is enabled in Sentinel to have this table available for querying.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ImagePath contains "mshta" and ImagePath contains "vbscript:createobject") and Provider_Name =~ "Service Control Manager"