// Title: Invoke-Obfuscation VAR+ Launcher - System
// Author: Jonathan Cheong, oscd.community
// Date: 2020-10-15
// Level: high
// Description: Detects Obfuscated use of Environment Variables to execute PowerShellThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events data connector is enabled in Sentinel to have this table available for querying.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ImagePath contains "/c" or ImagePath contains "/r") and (ImagePath contains "cmd" and ImagePath contains "\"set" and ImagePath contains "-f") and Provider_Name =~ "Service Control Manager"