// Title: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION - System
// Author: Timur Zinniatullin, oscd.community
// Date: 2020-10-13
// Level: high
// Description: Detects Obfuscated Powershell via VAR++ LAUNCHERThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events are being collected and ingested into Sentinel for this table to be available.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ImagePath contains "{0}" or ImagePath contains "{1}" or ImagePath contains "{2}" or ImagePath contains "{3}" or ImagePath contains "{4}" or ImagePath contains "{5}") and (ImagePath contains "&&set" and ImagePath contains "cmd" and ImagePath contains "/c" and ImagePath contains "-f") and Provider_Name =~ "Service Control Manager"