// Title: Invoke-Obfuscation Via Stdin - System
// Author: Nikita Nazarov, oscd.community
// Date: 2020-10-12
// Level: high
// Description: Detects Obfuscated Powershell via Stdin in ScriptsThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Make sure to have the Windows Security Events connector enabled in Sentinel to collect these logs.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ImagePath contains "environment" or ImagePath contains "invoke" or ImagePath contains "input") and (ImagePath contains "set" and ImagePath contains "&&") and Provider_Name =~ "Service Control Manager"