// Title: Invoke-Obfuscation Via Use MSHTA - Security
// Author: Nikita Nazarov, oscd.community
// Date: 2020-10-09
// Level: high
// Description: Detects Obfuscated Powershell via use MSHTA in ScriptsThis table contains security-related events, including event ID 4697. Ensure that the Windows Security Events connector is installed in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where ServiceFileName contains "mshta" and ServiceFileName contains "vbscript:createobject" and ServiceFileName contains ".run" and ServiceFileName contains "window.close"