// Title: Invoke-Obfuscation STDIN+ Launcher - System
// Author: Jonathan Cheong, oscd.community
// Date: 2020-10-15
// Level: high
// Description: Detects Obfuscated use of stdin to execute PowerShellThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security events are being collected and sent to Microsoft Sentinel for this table to be populated.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where ((ImagePath contains "/c" or ImagePath contains "/r") and (ImagePath contains "cmd" and ImagePath contains "powershell") and Provider_Name =~ "Service Control Manager") and (ImagePath contains "noexit" or (ImagePath contains "input" and ImagePath contains "$"))