// Title: Invoke-Obfuscation VAR+ Launcher - PowerShell Module
// Author: Jonathan Cheong, oscd.community
// Date: 2020-10-15
// Level: high
// Description: Detects Obfuscated use of Environment Variables to execute PowerShellThis table contains security-related events from Windows machines. Make sure to have the Microsoft-Windows-Security-Auditing component enabled in your Sentinel workspace to have access to this table.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where Payload matches regex "cmd.{0,5}(?:/c|/r)(?:\\s|)"set\\s[a-zA-Z]{3,6}.*(?:\\{\\d\\}){1,}\\\\"\\s+?-f(?:.*\\)){1,}.*""