// Title: Invoke-Obfuscation Via Use Rundll32 - PowerShell Module
// Author: Nikita Nazarov, oscd.community
// Date: 2019-10-08
// Level: high
// Description: Detects Obfuscated Powershell via use Rundll32 in ScriptsThis table contains security events from Windows machines. Make sure to have the Windows Security Events data connector enabled in Microsoft Sentinel to query this table.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (Payload contains "value" or Payload contains "invoke" or Payload contains "comspec" or Payload contains "iex") and (Payload contains "&&" and Payload contains "rundll32" and Payload contains "shell32.dll" and Payload contains "shellexec_rundll")