// Title: Invoke-Obfuscation COMPRESS OBFUSCATION - Security
// Author: Timur Zinniatullin, oscd.community
// Date: 2020-10-18
// Level: medium
// Description: Detects Obfuscated Powershell via COMPRESS OBFUSCATIONThis table contains security-related events, including event ID 4697. Make sure to have the Windows Security Events data connector enabled in Microsoft Sentinel to query this table.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ServiceFileName contains "system.io.compression.deflatestream" or ServiceFileName contains "system.io.streamreader") and (ServiceFileName contains "new-object" and ServiceFileName contains "text.encoding]::ascii" and ServiceFileName contains "readtoend")