// Title: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION - PowerShell Module
// Author: Timur Zinniatullin, oscd.community
// Date: 2020-10-13
// Level: high
// Description: Detects Obfuscated Powershell via VAR++ LAUNCHERThis table contains security event logs from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to collect these logs.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where Payload matches regex "(?i)&&set.*(\\{\\d\\}){2,}\\\\"\\s+?-f.*&&.*cmd.*/c"