// Title: Invoke-Obfuscation Via Use Rundll32 - Security
// Author: Nikita Nazarov, oscd.community
// Date: 2020-10-09
// Level: high
// Description: Detects Obfuscated Powershell via use Rundll32 in ScriptsThis table contains security-related events, including event ID 4697. Make sure to have the necessary connectors or data sources configured in Sentinel to collect Windows security event logs.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ServiceFileName contains "value" or ServiceFileName contains "invoke" or ServiceFileName contains "comspec" or ServiceFileName contains "iex") and (ServiceFileName contains "&&" and ServiceFileName contains "rundll32" and ServiceFileName contains "shell32.dll" and ServiceFileName contains "shellexec_rundll")