// Title: Invoke-Obfuscation COMPRESS OBFUSCATION - PowerShell
// Author: Timur Zinniatullin, oscd.community
// Date: 2020-10-18
// Level: medium
// Description: Detects Obfuscated Powershell via COMPRESS OBFUSCATIONThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Make sure to have the necessary data connectors and configurations set up in Sentinel to collect and ingest Windows security event logs.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "system.io.compression.deflatestream" or ScriptBlockText contains "system.io.streamreader") and (ScriptBlockText contains "new-object" and ScriptBlockText contains "text.encoding]::ascii") and ScriptBlockText endswith "readtoend"