// Title: Invoke-Obfuscation STDIN+ Launcher - Security
// Author: Jonathan Cheong, oscd.community
// Date: 2020-10-15
// Level: high
// Description: Detects Obfuscated use of stdin to execute PowerShellThis table contains security-related events, including event ID 4697. Ensure that the necessary data connectors are set up to collect Windows security event logs in Microsoft Sentinel.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ServiceFileName contains "cmd" and ServiceFileName contains "powershell") and (ServiceFileName contains "${input}" or ServiceFileName contains "noexit") and (ServiceFileName contains " /c " or ServiceFileName contains " /r ")