// Title: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION - Security
// Author: Timur Zinniatullin, oscd.community
// Date: 2020-10-13
// Level: high
// Description: Detects Obfuscated Powershell via VAR++ LAUNCHERThis table contains security-related events, including event ID 4697. Make sure to have the necessary connectors or data sources configured in Sentinel to collect Windows security event logs.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where (ServiceFileName contains "{0}" or ServiceFileName contains "{1}" or ServiceFileName contains "{2}" or ServiceFileName contains "{3}" or ServiceFileName contains "{4}" or ServiceFileName contains "{5}") and (ServiceFileName contains "&&set" and ServiceFileName contains "cmd" and ServiceFileName contains "/c" and ServiceFileName contains "-f")