// Title: Invoke-Obfuscation RUNDLL LAUNCHER - Security
// Author: Timur Zinniatullin, oscd.community
// Date: 2020-10-18
// Level: medium
// Description: Detects Obfuscated Powershell via RUNDLL LAUNCHERThis table contains security-related events, including event ID 4697. Make sure to have the Windows Security Events data connector enabled in Microsoft Sentinel to query this table.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where ServiceFileName contains "rundll32.exe" and ServiceFileName contains "shell32.dll" and ServiceFileName contains "shellexec_rundll" and ServiceFileName contains "powershell"