// Title: Invoke-Obfuscation RUNDLL LAUNCHER - PowerShell Module
// Author: Timur Zinniatullin, oscd.community
// Date: 2020-10-18
// Level: medium
// Description: Detects Obfuscated Powershell via RUNDLL LAUNCHERThis table contains security-related events from Windows machines. Make sure to have the Windows Security Events data connector enabled in Microsoft Sentinel to query this table.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where Payload contains "rundll32.exe" and Payload contains "shell32.dll" and Payload contains "shellexec_rundll" and Payload contains "powershell"