// Title: Invoke-Obfuscation Via Use MSHTA - PowerShell Module
// Author: Nikita Nazarov, oscd.community
// Date: 2020-10-08
// Level: high
// Description: Detects Obfuscated Powershell via use MSHTA in ScriptsThis table contains security-related events from Windows machines. Make sure to have the Microsoft Security Event Log connector enabled in Sentinel to collect these events.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where Payload contains "set" and Payload contains "&&" and Payload contains "mshta" and Payload contains "vbscript:createobject" and Payload contains ".run" and Payload contains "(window.close)"