// Title: Invoke-Obfuscation CLIP+ Launcher - PowerShell Module
// Author: Jonathan Cheong, oscd.community
// Date: 2020-10-13
// Level: high
// Description: Detects Obfuscated use of Clip.exe to execute PowerShellThis table contains security event logs from Windows machines. Make sure to have the Windows Security Events connector enabled in Microsoft Sentinel to collect these logs.
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// ================================================================== 

SecurityEvent
| where Payload matches regex "cmd.{0,5}(?:/c|/r).+clip(?:\\.exe)?.{0,4}&&.+clipboard]::\\(\\s\\\\"\\{\\d\\}.+-f.+""