// Title: Password Protected ZIP File Opened (Email Attachment)
// Author: Florian Roth (Nextron Systems)
// Date: 2022-05-09
// Level: high
// Description: Detects the extraction of password protected ZIP archives. See the filename variable for more details on which file has been opened.This table contains security events for Windows systems. Make sure to have the Microsoft Security Events connector enabled in Sentinel to collect these logs.
// Tags: attack.defense-evasion, attack.initial-access, attack.t1027, attack.t1566.001
// ================================================================== 

SecurityEvent
| where TargetName contains "Microsoft_Windows_Shell_ZipFolder:filename" and TargetName contains "\\Temporary Internet Files\\Content.Outlook"