// Title: Password Protected ZIP File Opened
// Author: Florian Roth (Nextron Systems)
// Date: 2022-05-09
// Level: medium
// Description: Detects the extraction of password protected ZIP archives. See the filename variable for more details on which file has been opened.The SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. To query this table, ensure that the Windows Security events are being collected and sent to Sentinel. This can be achieved by installing the Microsoft Monitoring Agent on the Windows machines and configuring the appropriate data connectors in Sentinel.
// Tags: attack.defense-evasion, attack.t1027
// ================================================================== 

SecurityEvent
| where TargetName contains "Microsoft_Windows_Shell_ZipFolder:filename" and (not(TargetName contains "\\Temporary Internet Files\\Content.Outlook"))