// Title: Potential PowerShell Obfuscation Using Alias Cmdlets
// Author: frack113
// Date: 2023-01-08
// Level: low
// Description: Detects Set-Alias or New-Alias cmdlet usage. Which can be use as a mean to obfuscate PowerShell scriptsThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which can include information about PowerShell script execution. To query for events related to script block logging being enabled, you can filter on the EventID field and look for events with EventID 4104.
// Tags: attack.defense-evasion, attack.execution, attack.t1027, attack.t1059.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Set-Alias " or ScriptBlockText contains "New-Alias "