// Title: AWS RDS Master Password Change
// Author: faloker
// Date: 2020-02-12
// Level: medium
// Description: Detects the change of database master password. It may be a part of data exfiltration.The CloudTrail table in Microsoft Sentinel contains logs from AWS CloudTrail service. To have this table present in Sentinel, you need to ensure that you have integrated AWS CloudTrail logs into Sentinel by configuring the appropriate data connectors.
// Tags: attack.exfiltration, attack.t1020
// ================================================================== 

CloudTrail
| where eventName =~ "ModifyDBInstance" and eventSource =~ "rds.amazonaws.com" and 'responseElements.pendingModifiedValues.masterUserPassword' startswith ""