// Title: PowerShell Script With File Hostname Resolving Capabilities
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-05
// Level: medium
// Description: Detects PowerShell scripts that have capabilities to read files, loop through them and resolve DNS host entries.This table contains security event logs from Windows machines. Make sure to have the Windows Security Events data connector enabled in Microsoft Sentinel to have access to this table.
// Tags: attack.exfiltration, attack.t1020
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "Get-content " and ScriptBlockText contains "foreach" and ScriptBlockText contains "[System.Net.Dns]::GetHostEntry" and ScriptBlockText contains "Out-File"