// Title: Restore Public AWS RDS Instance
// Author: faloker
// Date: 2020-02-12
// Level: high
// Description: Detects the recovery of a new public database instance from a snapshot. It may be a part of data exfiltration.The CloudTrail table in Microsoft Sentinel contains logs related to AWS CloudTrail service. To have this table present in Sentinel, ensure that you have the AWS CloudTrail connector configured and collecting logs from your AWS environment.
// Tags: attack.exfiltration, attack.t1020
// ================================================================== 

CloudTrail
| where eventName =~ "RestoreDBInstanceFromDBSnapshot" and eventSource =~ "rds.amazonaws.com" and 'responseElements.publiclyAccessible' =~ "true"