// Title: AD Groups Or Users Enumeration Using PowerShell - ScriptBlock
// Author: frack113
// Date: 2021-12-15
// Level: low
// Description: Adversaries may attempt to find domain-level groups and permission settings.
// The knowledge of domain-level permission groups can help adversaries determine which groups exist and which users belong to a particular group.
// Adversaries may use this information to determine which users have elevated permissions, such as domain administrators.
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows Security events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.discovery, attack.t1069.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "get-ADPrincipalGroupMembership" or (ScriptBlockText contains "get-aduser" and ScriptBlockText contains "-f " and ScriptBlockText contains "-pr " and ScriptBlockText contains "DoesNotRequirePreAuth")