// Title: Local Groups Discovery - MacOs
// Author: Ömer Günal, Alejandro Ortuno, oscd.community
// Date: 2020-10-11
// Level: informational
// Description: Detects enumeration of local system groups
// Tags: attack.discovery, attack.t1069.001
// ================================================================== 

DeviceProcessEvents
| where ((ProcessCommandLine contains "-q" and ProcessCommandLine contains "group") and FolderPath endswith "/dscacheutil") or (ProcessCommandLine contains "/etc/group" and FolderPath endswith "/cat") or ((ProcessCommandLine contains "-list" and ProcessCommandLine contains "/groups") and FolderPath endswith "/dscl")