// Title: Suspicious Get Information for SMB Share - PowerShell Module
// Author: frack113
// Date: 2021-12-15
// Level: low
// Description: Adversaries may look for folders and drives shared on remote systems as a means of identifying sources of information to gather as a precursor for Collection and
// to identify potential systems of interest for Lateral Movement.
// Networks often contain shared network drives and folders that enable users to access file directories on various systems across a network.
// This table contains security-related events from Windows machines. Make sure to have the Microsoft Security Event Log connector enabled in Sentinel to collect these events.
// Tags: attack.discovery, attack.t1069.001
// ================================================================== 

SecurityEvent
| where Payload contains "get-smbshare" or ContextInfo contains "get-smbshare"