// Title: Suspicious Get Information for SMB Share
// Author: frack113
// Date: 2021-12-15
// Level: low
// Description: Adversaries may look for folders and drives shared on remote systems as a means of identifying sources of information to gather as
// a precursor for Collection and to identify potential systems of interest for Lateral Movement.
// Networks often contain shared network drives and folders that enable users to access file directories on various systems across a network.
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which may include information about PowerShell script execution. Ensure that the Windows Security Events data connector is enabled in Sentinel to collect these logs.
// Tags: attack.discovery, attack.t1069.001
// ================================================================== 

SecurityEvent
| where ScriptBlockText contains "get-smbshare"