// Title: Potential Credential Dumping Attempt Via PowerShell
// Author: oscd.community, Natalia Shornikova
// Date: 2020-10-06
// Level: medium
// Description: Detects a PowerShell process requesting access to "lsass.exe", which can be indicative of potential credential dumping attemptsThe SecurityEvent table in Microsoft Sentinel contains process access logs for Windows systems. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.credential-access, attack.t1003.001, detection.threat-hunting
// ================================================================== 

SecurityEvent
| where (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") and TargetImage endswith "\\lsass.exe"