// Title: RBAC Permission Enumeration Attempt
// Author: Leo Tsaousis (@laripping)
// Date: 2024-03-26
// Level: low
// Description: Detects identities attempting to enumerate their Kubernetes RBAC permissions.
// In the early stages of a breach, attackers will aim to list the permissions they have within the compromised environment.
// In a Kubernetes cluster, this can be achieved by interacting with the API server, and querying the SelfSubjectAccessReview API via e.g. a "kubectl auth can-i --list" command.
// This will enumerate the Role-Based Access Controls (RBAC) rules defining the compromised user's authorization.
// The KubeEvents table in Microsoft Sentinel contains Kubernetes audit logs. To have this table present, ensure that the Kubernetes audit logs are being collected and ingested into Sentinel.
// Tags: attack.t1069.003, attack.t1087.004
// ================================================================== 

KubeEvents
| where apiGroup =~ "authorization.k8s.io" and 'objectRef.resource' =~ "selfsubjectrulesreviews" and verb =~ "create"