// Title: Remote Task Creation via ATSVC Named Pipe - Zeek
// Author: Samir Bousseaden, @neu5rn
// Date: 2020-04-03
// Level: medium
// Description: Detects remote task creation via at.exe or API interacting with ATSVC namedpipeThis table contains information about SMB file events in Microsoft Sentinel. To have this table present, ensure that the necessary connectors are set up to collect data from Zeek logs related to SMB file activity.
// Tags: attack.lateral-movement, attack.persistence, car.2013-05-004, car.2015-04-001, attack.t1053.002
// ================================================================== 

SMBFileEvents
| where name =~ "atsvc" and path =~ "\\*\\IPC$"