// Title: Remote Task Creation via ATSVC Named Pipe
// Author: Samir Bousseaden
// Date: 2019-04-03
// Level: medium
// Description: Detects remote task creation via at.exe or API interacting with ATSVC namedpipeThe SecurityEvent table in Microsoft Sentinel contains security-related events, including detailed file share access events. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.lateral-movement, attack.persistence, car.2013-05-004, car.2015-04-001, attack.t1053.002
// ================================================================== 

SecurityEvent
| where AccessList contains "WriteData" and RelativeTargetName =~ "atsvc" and ShareName =~ "\\\\*\\IPC$"