// Title: HackTool - Potential Remote Credential Dumping Activity Via CrackMapExec Or Impacket-Secretsdump
// Author: SecurityAura
// Date: 2022-11-16
// Level: high
// Description: Detects default filenames output from the execution of CrackMapExec and Impacket-secretsdump against an endpoint.
// Tags: attack.credential-access, attack.t1003
// ================================================================== 

DeviceFileEvents
| where InitiatingProcessFolderPath endswith "\\svchost.exe" and FolderPath matches regex "\\\\Windows\\\\System32\\\\[a-zA-Z0-9]{8}\\.tmp$"