// Title: WCE wceaux.dll Access
// Author: Thomas Patzke
// Date: 2017-06-14
// Level: critical
// Description: Detects wceaux.dll access while WCE pass-the-hash remote command execution on source host
// Tags: attack.credential-access, attack.t1003, attack.s0005
// ================================================================== 

DeviceRegistryEvents
| where RegistryKey endswith "\\wceaux.dll"