// Title: Applications That Are Using ROPC Authentication Flow
// Author: Mark Morowczynski '@markmorow', Bailey Bercik '@baileybercik'
// Date: 2022-06-01
// Level: medium
// Description: Resource owner password credentials (ROPC) should be avoided if at all possible as this requires the user to expose their current password credentials to the application directly.
// The application then uses those credentials to authenticate the user against the identity provider.
// This table contains Azure AD sign-in logs. Ensure that Azure AD logs are being collected and stored in Microsoft Sentinel to query this table.
// Tags: attack.t1078, attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.initial-access
// ================================================================== 

SigninLogs
| where 'properties.message' =~ "ROPC"