// Title: Application Using Device Code Authentication Flow
// Author: Mark Morowczynski '@markmorow', Bailey Bercik '@baileybercik'
// Date: 2022-06-01
// Level: medium
// Description: Device code flow is an OAuth 2.0 protocol flow specifically for input constrained devices and is not used in all environments.
// If this type of flow is seen in the environment and not being used in an input constrained device scenario, further investigation is warranted.
// This can be a misconfigured application or potentially something malicious.
// This table contains Azure AD sign-in logs. Ensure that Azure AD logs are being collected and ingested into Microsoft Sentinel to query this table.
// Tags: attack.t1078, attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.initial-access
// ================================================================== 

SigninLogs
| where 'properties.message' =~ "Device Code"