// Title: Azure Login Bypassing Conditional Access Policies
// Author: Josh Nickels, Marius Rothenbücher
// Date: 2025-01-08
// Level: high
// Description: Detects a successful login to the Microsoft Intune Company Portal which could allow bypassing Conditional Access Policies and InTune device trust using a tool like TokenSmith.
// The OfficeActivity table in Microsoft Sentinel contains audit logs related to Microsoft 365 services. Ensure that the Microsoft 365 connector is set up and collecting data in Sentinel to have this table available for querying.
// Tags: attack.defense-evasion, attack.t1078
// ================================================================== 

OfficeActivity
| where (ApplicationId =~ "9ba1a5c7-f17a-4de9-a1f1-6178c8d51223" and Operation =~ "UserLoggedIn" and RequestType =~ "Cmsi:Cmsi" and ResultStatus =~ "Success") and (not(ObjectId =~ "0000000a-0000-0000-c000-000000000000"))