// Title: Increased Failed Authentications Of Any Type
// Author: Mark Morowczynski '@markmorow', MikeDuddington, '@dudders1'
// Date: 2022-08-11
// Level: medium
// Description: Detects when sign-ins increased by 10% or greater.This table contains Azure Active Directory sign-in logs. Make sure to have Azure Active Directory logs enabled in Microsoft Sentinel to query this table.
// Tags: attack.defense-evasion, attack.t1078
// ================================================================== 

SigninLogs
| where Count =~ "<10%" and Status =~ "failure"