// Title: Measurable Increase Of Successful Authentications
// Author: Mark Morowczynski '@markmorow', MikeDuddington, '@dudders1', Tim Shelton
// Date: 2022-08-11
// Level: low
// Description: Detects when successful sign-ins increased by 10% or greater.This table contains Azure Active Directory sign-in logs. To have this table present in Microsoft Sentinel, ensure that Azure Active Directory logs are being ingested and enabled in the Azure Sentinel workspace.
// Tags: attack.defense-evasion, attack.t1078
// ================================================================== 

SigninLogs
| where Count =~ "<10%" and Status =~ "Success"