// Title: Suspicious SignIns From A Non Registered Device
// Author: Harjot Singh, '@cyb3rjy0t'
// Date: 2023-01-10
// Level: high
// Description: Detects risky authentication from a non AD registered device without MFA being required.The equivalent table in Microsoft Sentinel for Azure signin logs. Make sure to have the Azure Activity Log solution enabled in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1078
// ================================================================== 

SigninLogs
| where AuthenticationRequirement =~ "singleFactorAuthentication" and 'DeviceDetail.trusttype' =~ "" and RiskState =~ "atRisk" and Status =~ "Success"