// Title: DHCP Server Loaded the CallOut DLL
// Author: Dimitrios Slamaris
// Date: 2017-05-15
// Level: high
// Description: This rule detects a DHCP server in which a specified Callout DLL (in registry) was loadedThe SecurityEvent table in Microsoft Sentinel contains Windows security event logs. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1574.002
// ================================================================== 

SecurityEvent
| where Provider_Name =~ "Microsoft-Windows-DHCP-Server"