// Title: Microsoft Defender Blocked from Loading Unsigned DLL
// Author: Bhabesh Raj
// Date: 2022-08-02
// Level: high
// Description: Detects Code Integrity (CI) engine blocking Microsoft Defender's processes (MpCmdRun and NisSrv) from loading unsigned DLLs which may be an attempt to sideload arbitrary DLLThe SecurityEvent table in Microsoft Sentinel contains security-related events and logs from Windows systems. To have this table present, ensure that the Windows Security Events data connector is enabled in Microsoft Sentinel.
// Tags: attack.defense-evasion, attack.t1574.002
// ================================================================== 

SecurityEvent
| where ProcessPath endswith "\\MpCmdRun.exe" or ProcessPath endswith "\\NisSrv.exe"