// Title: Suspicious Unsigned Thor Scanner Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-29
// Level: high
// Description: Detects loading and execution of an unsigned thor scanner binary.This table contains information about image loading events on Windows systems. Ensure that the Microsoft Defender for Endpoint data connector is enabled in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.t1574.002
// ================================================================== 

ImageLoadEvents
| where ((FolderPath endswith "\\thor.exe" or FolderPath endswith "\\thor64.exe") and (InitiatingProcessFolderPath endswith "\\thor.exe" or InitiatingProcessFolderPath endswith "\\thor64.exe")) and (not((Signature =~ "Nextron Systems GmbH" and SignatureStatus =~ "valid" and Signed =~ "true")))