// Title: Modify Group Policy Settings - ScriptBlockLogging
// Author: frack113
// Date: 2022-08-19
// Level: medium
// Description: Detect malicious GPO modifications can be used to implement many other malicious behaviors.The SecurityEvent table in Microsoft Sentinel contains Windows security event logs, which would include logs related to PowerShell script execution. Ensure that the Windows Security Events data connector is enabled in Sentinel to have access to this table.
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1484.001
// ================================================================== 

SecurityEvent
| where (ScriptBlockText contains "GroupPolicyRefreshTimeDC" or ScriptBlockText contains "GroupPolicyRefreshTimeOffsetDC" or ScriptBlockText contains "GroupPolicyRefreshTime" or ScriptBlockText contains "GroupPolicyRefreshTimeOffset" or ScriptBlockText contains "EnableSmartScreen" or ScriptBlockText contains "ShellSmartScreenLevel") and ScriptBlockText contains "\\SOFTWARE\\Policies\\Microsoft\\Windows\\System"