// Title: Application Removed Via Wmic.EXE
// Author: frack113
// Date: 2022-01-28
// Level: medium
// Description: Detects the removal or uninstallation of an application via "Wmic.EXE".
// Tags: attack.execution, attack.t1047
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains "call" and ProcessCommandLine contains "uninstall") and (FolderPath endswith "\\WMIC.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")