// Title: ImagingDevices Unusual Parent/Child Processes
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-27
// Level: high
// Description: Detects unusual parent or children of the ImagingDevices.exe (Windows Contacts) process as seen being used with Bumblebee activity
// Tags: attack.defense-evasion, attack.execution
// ================================================================== 

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\ImagingDevices.exe" or (FolderPath endswith "\\ImagingDevices.exe" and (InitiatingProcessFolderPath endswith "\\WmiPrvSE.exe" or InitiatingProcessFolderPath endswith "\\svchost.exe" or InitiatingProcessFolderPath endswith "\\dllhost.exe"))