// Title: Potentially Suspicious DMP/HDMP File Creation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-07
// Level: medium
// Description: Detects the creation of a file with the ".dmp"/".hdmp" extension by a shell or scripting application such as "cmd", "powershell", etc. Often created by software during a crash. Memory dumps can sometimes contain sensitive information such as credentials. It's best to determine the source of the crash.
// Tags: attack.defense-evasion
// ================================================================== 

DeviceFileEvents
| where (InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\cscript.exe" or InitiatingProcessFolderPath endswith "\\mshta.exe" or InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe" or InitiatingProcessFolderPath endswith "\\wscript.exe") and (FolderPath endswith ".dmp" or FolderPath endswith ".dump" or FolderPath endswith ".hdmp")