// Title: Wab/Wabmig Unusual Parent Or Child Processes
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-12
// Level: high
// Description: Detects unusual parent or children of the wab.exe (Windows Contacts) and Wabmig.exe (Microsoft Address Book Import Tool) processes as seen being used with bumblebee activity
// Tags: attack.defense-evasion, attack.execution
// ================================================================== 

DeviceProcessEvents
| where (InitiatingProcessFolderPath endswith "\\wab.exe" or InitiatingProcessFolderPath endswith "\\wabmig.exe") or ((FolderPath endswith "\\wab.exe" or FolderPath endswith "\\wabmig.exe") and (InitiatingProcessFolderPath endswith "\\WmiPrvSE.exe" or InitiatingProcessFolderPath endswith "\\svchost.exe" or InitiatingProcessFolderPath endswith "\\dllhost.exe"))