// Title: HackTool - DInjector PowerShell Cradle Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2021-12-07
// Level: critical
// Description: Detects the use of the Dinject PowerShell cradle based on the specific flags
// Tags: attack.defense-evasion, attack.t1055
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains " /am51" and ProcessCommandLine contains " /password"