// Title: Clipboard Data Collection Via OSAScript
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-01-31
// Level: high
// Description: Detects possible collection of data from the clipboard via execution of the osascript binary
// Tags: attack.collection, attack.execution, attack.t1115, attack.t1059.002
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "osascript" and ProcessCommandLine contains " -e " and ProcessCommandLine contains "clipboard"