// Title: Successful Overpass the Hash Attempt
// Author: Roberto Rodriguez (source), Dominik Schaudel (rule)
// Date: 2018-02-12
// Level: high
// Description: Detects successful logon with logon type 9 (NewCredentials) which matches the Overpass the Hash behavior of e.g Mimikatz's sekurlsa::pth module.The SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. Ensure that you have the necessary data connectors and configurations set up in Sentinel to collect and ingest security events from Windows machines.
// Tags: attack.lateral-movement, attack.s0002, attack.t1550.002
// ================================================================== 

SecurityEvent
| where AuthenticationPackageName =~ "Negotiate" and LogonProcessName =~ "seclogo" and LogonType == 9