// Title: JXA In-memory Execution Via OSAScript
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-01-31
// Level: high
// Description: Detects possible malicious execution of JXA in-memory via OSAScript
// Tags: attack.t1059.002, attack.t1059.007, attack.execution
// ================================================================== 

DeviceProcessEvents
| where ((ProcessCommandLine contains " -l " and ProcessCommandLine contains "JavaScript") or ProcessCommandLine contains ".js") and (ProcessCommandLine contains "osascript" and ProcessCommandLine contains " -e " and ProcessCommandLine contains "eval" and ProcessCommandLine contains "NSData.dataWithContentsOfURL")