// Title: OSACompile Run-Only Execution
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-01-31
// Level: high
// Description: Detects potential suspicious run-only executions compiled using OSACompile
// Tags: attack.t1059.002, attack.execution
// ================================================================== 

DeviceProcessEvents
| where ProcessCommandLine contains "osacompile" and ProcessCommandLine contains " -x " and ProcessCommandLine contains " -e "