// Title: Guest Account Enabled Via Sysadminctl
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-02-18
// Level: low
// Description: Detects attempts to enable the guest account using the sysadminctl utility
// Tags: attack.initial-access, attack.t1078, attack.t1078.001
// ================================================================== 

DeviceProcessEvents
| where (ProcessCommandLine contains " -guestAccount" and ProcessCommandLine contains " on") and FolderPath endswith "/sysadminctl"