// Title: Critical Hive In Suspicious Location Access Bits Cleared
// Author: Florian Roth (Nextron Systems)
// Date: 2017-05-15
// Level: high
// Description: Detects events from the Kernel-General ETW indicating that the access bits of a hive with a system like hive name located in the temp directory have been reset.
// This occurs when an application tries to access a hive and the hive has not be recognized since the last 7 days (by default).
// Registry hive dumping utilities such as QuarksPwDump were seen emitting this behavior.
// The SecurityEvent table in Microsoft Sentinel contains Windows security event logs. To query this table, ensure that you have the necessary connectors and data sources configured in Sentinel to collect Windows security event logs.
// Tags: attack.credential-access, attack.t1003.002
// ================================================================== 

SecurityEvent
| where (HiveName contains "\\Temp\\SAM" or HiveName contains "\\Temp\\SECURITY") and Provider_Name =~ "Microsoft-Windows-Kernel-General"