// Title: Possible Impacket SecretDump Remote Activity
// Author: Samir Bousseaden, wagga
// Date: 2019-04-03
// Level: high
// Description: Detect AD credential dumping using impacket secretdump HKTLThe SecurityEvent table in Microsoft Sentinel contains security-related events, including object access events. Ensure that the necessary data connectors are set up to collect Windows security logs in Sentinel to query this table.
// Tags: attack.credential-access, attack.t1003.002, attack.t1003.004, attack.t1003.003
// ================================================================== 

SecurityEvent
| where (RelativeTargetName contains "SYSTEM32\\" and RelativeTargetName contains ".tmp") and ShareName =~ "\\\\*\\ADMIN$"