// Title: Possible Impacket SecretDump Remote Activity - Zeek
// Author: Samir Bousseaden, @neu5ron
// Date: 2020-03-19
// Level: high
// Description: Detect AD credential dumping using impacket secretdump HKTL. Based on the SIGMA rules/windows/builtin/win_impacket_secretdump.ymlThe equivalent table in Microsoft Sentinel for SMB file activity logs. Ensure that the Zeek connector is enabled in Sentinel to collect data from Zeek logs.
// Tags: attack.credential-access, attack.t1003.002, attack.t1003.004, attack.t1003.003
// ================================================================== 

SmbFiles
| where name contains "SYSTEM32\\" and name endswith ".tmp" and (path contains "\\" and path contains "ADMIN$")