// Title: Transferring Files with Credential Data via Network Shares
// Author: Teymur Kheirkhabarov, oscd.community
// Date: 2019-10-22
// Level: medium
// Description: Transferring files with well-known filenames (sensitive files with credential data) using network sharesThe SecurityEvent table in Microsoft Sentinel contains security-related events from Windows machines. To have this table present, ensure that the Windows Security Events connector is enabled in your Sentinel workspace.
// Tags: attack.credential-access, attack.t1003.002, attack.t1003.001, attack.t1003.003
// ================================================================== 

SecurityEvent
| where RelativeTargetName contains "\\mimidrv" or RelativeTargetName contains "\\lsass" or RelativeTargetName contains "\\windows\\minidump\\" or RelativeTargetName contains "\\hiberfil" or RelativeTargetName contains "\\sqldmpr" or RelativeTargetName contains "\\sam" or RelativeTargetName contains "\\ntds.dit" or RelativeTargetName contains "\\security"