// Title: Transferring Files with Credential Data via Network Shares - Zeek
// Author: @neu5ron, Teymur Kheirkhabarov, oscd.community
// Date: 2020-04-02
// Level: medium
// Description: Transferring files with well-known filenames (sensitive files with credential data) using network sharesThis table contains information about SMB file activity. To have this table present in Microsoft Sentinel, ensure that the Zeek logs are being ingested and parsed correctly.
// Tags: attack.credential-access, attack.t1003.002, attack.t1003.001, attack.t1003.003
// ================================================================== 

SmbFiles
| where name in~ ("\\mimidrv", "\\lsass", "\\windows\\minidump\\", "\\hiberfil", "\\sqldmpr", "\\sam", "\\ntds.dit", "\\security")